# ACTUELE ONDERZOEKSTHEMA'S EN -VRAGEN 

## INLEIDING 

Op basis van de huidige onderzoeksbalans formuleren we hieronder een aantal onderzoeksthema's en bijhorende vragen die momenteel actueel zijn. Sommige zijn heel algemeen, andere specifiek geformuleerd op basis van lopend onderzoek. Het hoeft geen betoog dat dit een tijdsopname is en thema's en onderzoeksvragen continu aan herziening toe zijn.

## PROSPECTIE EN WAARDERING VAN VINDPLAATSEN 

Binnen de context van Malta archeologie is er een dringende noodzaak tot de ontwikkeling van aangepaste terreinmethodieken voor de opsporing en waardering van vindplaatsen. Terwijl in het algemeen de aandacht voor steentijd weliswaar is toegenomen, zien we dat het prospectief onderzoek vooral gebeurt aan de hand van booronderzoek en een focus heeft op het holocene landschap. Er zijn echter een aantal nadelen aan deze methodiek verbonden. Zo zijn archeologische boringen weinig geschikt voor vindplaatsen met een lage densiteit. Daarnaast laten ze niet altijd toe om afgedekte bodems te herkennen en wordt dit aspect overigens ook vaak niet meegenomen in de vraagstelling. Tot slot merken we op dat veldkartering en de bemonstering van de ploeglaag nauwelijks wordt toegepast in het kader van Malta-archeologie. Voor aangeploegde vindplaatsen betekent dit dat ze worden gewaardeerd op basis van een beperkt deel van het materiaal. Terwijl de wetenschappelijke waarde van ploeglaagsites zeker in vraag mag gesteld worden[^470], dient deze echter ook steeds afgewogen worden ten opzichte van de hoeveelheid bronnen die er voor een bepaalde periode voorhanden is. Met name voor het paleolithicum is dit bijzonder schaars.

Er is in Vlaanderen een hoog potentieel aan goed bewaarde vindplaatsen die afgedekt zijn door een dik pakket aan alluviale, colluviale en/of eolische sedimenten. Bij ontginningsactiviteiten (bijv. groeves) bagger- en waterinfrastructuur en diepe bouwputten (bijv. in stedelijke contexten) worden deze aangesneden en kunnen waardevolle sites verloren gaan. Om na te gaan of er potentieel is voor de bewaring van paleolithische vindplaats is in de eerste plaats een goed begrip van het paleolandschap nodig. Dat impliceert de kartering van het landschap door middel van boringen, profielputten of geofysisch en -technisch onderzoek (of een combinatie van deze methodes), maar eveneens dient een staalname en analyse gericht op dateringen, paleoecologie en geomorfologie in de prospectieve fase overwogen te worden.

Van belang is dat er niet enkel gefocust wordt op de grote riviervalleien, maar ook erkend wordt dat beekdalen waardevol kunnen zijn. Dat dergelijke beekvalleien ook potentieel kunnen bieden voor oudere vondsten, wordt aangetoond door de ontdekking van talrijke mousteriaanvindplaatsen, geassocieerd met pleistoceen bot langs de Kleine Gete net over de grens ter hoogte van Orp-jauche en Hannut (Waals Brabant)[^471]. Daarnaast is het van belang dat het onderzoek zich niet enkel richt op mogelijke bewoningslocaties maar dat er ook oog is voor watergebonden archeologie, zoals de aanwezigheid van afvaldumps, deposities, visfuiken en infrastructuur.

Het opsporen en waarderen van dergelijke vindplaatsen vergt echter een specifieke expertise en aanpak en blijkt vaak moeilijk te realiseren binnen de huidige Malta-praktijk. Samenwerkingen met de academische sector en het uitrollen van een (supra)regionale aanpak/afwegingskader en onderzoeksagenda kan soelaas bieden, maar zal weinig zoden aan de dijk brengen indien geen extra middelen worden voorzien voor dit type van onderzoek.

Vanuit deze problematiek stellen we ook de beleidskeuze in vraag waarbij in de huidige archeologische praktijk niet ingezet wordt op prospectieve kenniswinst. Binnen de preventieve archeologie wordt (omwille van de projectgebonden aanpak) onderzoek dat inzichten kan bieden in het potentieel van het omringende gebied, niet of nauwelijks uitgevoerd. Maar net die prospectieve kennis is noodzakelijk om onze kennis omtrent de evolutie van het (paleo)landschap in kaart te brengen en via voortschrijdend inzicht het paleolithisch potentieel beter te begrijpen.

Los van bovenstaande bedenkingen, formuleren we hierbij een aantal mogelijke onderzoeksvragen die tijdens de prospectie en waardering van vindplaatsen kunnen gebruikt worden:

*Landschap:*

Wat is de algemene paleolandschappelijke evolutie en in welke eenheden kunnen vindplaatsen voorkomen? Kan op basis van de paleolandschappelijke eenheden waarbinnen ze verwacht worden, uitspraken gedaan worden omtrent de ouderdom? Indien niet, welke stappen dienen ondernomen te worden om daar duidelijkheid over te verschaffen?

Wat is de impact van erosie- en sedimentatieprocessen binnen het gebied op de gaafheid en zichtbaarheid van potentiele vindplaatsen?

In welke zin bieden bodemkundige aspecten inzicht over de gaafheid van de vindplaats? Impliceert de afwezigheid van macroscopisch zichtbare pedologische processen ook dat er geen vindplaats aanwezig kan zijn? Zijn er andere verklaringen voor het ontbreken van bodemontwikkeling? Indien deze afwezig is, maar de aanwezigheid van vindplaatsen niet uitgesloten kan worden, hoe kan hier tijdens de prospectiefase mee omgegaan worden?

Kunnen de eenheden gedateerd worden? En op welke wijze?

Zijn er mogelijkheden tot de reconstructie van het paleolandschap?

*Archeologische resten:*

In welke eenheden en op welke dieptes bevinden zich de archeologische vindplaats(en)? Zijn de resten geassocieerd met een paleobodem?

In het geval van niet-afgedekte vindplaatsen: Wat is de verhouding tussen artefacten in de bouwvoor en artefacten die zich nog *in situ* (onder de bouwvoor) bevinden?

Hoe kunnen archeologische resten zich manifesteren (sporen, artefactenconcentraties, botanische resten ...)?

Zijn er indicaties omtrent de vondstdichtheid en eventuele clustering? Kunnen clusters afgebakend worden?

Kunnen reeds uitspraken gedaan worden omtrent de aard en datering van de vindplaats(en)? Zijn er elementen aan het licht gekomen omtrent een eventuele fasering van de archeologische vindplaats?

Op welke wijze kan omgegaan worden met verschillende densiteit en grootte van de te prospecteren clusters?

In welke zin heeft de prospectiemethode impact op de trefkans op artefacten? Wat impliceert dit voor de interpretatie en waardering van de vindplaats?

Welk afwegingskader wordt gebruikt voor het verder onderzoek? Op basis van welke wetenschappelijke inzichten is dit onderbouwd?

Komen de resultaten overeen met de archeologische verwachting die voorafgaandelijk werd opgesteld?

## EVOLUTIE VAN DE BEWONINGSGESCHIEDENIS IN FUNCTIE VAN HET PALEOLANDSCHAP 

Voor het vroegpaleolithicum zijn betrouwbare signalen van menselijke aanwezigheid voorlopig beperkt. Elke valideerbare vondst uit deze periode lijkt op dit moment van gewestelijk belang.

Voor het middenpaleolithicum is er een onevenwicht tussen intrinsieke mogelijkheden van het aanwezige erfgoed enerzijds en de feitelijke onderzoekstoestand anderzijds. Om die verhouding recht te trekken is er in feite behoefte aan een soort 'masterplan'. Drie regio's in het bijzonder hebben een groot paleolithisch potentieel. Enerzijds zijn er de loessgebieden in het oosten en zuidwesten van het gewest, vooral voor stratigrafisch onderzoek, maar potentieel ook met unieke in situ condities zoals in Kesselt-Op De Schans. Anderzijds is er de Vlaamse Vallei, een grote 'sedimentval' waarin naast lithisch materiaal ook bot is aangetroffen. Tot slot wijst recent onderzoek in het kustgebied en de Noordzee op een rijk, maar nog beperkt in kaart gebracht potentieel[^472]. In andere regio's zijn dergelijke contexten minder voorhanden, maar a priori uitgesloten zijn ze nergens. Van belang in het middenpaleolithicum lijkt dan ook elke vindplaats die, óf zich in context bevindt, óf dateerbaar is, óf met organisch materiaal geassocieerd kan worden.

Voor het laatpaleolithicum is de toestand moeilijker in te schatten. Ook hier kan, zoals voor het vroegpaleolithicum, worden geargumenteerd dat élke valideerbare vindplaats van belang is.

Voor het finaalpaleolithicum is de verhouding tussen de 'voorraad' bronnenmateriaal en het hierop gevoerde onderzoek wellicht iets evenwichtiger. Alle overwegingen in acht genomen, lijken voor het finaalpaleolithicum sites die aan één van de volgende criteria voldoen van belang: archeologisch in situ, stratigrafisch in situ, dateerbaar, aanwezigheid van organisch materiaal, mogelijkheid tot paleoecologisch onderzoek.

Bovenstaande oplijsting betekent niet dat vindplaatsen die grotendeels of volledig opgenomen zijn in de bouwvoor geen wetenschappelijke waarde hebben. Ze bieden inzichten over de bewoningsgeschiedenis in gebieden waar geen of weinig kansen zijn tot *in situ* bewaring en vullen dus in belangrijke mate de paleolithische dataset aan. Ze verdienen met andere woorden de nodige aandacht, maar via een aangepaste onderzoeksstrategie.

*Onderzoeksvragen:*

Wanneer, waar en onder welke landschappelijke en klimatologische omstandigheden verschijnen de verschillende paleolithische culturen en culturele tradities op het toneel? Wat is hun geografische en chronologische reikwijdte, en wat zijn de onderlinge relaties?

Waar zijn afzettingen uit het midden- en laatpleistoceen bewaard?

Wat is de aard en diepte van deze afzettingen? En wat zeggen deze over een mogelijke aanwezigheid van archeologische en paleo-ecologische resten?

Wat is de ouderdom en het afzettingsmilieu van de voorkomende formaties en hoe zag het paleoreliëf eruit?

Welke tafonomische processen hebben ingegrepen op de vindplaats? Hoe snel werd de vindplaats afgedekt? Wat betekent dit voor de verdere analyse en interpretatie van de archeologische resten?

Wanneer en op welke wijze zijn gebieden die nu onder water staan door en mens gebruikt, wat zijn de karakteristieken van die landschappelijke zones en hoe verhoudt dit gebruik zich tot dat wat we van het land kennen?

## GEBRUIK VAN HET LANDSCHAP EN NEDERZETTINGSSYSTEMEN 

Binnen welke landschappelijke eenheden bevinden de vindplaatsen zich? In welke zin sluit dit aan bij het gekende nederzettingspatroon?

Bijv. in welke mate speelt de aanwezigheid van water en/of (micro)topografie een rol?

Kan informatie vergaard worden omtrent het landschap ten tijde van de menselijke bewoning? Hoe ontwikkelde zich dit?

Wat is de functie en datering van de vindplaatsen?

Is er een relatie tussen de functie van de vindplaats en landschappelijke ligging?

Zijn er mogelijkheden tot absolute dateringen? Zo ja, op welk materiaal en met welke methode? Zijn er aspecten die de betrouwbaarheid van de datering(en) beïnvloed hebben?

In hoeverre wijzen de gegevens op continuïteit of juist onderbreking of abrupte beëindiging van bewoning?

Is er een nederzettingssysteem in beekvalleien aanwezig, en zo ja, hoe verhoudt dit zich tot andere regio's?

In welke zin is er een relatie met gekende paleovalleien? Relatie met tafonomie of nederzettingspatroon?

Sitecomplexen: wat is de reden waarom op deze plek een zogenaamd sitecomplex voorkomt? Aantrekkelijk landschap, tafonomie, resultaat van prospectiestrategie? Gaat het hier om zogenaamde 'persistent places' en wat zijn daarvan de kenmerken en context?

Op welke wijze maakte men gebruik van de biotische en abiotische grondstoffen in de onmiddellijke nabijheid van de vindplaats? Geven deze inzichten omtrent seizoenaliteit?

Op welke wijze gaan paleolithische groepen om met wijzigende klimatologische omstandigen, zowel op lange termijn (bijv. neanderthalergedrag in functie van de afwisseling van warme en koude periodes tijdens het midden- en laat-pleistoceen) als in periodes van snelle klimatologische veranderingen (bijv. de finaalpaleolithische groepen op het einde van het glaciaal)?

## RUIMTELIJKE ORGANISATIE BINNEN DE VINDPLAATS/CLUSTER 

Werden sporen aangetroffen (al dan niet latent)? Hoe kunnen ze geïnterpreteerd worden en wat is hun relatie tot de artefactenspreiding?

Op basis van welke kenmerken kan er een onderscheid worden gemaakt tussen antropogene en natuurlijke sporen? Welke rol kan micromorfologisch onderzoek hierin spelen?

Is er sprake van configuraties van grondsporen of stenen die duiden op structuren, zoals hutten, tenten of andere faciliteiten (bijv. windschermen, droogrekken, opslagkuilen)?

Zijn er oppervlaktehaarden, kuilhaarden en andere stookplaatsen aanwezig en wat zijn hun kenmerken? Wat is de archeologische neerslag in de directe omgeving van de haarden?

Wat zijn de ruimtelijke en chronologische relaties tussen (verschillende categorieën) vondstmateriaal?

Welke archeologische verschijnselen bevinden zich in de 'lege' zones en in de periferie van vondstrijke zones en hoe dienen deze verschijnselen te worden geïnterpreteerd?

Hoe manifesteert zich de horizontale spreiding van de vondsten? Gaat het om een hoge of lage densiteit? Tekenen zich afzonderlijke clusters af? Zo ja, wat is de onderlinge relatie tussen die verschillende clusters?

Is er op één en dezelfde locatie sprake van meerdere fasen? Op welke manier kan dit onderbouwd worden? Zo ja: welke?

Is er sprake van specifieke activiteitenzones (jacht, slacht, vuursteenbewerking, mergextractie, ... ) ? Op welke wijze kan dit achterhaald worden?

Hoe manifesteert de verticale spreiding van de vondsten zich? Hoe kan deze geïnterpreteerd worden? Is er sprake van een (fantoom)stratigrafie?

## VOEDSELECONOMIE, RELATIE MENS EN MILIEU 

Zijn er aanwijzingen dat de mens reeds in het paleolithicum ingreep in het landschap en de vegetatie en/of fauna? Voorbeelden hiervan kunnen zijn: het creëren van artificiële bosbranden en impact op het faunabestand door jachttechnieken.

Zijn er macroresten aanwezig die als potentiële voedselresten kunnen worden geïnterpreteerd?

In welke mate zijn er residuen op het lithisch materiaal bewaard en bieden deze potentieel voor verder onderzoek?

## MATERIËLE CULTUUR 

In welke mate bieden de typotechnologische kenmerken van het materiaal inzichten omtrent de datering en eventuele fasering binnen het lithisch ensemble? In welke zin sluiten deze aan (of niet) bij eventueel beschikbare absolute of relatieve dateringen van de vindplaats?

Welke voorwerpen van organisch materiaal maakten deel uit van de materiële cultuur, wat zijn de kenmerken ervan en waarvoor werden ze gebruikt? Welke informatie biedt het voorwerp over de functie en levensloop (productie, onderhoud, afdanking) van het artefact?

Hoe werd met afval omgegaan?

Op welke wijze werden plantaardige en dierlijke bronnen gebruikt in het levensonderhoud en als grondstof voor voorwerpen en welke rol speelden deze bronnen in uitwisseling en ruil?

Wat zijn de technologische en typologische kenmerken en welke technieken van (vuur)steenbewerking (*chaîne opératoire*) zijn op de vindplaats toegepast?

Wat is de datering, functie en levensloop van werktuigen?

Wat is de herkomst van de gebruikte grondstofsoorten? Zijn er verschillen op vlak van reductiemethode, werktuigproductie of import/export?

## CULTURELE TRADITIES, SOCIALE RELATIES EN INTERACTIE 

Wat is de herkomst, mobiliteit en territoriumomvang van de paleolithische groepen en welke relaties zijn aantoonbaar met andere regio's binnen en buiten Vlaanderen?

Welke culturele elementen zijn herkenbaar binnen de materiële cultuur?

In welke mate kunnen de typochronologische kenmerken en samenstelling van microlieten binnen finaalpaleolithische culturen inzichten bieden omtrent de aanwezigheid en interactie van de verschillende culturele groepen (creswell-, federmesser-, ahrensburggroepen)? In welke mate zijn hier chronologische tendensen in te zien?

## MENSELIJKE RESTEN 

Momenteel zijn er geen menselijke resten gekend binnen Vlaanderen die dateren uit het paleolithicum. De bewaring van dierlijk botmateriaal (verbrand en onverbrand) op diverse locaties toont aan dat er wel degelijk dient rekening gehouden te worden met deze mogelijkheid.

Onderzoeksvragen die -- naast het standaardassessment (leeftijd, sexe, pathologieën, \...) - in dat geval kunnen gesteld worden zijn:

Op welke wijze werd in de vroege prehistorie omgegaan met de overledenen (context en kenmerken van het 'dodenbestel')?

Biedt het menselijk bot mogelijkheden tot dieetreconstructies? Welke analyses zijn aangewezen (bijv. isotopenonderzoek)? In welke zin sluiten ze aan bij de paleolandschappelijke context of geven ze aanvullende/nieuwe inzichten?

Wat is de ouderdom van het bot? Op welke manier kan het bot gedateerd worden (direct of indirect)?


[^470]: Van Gils *et* *al*. 2010.
[^471]: Van Dijck & Otte, 2019.
[^472]: Pieters *et al.* 2010; Amkreutz *et al.* 2018; Missiaen *et al.* 2018; Pieters *et al.* 2020.
