# BALANS VAN DE BRONNEN 

## INLEIDING 

Op dit moment valt nauwelijks in te schatten wat de 'voorraad' is van paleolithisch erfgoed in Vlaanderen. Terwijl altijd geldt dat een archeologische inventaris - in dit geval de CAI - maar een fractie omvat van het reëel aanwezige archeologische erfgoed (per definitie de tot hiertoe bekende sites), geldt deze beperking in nog veel grotere mate voor het paleolithicum. Door de soms diepe begraving van pleistocene oppervlakken zijn hier veel minder vaak kijkvensters op gericht dan op de latere periodes, die in principe allemaal het (huidige) holocene oppervlak hebben gebruikt en dus een veel grotere zichtbaarheid genieten.

De CAI laat daarnaast slechts een beperkte evaluatie toe van de geïnventariseerde sites. Zaken die van belang zijn voor steentijdonderzoek zoals het type site (bewoning, jachtkamp, grondstofextractie,...), de gaafheid, stratigrafische verbanden, aanwezigheid structuren (bijv. haarden), zijn niet systematisch ingevoerd en dus uit de CAI te halen. Het overzicht die we in de volgende paragrafen is opgemaakt, baseert zich dan ook grotendeels op basis van gepubliceerde data.

Tot slot zijn nog heel wat amateur-collecties niet opgenomen in de CAI en dus onbekend.

## BALANS VAN DE SITES 

Terwijl we, zoals hierboven gesteld, de voorraad aan paleolithisch erfgoed nauwelijks kennen, is het nog veel slechter gesteld met onze kennis van de toestand ervan. We gaven boven al een schets van algemene kansen op (goede) bewaring in de verschillende archeoregio's, maar echte validatie hiervan is voorlopig erg beperkt. De laatste decennia zijn vanuit academische hoek wel projecten opgestart die systematisch prospecteren naar goed bewaarde vindplaatsen en daarbij ook het

(paleo)landschappelijke kader mee in overweging nemen (bijv. Scheldepolders, laatglaciale duinen, Moervaartdepressie, Limburgse leemgroeves). Deze methodiek wordt enigszins ook binnen maltaonderzoek doorgetrokken, maar de toepassing ervan hangt sterk af van de draagkracht van specifieke projecten en expertise van de uitvoerder. Er is een sterke toename aan onderzoeken, met name sinds 2016, waarbij ook grootschalige en diepe ingrepen minstens aan een archeologisch vooronderzoek worden onderworpen. Toch valt op dat hierbij nauwelijks afgedekte paleolithische vindplaatsen zijn ontdekt, ondanks het aangetoonde potentieel in Vlaanderen. Dit lijkt er op te wijzen dat dit aspect onderbelicht wordt binnen Malta-archeologie. Nieuwe vindplaatsen blijken vooral eerder toevallig aan het licht te komen (bijv. Ruien -- Rosalinde[^261]). En indien er een systematische prospectie wordt uitgevoerd, is ze voornamelijk gericht op de top van laatglaciale afzettingen en richt ze zich zowel op de detectie van finaalpaleolithische als mesolithische vindplaatsen.

Voorlopig beperken we ons hier tot een korte schets van de algemene kenmerken en bewaringscondities van de sites zoals we die tot hiertoe in de verschillende periodes kennen.

### Vroeg- en middenpaleolithicum 

Door de zeer lange tijdsduur enerzijds en het beperkte aantal opgravingen anderzijds, kan ons beeld op deze periode alleen maar anekdotisch zijn.

We bespreken hieronder de belangrijkste referentievindplaatsen.

Ter hoogte van Kesselt en Veldwezelt zijn een reeks vindplaatsen aangetroffen in een voormalige

Maasarm die werd opgevuld met een loess sequentie en waarin verschillende paleolsols bewaard zijn

[^262]^.^ Concreet gaat het om volgende vindplaatsen: Kesselt-Nelissen[^263], Kesselt-Albert Kanaal[^264], Kesselt-Op de Schans (in sommige publicaties als Veldwezelt-Op de Schans benoemd)[^265] en Veldwezelt-Hezerwater[^266]. Te Kesselt -- Op de Schans gaat het oudste niveau met artefacten tenminste terug tot de aanvang van M.I.S. 10 voor 390.000 BP, het jongste niveau dateert uit MIS 5b. Daar waar bepaalde archeologische niveaus uitsluitend herwerkte lithische artefacten bevatten, zijn andere veel beter bewaard gebleven. Zo'n 10 meter onder het huidige maaiveld werd een in situ archeologisch niveau aangetroffen met vier lithische concentraties (ODS 1 tot en met 4), gedateerd op de overgang van MIS 9 naar MIS 8, die de neerslag vormen van enkele kortstondige fases van vuursteenbewerking. De ensembles tonen aan dat in deze periode verschillende reductiemethodes werden toepast: zowel discoïde, levallois als *simple prepared core* technologie. Naast lokaal geproduceerd materiaal werden ook geïmporteerde grote afslagen, schrabbers en levallois afslagen in vuursteen aangetroffen. Daarnaast bleken bepaalde lokaal geproduceerde producten geëxporteerd[^267].

Ook te Kesselt --Nelissen werd in een dikke loess sequentie een reeks stratigrafische eenheden aangetroffen die geassocieerd zijn met paleolithische vindplaatsen en dateren in respectievelijk MIS 5, MIS 6 en MIS 7[^268].

De vindplaats Veldwezelt -- Hezerwater werd eveneens aangetroffen in een leemgroeve. Er werden binnen de loess sequentie 24 archeologische niveaus aangetroffen, waarvan er vijf *in situ* bewaarde vindplaatsen materiaal bevatten dat in detail bestudeerd is[^269]. Ze dateren uit de late Saale (MIS 6) en de vroege midden-Weichsel (MIS 3). Er werden tevens verschillende niveaus behorende tot het vroegglaciaal onderzocht. De vindplaatsen vertonen een grote diversiteit in, zowel op vlak van technologische en typologische kenmerken van het materiaal, de aanwezigheid van fauna, aanwijzingen voor vuurbewerking, als in de activiteiten die er werden uitgevoerd. De oudste vindplaatsen (de zogenaamde VLL- en VLB-sites[^270], daterend in de Saale) kenmerken zich respectievelijk door de aanwezigheid van een verzorgde klingentechnologie samen met de aanwezigheid van kleine werktuigen, en een levalloistechnologie. De jacht- en slachtvindplaatsen daterend uit de vroege midden-Weichsel kenmerken zich dan weer door een levalloistechnologie en *oversized* heraangescherpte quina-werktuigen[^271]. De neanderthalers beschikten met andere woorden over een heel divers repertoire aan reductiemethodes, die afhankelijk van de context en aard van het materiaal werd toegepast^289^.

In de Maasregio zijn eveneens oppervlaktevindplaatsen gekend, waarvan we omwille van zijn omvang,

's Gravenvoeren -- Snauwenberg vermelden. Het gaat om een oppervlaktecollectie met een 1000-tal

stukken en een heel diverse samenstelling. Er zijn o.m. Levallois- en discoïdekernen ingezameld. Binnen de werktuigen valt het relatieve hoge aantal bifaciale werktuigen op, waaronder zogenaamde *Keilmesser* en bifaciale werktuigen[^272].

Voor de noordelijke Kempen vermelden we het onderzoek te Oosthoven -- Heieinde waar zowel lithisch materiaal aan het oppervlak is aangetroffen als geassocieerd met grindhoudende zandige sedimenten die tijdens een koude fase (laat glaciaal maximum?) afgezet werden door rivierwerking. In de daaropvolgende fase werden de fijne sedimenten weggeblazen waardoor het grind, inclusief de vuurstenen artefacten, achterbleven. Het lithisch ensemble van de diverse campagnes vertoont een combinatie aan mousteriaan en micoquieaan aspecten en kenmerkt zich door de aanwezigheid van kleine discoïdale, klingen- en een beperkt aantal levalloiskernen naast voornamelijk schrabbers en kleine bifaciale werktuigen met ongeretoucheerde basis[^273]. Een aantal oppervlaktevondsten in de ruimere omgeving van De Liereman[^274] tonen aan dat het gebied niet alleen voor het finaalpaleolithicum en mesolithicum van belang is, maar ook voor de oudere periodes.

De oostelijke uitloper van de Vlaamse vallei is eveneens gekend omwille van haar hoog potentieel voor middenpaleolithische vindplaatsen[^275]. Zemst -- Bos van Aa bevindt zich in de Zennevallei. Er werden tijdens zandontginningswerken in twee groeves artefacten aangetroffen. Fluviatiele afzettingen zijn er afgedekt door eolisch materiaal. Er werden zowel faunaresten als lithisch materiaal aangetroffen, waarvan het merendeel uit het opgespoten sediment werd ingezameld. Vier artefacten werden in hun stratigrafische positie ontdekt. Op basis van diverse elementen (fauna, stratigrafie en ESR) wordt een datering in een koude fase van de vroege Weichsel voorgesteld[^276]. Rotselaar -- Toren ter Heide is een gestratifieerde vindplaats, maar het materiaal werd ingezameld door amateur-archeologen in weinig gunstige omstandigheden waardoor de associatie met de stratigrafische eenheden niet kon vastgesteld worden. Er werden zowel lithische vondsten (gerold en vers) als faunaresten aangetroffen. Oorspronkelijk werd het ensemble toegewezen aan het mousteriaan met acheuleaan traditie omwille van het voorkomen van vuistbijlen[^277]. Nieuw onderzoek op basis van boringen in de onmiddellijke nabijheid van de groeve lijkt te wijzen enerzijds op de aanwezigheid van een herwerkt ensemble, geassocieerd met een grindterras. Mogelijk komt ook het botmateriaal hier vandaan. Het vers materiaal is anderzijds mogelijk geassocieerd met een ouder, beter bewaard niveau dat gelinkt wordt aan de overgan van het Eem naar de laatste ijstijd[^278]. Vooralsnog blijft het bij sterke aanwijzingen maar nog geen direct bewijs. Het hernieuwd onderzoek bracht eveneens Micoquiaan invloeden in het lithisch ensemble onder de aandacht[^279]. Een derde belangrijke vindplaats bevindt zich te Schulensbroek, waar bij ontginningsactiviteiten een beperkt ensemble werd ingezameld, evenals faunaresten. Ook deze vindplaats wordt momenteel opnieuw geëvalueerd[^280].

Andere vindplaatsen binnen de Vlaamse vallei zijn slechts gekend aan de hand van oudere vondstmeldingen en werden minder uitgebreid onderzocht. Ze duiden er echter op dat het potentieel zich niet beperkt tot de oostelijke uitlopers. Zo werd bij de aanleg van de recreatievijver 'Blaarmeersen' te Gent naast ijstijdfauna ook lithische artefacten ingezameld uit het opgespoten sediment. Er werd

o.m. een fragment van een vuistbijl en een reeks levalloisafslagen (evenwel zonder voorbereide hiel) aangetroffen.[^281] Te Uitbergen, in de groeve 'Maes', is de stratigrafische opbouw[^282] en het faunamateriaal[^283] dan weer wel uitgebreid bestudeerd maar is er onduidelijkheid omtrent de

vondstomstandigheden van het ingezameld materiaal. Door J. de Heinzelin werden Solutreaan elementen herkend, maar Crombé en Van der Haegen zien eerder affiniteiten met het middenpaleolithicum[^284].

In de Vlaamse Ardennen zijn een aantal vindplaatsen gekend met zowel levallois componenten als bifaciale werktuigen. Over het algemeen gaat het om geërodeerde contexten waarbij het materiaal niet meer *in situ* bewaard is, zoals te Ronse-Hoogerlucht[^285], Ruien -- Pontweg[^286], Muziekberg^305^ en Ronse-Pontweg[^287]. Een omvangrijk ensemble werd ingezameld op de top van de Kluisberg (op het grondgebied van de gemeentes Orroir, Amougies en Ruien). Ook hier betreft het materiaal dat grotendeels verplaatst lijkt. Echter omtrent de mogelijke stratigrafische context is er nog onduidelijkheid. Op basis van typo-technologische kenmerken wordt het ondergebracht onder het 'typisch Mousteriaan van Levallois-faciës'[^288]. Ook op de Kemmelberg te Heuvelland is een omvangrijke vindplaats gekend, waar zowel levallois als discoïdekernen en een heel diverse set aan werktuigen (schrabbers, spitsen, messen, getande en gekerfde werktuigen) zijn aangetroffen. Maar er werden ook enkele bifaces en bifaciaal bewerkte afslagen ingezameld[^289].

De vindplaats Vollezele -- Congoberg maakt deel uit van een aantal getuigenheuvels langs de Dender.

Het materiaal werd er aangetroffen in colluviale sedimenten die wellicht dateren uit het Weichsel. Binnen het ensemble komen zowel levallois als klingendebitage voor. Op basis van typotechnologische kenmerken werd het als Mousteriaan met Levallois-faciës gedetermineerd[^290].

Te Aalter zijn twee omvangrijke oppervlaktecollecties ingezameld. Het gaat om de vindplaats AalterNieuwendam en Aalter-Hageland. Beide vindplaatsen bevinden zich ter hoogte van tertiaire opduikingen. Ze kenmerken zich o.m. door het 'opportunistisch' gebruik van de minder kwalitatieve, lokale grondstoffen. Dit bestaat vooral uit kwartair basisgrind, maar eveneens uit fossiel hout. Het gebruik van fossiel hout als grondstof is buiten Europa gekend, o.m. bij de Noord-Amerikaanse Clovis- en Folsomculturen[^291], maar is binnen een Europese context uitzonderlijk. Op basis van typotechnologische kenmerken werd het materiaal als 'Charentiaan met enige Micoquiaan-invloeden' omschreven[^292].

Sites lijken zich dus in de nabijheid van waterlopen te bevinden (bijv. Kesselt en Veldwezelt), maar eveneens vaak geassocieerd te zijn met uitgesproken reliëfelementen zoals getuigenheuvels en plateaus (Kluisbergen, Vollezele, ...). Daarnaast heeft ook de aanwezigheid van grondstoffen wellicht een bepalende rol gespeeld (bijv. te Veldwezelt -- Hezerwater en Oosthoven -- Heieinde). Echter, omwille van de beperkte kennis omtrent het pleistocene paleolandschap en het gefragmenteerd beeld op de locatie van vindplaatsen, is een verdere analyse vooralsnog niet mogelijk.

### Het laatpaleolithicum 

#### Gravettiaan 

Vindplaatsen uit het gravettiaan zijn nauwelijks gekend in Vlaanderen. In de collectie van het Schulensbroek komt mogelijk 1 vuurstenen werktuig voor (zie verder). Uit de collectie is eveneens een gegraveerd botfragment van een mammoet gekend. Vijf radiokoolstofdateringen werden door het

Koninklijk Instituut voor het Kunstpatrimonium uitgevoerd op verschillende steekproeven van het geëxtraheerde collageen. De gemiddelde waarde (ongecalibreerd) komt uit op 27417 [+]{.underline} 225 BP[^293].

#### Magdaleniaan 

Het aantal vindplaatsen dat met de nodige zekerheid aan het magdaleniaan kan worden toegewezen is beperkt. Voorlopig is Kanne de enige onderzochte magdaleniaansite in Vlaanderen[^294]. De site werd ontdekt tijdens de uitbreiding van het Albert-kanaal in de vallei van de Jeker. Verschillende zones zijn onderzocht, die op hun beurt verschillende lithische vondstconcentraties opleverden. De locatiekeuze moet hier waarschijnlijk worden verklaard door de aanwezigheid van kwalitatief goede vuursteen. Indicaties van echt residentieel verblijf in de regio ontbreken tot dusver.

Op basis van morfo-technologische kenmerken worden naast Kanne nog enkele andere vindplaatsen als mogelijk magdaleniaan bestempeld. Dit geldt voor enkele vondsten van de Kluisberg, onder meer een schrabber met een hiel 'en éperon'[^295]. Vermeersch en Symens maken melding van een magdaleniaan klingenkern met een dikke patina en verschillende vorstvlakken afkomstig van de oppervlaktevindplaats Oedelem-*Maandagse*[^296]*.*

### Het finaalpaleolithicum 

#### Federmesser 

In Vlaanderen zijn verschillende tientallen federmessersites gekend[^297]. Deze liggen gespreid over de verschillende archeoregio's en wijzen in tegenstelling tot het magdaleniaan op een min of meer permanente aanwezigheid. Ze bevinden zich systematisch op een drogere verhevenheid (in de zandstreken meestal (dek)zandruggen) nabij open water, en in het bijzonder de droge oevers van de ondiepe laatglaciale meren (bijv. Moervaartdepressie[^298]), duinpannen of brongebieden ( bijv. LommelMaatheide). Binnen de overstromingsvlakte van de rivieren, en met name de Schelde, zijn de aanwijzingen voor nederzettingen beperkt[^299]. Een mogelijke verklaring is dat het landschap binnen de overtromingsvlaktes in het Scheldebekken te dynamisch was en minder aantrekkelijk voor bewoning. Ook op het einde van de Allerød, wanneer door een abrupte klimaatschommeling drinkwater schaars wordt, lijkt te bewoning zich niet te gaan verplaatsen naar de oevers van de rivieren [^300]. Maar, mogelijk heeft de stand van het onderzoek een belangrijke hand in huidig verspreidingspatroon. Enkele ontdekkingen in stedelijke context (Aalst-Oud Hospitaal[^301], Antwerpen-Burchtzone[^302], LierSionsplein[^303]), maar ook uit het onderzoek naar Rekem[^304] lijken er op te wijzen dat de oevers van de rivieren vermoedelijk wel werden bezocht, dat is ook het patroon in de buurlanden. Mogelijk bevinden zich eveneens vindplaatsen dieper in de fossiele beddingen, omdat in het laatglaciaal die breed uitgeschuurde beddingen een mini-vallei vormden met een *underfit* rivier aan de basis. In dat geval zitten die sites dieper, op de randen of in de vroegere beddingen van de breed meanderende rivieren, en zijn ze moeilijker te detecteren^324^.

Het merendeel van de gekende federmesservindplaatsen zijn oppervlaktevindplaatsen die enkel door middel van veldkartering zijn onderzocht[^305]. Het aantal opgegraven sites is beperkt. De belangrijkste zijn:

Meer -- Meirberg[^306]: De duinrug Meirberg in Meer herbergt een hoge densiteit aan zowel finaalpaleolithische als mesolithische vindplaatsen, bewaard in een podzolbodem. Het grootste deel van de duinrug werd gewaardeerd door intensief booronderzoek, en verschillende vondstlocaties werden opgegraven. De vindplaats leverde zowel finaalpaleolithische als mesolithische clusters op. Meer II leverde veruit het grootste federmesser-ensemble op en vormde in de jaren 1970 het onderwerp van een toen baanbrekende combinatie van functioneel onderzoek (microwear analyse) en ruimtelijke analyse[^307]. De site werd beschermd als monument[^308].

Harelbeke -- Gavermeersen[^309]: De vindplaats is onderzocht in het kader van zandwinningswerken. Op de zuidelijke flank van een zandrug zijn zo'n 2.200 artefacten ingezameld. Een belangrijk deel hiervan was reeds in de bouwvoor opgenomen. Duidelijke verspreidingspatronen zijn niet herkend.

Klein-Sinaai -- Boudelo[^310]: Tussen de resten van een middeleeuwse abdij werden de resten van minimaal vijf vuursteenconcentraties ontdekt (ca. 1.750 artefacten). Bijzonder aan de vindplaats is dat de resten zijn ingezameld in een zandig pakket zo'n 10 cm boven een laag die gekenmerkt wordt door de aanwezigheid van houtskoolskoolpartikels, mogelijk een Usselo-bodem. Recent onderzoek in de onmiddellijke nabijheid leverde het bewijs dat eolische activiteiten zich ook voorgedaan hebben tijdens het warmere Allerod, en dus niet enkel tijdens de koudere stadialen (Oude en Jonge Dryas)[^311].

Rekem[^312]: De vindplaats werd ontdekt midden jaren '80 van de vorige eeuw bij onderzoek van een Romeinse nederzetting. Over de loop van de daaropvolgende jaren zijn een vijftiental clusters opgegraven (ca. 24.000 artefacten) die in de jaren '90 aan een grondige typo-technologisch en ruimtelijke analyse zijn onderworpen. Ook microwear kreeg tijdens dit onderzoek de nodige aandacht.

Weelde -- Eindegoorheide[^313]: In het kader van ruilverkavelingswerken zijn in Weelde-Eindegoorheide verschillende finaalpaleolithische en mesolithische vuursteenconcentraties onderzocht. Verschillende van deze vindplaatsen waren reeds langere tijd gekend door oppervlaktekartering en bevonden zich grotendeels in de bouwvoor. Beperkt refittingonderzoek heeft duidelijk gemaakt dat enkele van deze concentraties mogelijk gelijktijdig zijn. Naast vuursteen is op een aantal vindplaatsen ook verbrand bot ingezameld. Enkele van deze fragmenten zijn gedateerd (ca. 11.900-10.800 BP), echter de associatie met de vuursteenclusters staat niet vast.

Verrebroek -- Dok 2[^314]: Bij controle van dijkwerken in het kader van de havenuitbreiding op de linker Scheldeoever werd in een humeuze horizont een kleine vuursteenconcentratie aangetroffen met daarin de debitageresten van een drietal kleine vuursteenknollen. Kenmerkende werktuigtypes ontbreken, maar de technologische analyse wijst in de richting van de federmessergroepen. Paleoecologisch- (pollen, macroresten, houtskool) en radiokoolstofonderzoek wees uit dat de bodem en de vindplaats op de overgang van de Oude Dryas naar de Allerød dient te worden gedateerd.

Doel -- Deurganckdok zone B^335^: Bij onderzoek van een dekzandrug in het tracé van het Deurganckdok werden naast Swifterbantresten ook de resten van federmessergroepen aangetroffen. Minimaal 600

artefacten, behorende tot drie vondstconcentraties, kunnen aan deze occupatie worden toegewezen, waaronder een dertigtal werktuigen (spitsen, schrabbers, stekers, geretoucheerde klingen, ...). Wegens de tijdsdruk en de uitgesproken verticale spreiding van de artefacten was het niet mogelijk het ensemble integraal te bergen.

Lommel -- Maatheide[^315]: Dit is één van de vroegst gekende paleolithische sites in Vlaanderen; HamalNandrin zamelde er reeds in de jaren 1930 uitgebreid vondsten in. In het kader van grootschalige zandwinning werd het terrein begin jaren 2000 aan een grondige prospectie onderworpen. Daarbij werden tientallen vuursteenconcentraties ontdekt. Verschillende van deze vondstconcentraties kunnen met een Federmesseraanwezigheid in verband worden gebracht (o.m. LB25). De voornaamste occupatie uit deze periode bevond zich op een laatglaciale duin ten noorden van de Blokwaters en de Rietreienloop. Deze deflateerde echter tijdens de Jonge Dryas waardoor de vondsten minder goed bewaard bleven in de holocene podzolbodem. In de periferie van deze duin werd echter één vondstconcentratie uitstekend bewaard in directe associatie met een Usselobodem aangetroffen. Twee anderen waren ook geassocieerd met de Usselbodem maar minder goed bewaard. Het onderzoek van deze laatglaciale bodem en de evolutie van het paleolandschap kreeg de nodige aandacht.

Lommel -- Kristalpark[^316]: Deze vindplaats maakt deel uit van het sitecomplex Lommel -- Molse Nete en bevindt zich (grotendeels) op de noordelijke valleirand van de Molse Nete. Verschillende boorcampagnes, proefputtenonderzoeken en opgravingen leverden naast mesolithische en neolithische sites, op diverse locaties finaalpaleolithische artefacten op al dan niet in associatie met een Usselobodem. In 2010 werden 3 kleine clusters opgegraven die op basis van het lithisch materiaal en de associatie met de Usselobodem tot de federmessergroepen worden gerekend.

Tongeren -- Plinius[^317]: Naast resten uit het middenpaleolithicum, neolithicum en ijzertijd zijn tijdens het onderzoek ook vijf finaalpaleolithische vondstclusters aangetroffen, elk met een oppervlakte tussen ca. 25 en 50 m². Enkele hiervan zijn in het bezit van een haard. Op basis van het voorkomen van enkele steilgeretoucheerde spitsen worden de ensembles tot de federmessergroepen gerekend. Of de verschillende vondstclusters gelijktijdig zijn is vooralsnog niet duidelijk. Eén locatie (cluster 4) wordt op basis van een datering op verbrand bot op de overgang van Allerød naar Jonge Dryas gedateerd.

Arendonk -- Korhaan[^318]: Tijdens een waarderend archeologisch booronderzoek in het Landschap Liereman werden ter hoogte van Korhaan een aantal vondsten op relatief grote diepte aangetroffen. Aangezien de aanwezigheid van een Usselobodem in het gebied gekend was, is een eventuele associatie met deze bodem verder onderzocht en bevestigd door middel enkele testputten. Het materiaal bleek zich daarbij vooral in het topgedeelte van de Usselobodem te bevinden, waardoor de vindplaats op de overgang van de Allerød naar de Jonge Dryas wordt gedateerd. Op basis van enkele fragmenten van steilgeretoucheerde klingen wordt het ensemble aan de federmessergroepen toegeschreven. Ook op andere locaties in het landschap de Liereman is vondstmateriaal in associatie met de Usselobodem aanwezig. Op een akker hierlangs werden bij herhaaldelijke oppervlakteprospectie meer dan 50.000 vondsten ingezameld, waaronder een groot aantal federmesserspitsen. De volledige duinrug werd in 2013 beschermd[^319].

Beveren -- LPW^341^: Tussen de resten van een mesolithisch sitecomplex werden een aantal finaalpaleolithische spitsen aangetroffen evenals één kleine vondstconcentratie. De vondsten wijzen op een federmesseraanwezigheid aan de voet van de dekzandrug Maldegem-Stekene.

Ten slotte zijn er nog een aantal stadscontexten waar in de natuurlijke bodem, onder puinpakketten of middeleeuwse resten, Federmessermateriaal is ingezameld. De belangrijkste zijn:

Aalst -- Oud Hospitaal[^320]: vlak naast de Dender werd bij onderzoek begin jaren '80 van vorige eeuw in een glauconietrijke zandige laag onder de middeleeuwse resten een kleine vondstconcentratie aangetroffen bestaande uit 35 artefacten waaronder drie schrabbers, drie stekers op afknotting, twee stekerafslagen, een bek, een boor en twee kernen. Hoewel de kenmerkende federmesserspitsen ontbreken, wijst het grondstofgebruik (een kwaliteitsvolle, fijnkorrelig zwarte vuursteen die enige gelijkenissen vertoont met de zgn. Obourg-vuursteen), de manier van vuursteen bewerken en het hoge aandeel aan stekers op afknotting in de richting van de federmessergroepen.

Antwerpen -- Burchtzone[^321]: op de rechteroever, op korte afstand van de Schelde werden bij het onderzoek van de burchtzone in 2008-2009 61 lithische artefacten ingezameld waaronder mogelijk ook enkele artefacten van de federmessergroepen. Verschillende artefacten zijn vervaardigd uit een kwaliteitsvolle zwarte vuursteen. Naast een mogelijk fragment van een federmesserspits gaat het onder meer om een kern, een kernrandkling en een schrabber/steker.

Lier -- Sionsplein[^322]: een artefactenvindplaats uit de steentijd werd er aangetroffen onder een puinpakket. Landschappelijk bevindt de site zich op de linkeroever van de Nete. Het gaat om een gemengde context waarvan een aantal spitsen en (micro)klingen met afgestompte boord, een typische steker en schuin afgeknotte kling wijzen op een finaalpaleolithische component. De vier spitsen kunnen als ferdermesserspitsen worden beschouwd. Ook het gebruik van de Obourg-achtige vuursteen sluit hier mogelijk bij aan.

Hoewel de omvang van de opgegraven ensembles sterk varieert, lijkt het er op dat ze vaak deel uitmaken van grotere sitecomplexen die waarschijnlijk meermaals opgezocht zijn (o.m. Klein-Sinaai, Doel). Refitonderzoek op enkele van deze vindplaatsen maakt duidelijk dat vaak meerdere clusters met elkaar in verband staan (o.m. Meer, Rekem, Weelde)[^323]. Wel dient opgemerkt te worden dat dit beeld mogelijk het resultaat is van de prospectiestrategie die de laatste decennia wordt toegepast. Deze bestaat namelijk grotendeels uit archeologisch booronderzoek. Recent onderzoek naar steentijd prospectietechnieken in Vlaanderen en Nederland heeft echter aangetoond dat de klassieke boorstrategie weinig geschikt is voor het treffen van lage densiteit vindplaatsen[^324]. Kleinere vindplaatsen worden met andere woorden vaak gemist en zijn wellicht ondervertegenwoordigd. Organisch materiaal is op deze sites niet of nauwelijks bewaard en beperkt zich grotendeels tot verbrand bot (Weelde, Verrebroek). Ook evidente haarden zijn slechts uitzonderlijk geregistreerd (voorlopig enkel te Tongeren -- Plinius), maar in plaatsen waar voldoende lithisch materiaal aanwezig is, zijn wel structurele patronen te herkennen. Samen geven ze een indruk van georganiseerde kampplaatsen.

#### Ahrensburgiaan 

In vergelijking met de federmesseroccupatie, is het Ahrensburgiaan opnieuw veel minder goed gekend in Vlaanderen. Zonhoven -- Molenheide is de enige vindplaats die hieraan met zekerheid kan worden toegewezen. Van enkele andere vindplaatsen wordt aangenomen dat ze mogelijk ook tot het Ahrensburgiaan behoren of mogelijk gelijktijdig hiermee zijn (late Federmesser/Belloisiaan/ Laboriaan). De belangrijkste vindplaatsen zijn:

Zonhoven -- Molenheide[^325]: De vindplaats is gelegen op een voormalig militair domein en werd ontdekt bij controle van een door soldaten gegraven kuil. In de loop van de jaren '90 van vorige eeuw werden alles bij elkaar zo'n vijf vuursteenconcentraties opgegraven (ca. 11.600 artefacten). Op basis van refittingonderzoek blijkt dat ze wellicht gelijktijdig in gebruik waren. Het werktuigspectrum bestaat uit schrabbers, stekers, afgeknotte werktuigen, steilgeretoucheerde microklingen en groot aantal spitsen waaronder enkele kenmerkende steelspitsen.

Gent -- Tweekerkenstraat[^326]: Nabij de top van de Blandijnberg, hoog boven de Schelde, zijn tussen de graven van een voormalige parochiekerk de resten van twee kleine vuursteenconcentraties ontdekt. Bij gebrek aan kenmerkende artefacten is een chrono-culturele toewijzing van de vindplaats niet eenduidig. De aanwezigheid van protogeometrische microlieten, de technologische kenmerken evenals het grondstofgebruik (chalcedoon) wijzen op enige affiniteiten met het ahrensburgiaan. De aanwezigheid van een zgn. *soil-cap* op een belangrijk deel van het materiaal wijst op periglaciale omstandigheden en plaatst de vindplaats in de Jonge Dryas.

Ruien -- Rosalinde[^327]: De vindplaats werd bij toeval ontdekt tijdens het onderzoek van een nederzetting uit de metaaltijden en Romeinse tijd en ligt op de rechteroever van de Schelde aan de voet van de Kluisberg. Een haardstructuur en zo'n 3.500 vuursteenartefacten werden ingezameld. Ook op deze vindplaats ontbreken kenmerkende werktuigtypes, maar de microlithische elementen, de technologische kenmerken en het grondstofgebruik (chalcedoon) sluiten wederom eerder aan bij vindplaatsen uit het Ahrensburgiaan of (Epi)Laboriaan/Belloissiaan. Een radiokoolstof aan houtskool uit de haardstructuur plaatst de vindplaats op de overgang van de Allerød naar de Jonge Dryas.

Oudenaarde -- Markt[^328]: Het gaat hier om een klein lithisch ensemble dat is aangetroffen tussen de middeleeuwse resten in de top van een rivierduin. Kenmerkende werktuigen ontbreken, maar de beperkte technologische inzichten wijzen in de richting van het finaalpaleolithicum. Vergelijkbaar met Gent-Tweekerkenstraat is ook hier de aanwezigheid van een *soil-cap* op een deel van het materiaal vastgesteld. Op basis van een reeks OSL-dateringen kan een datering in de Jonge Dryas vooropgesteld worden.

Wichelen -- Bergenmeersen[^329]: Bij het onderzoek van een middeleeuws en postmiddeleeuws kasteelsite kwam een grote hoeveelheid vuursteen (ca. 7000 vondsten) aan het licht. De oudste vondsten dateren in het middenpaleolithicum, de jongste in de tweede helft van het neolithicum. De meerderheid van de vondsten hoort echter thuis in het mesolithicum en finaalpaleolithicum, waaronder enkele vondstclusters. Een culturele toewijzing was op basis van het beperkte werktuigspectrum niet mogelijk, maar een datering op het eind van het finaalpaleolithicum is op basis van de technologische kenmerken het meest waarschijnlijk.

### Balans van het archeologische materiaal 

Opnieuw beperken we ons tot een algemene schets van de bekende archeologische ensembles in de verschillende periodes.

### Vroeg- en middenpaleolithicum 

Het vroegpaleolithicum is slecht gekend in Vlaanderen. Enkel te Kesselt-op de Schans bevindt zich een gedateerde vindplaats (daterend voor 390.000 BP)^352^. Verder zijn er een aantal oppervlaktevondsten gedateerd in deze periode omwille van de aanwezigheid van een zogenaamde 'Acheuleaan-vuistbijl'.

Alhoewel het Acheuleaan zich inderdaad vaak kenmerkt door de aanwezigheid van vuistbijlen, komt deze technologie ook in de daaropvolgende periode voor en is een onderscheid op basis van typologische kenmerken niet altijd te maken. Sommige oppervlaktecollecties worden ook op basis van de aanwezigheid van eenvoudige afslagen (vaak sterk gepatineerd) tot deze periode gerekend. Dat is bijvoorbeeld het geval voor het zogenaamde 'Hagelands clactoniaan'^353^. Maar ook hier geldt dat een dergelijke toewijzing onvoldoende onderbouwd is.

Het middenpaleolithicum kenmerkt zich door de aanwezigheid van een aantal gestandaardiseerde en gecontroleerde productiemethodes gericht op afslagen, spitsen en klingen. Het gaat om de levallois^354^, discoïde[^330] en diverse vormen van klingentechnologie (waaronder volumetrische klingentechnologieën[^331]).[^332] Dit betekent evenwel niet dat de bifaciale technologie verloren gaat. Terwijl deze technologie voor het vroege middenpaleolithicum aan belang inboet, blijkt ze tijdens het Weichsel weer sterk aanwezig (zie verder).[^333] Opvallend is dat doorheen het middenpaleolithicum neanderthalers beschikten over een divers repertoire aan technologieën voor het vervaardigen van werktuigen. Onderzoek op goed bewaarde vindplaatsen zoals te Kesselt[^334], Veldwezelt[^335] maar ook in Wallonië (o.m. Remicourt-En Bia Flo[^336]) hebben aangetoond dat deze verschillende reductiemethodes gelijktijdig werden toegepast en o.m. gelinkt zijn aan een gediversifieerd grondstofgebruik en mobiliteitsstrategieën.

De oudste middenpaleolithische vindplaatsen in Vlaanderen (en bij uitbreiding België) zijn schaars en bevinden zich op de overgang van het vroeg- naar middenpaleolithicum. Zo werden in de goed bewaarde vroeg middenpaleolithische ensembles van Kesselt-Op de Schans (overgang MIS 9 naar MIS 8) zowel levallois, discoïde, als eenvoudig voorbereide reductiestrategieën naast elkaar toegepast.[^337] Een reeds volledig ontwikkelde levalloistechnologie werd eveneens geattesteerd op de Henegouwse site Mesvin IV (MIS 8).[^338] Beide vindplaatsen getuigen reeds van een volledig ontwikkelde middenpaleolithische technologie. Binnen de noordwest-europese context nemen ze daarom een uitzonderlijke positie in[^339].

Vanaf MIS 8 zal de levalloismethode de meeste middenpaleolithische ensembles gaan domineren in

Noordwest-Europa en zien we eveneens voor het eerst een volumetrische klingentechnologie

353. Vermeersch 1973.

354. De levalloistechnologie is een specfieke reductiemethode waarbij door middel van een verzorgde voorbereiding (van het slag- en productievlak) de nodige convexiteit en scherpe hoeken gecreëerd worden voor de productie van regelmatige afslagen, spitsen of klingen. Deze technologie kent een ruime chronologische en geografische verspreiding (Afrika, Eurasië en Australië), maar wordt in onze contreien voornamelijk met neandaerthalers geassocieerd. De technologie wordt beschouwd als marker voor de aanvang van het middenpaleolithicum (tegen het eind van MIS 9, alhoewel er indicaties zijn dat de technologie al vroeger aanwezig was in Europa).

verschijnen op een aantal sites, o.m. in Noord-Frankrijk (bijv. Saint-Valéry-sur-Somme)[^340], maar eveneens in Vlaanderen te Veldwezelt-Hezerwater^366^.

Zoals hierboven aangehaald, zal de bifaciale technologie nog slechts sporadisch voorkomen in de vroege ensembles, om vanaf het laatste glaciaal terug sterk aan belang te winnen. Binnen Europa worden momenteel twee grote groepen onderscheiden waarbinnen bifaciale werktuigen courant voorkomen: het gaat om het 'Mousteriaan met Acheuleaan traditie' (MTA) enerzijds en de zogenaamde 'Keilmessergruppen' (KMG, vroeger ook als 'micoquiaan' aangeduid) anderzijds. Binnen deze groepen komen nog heel wat varianten voor, vaak gelieerd aan hun regionale verspreiding.[^341] Vlaanderen neemt hierin een interessante positie in aangezien de regio zich op de grens van beide invloedsferen bevindt. Op basis van de aanwezigheid van 'klassieke', symmetrische vuistbijltypes met (sub)driehoekige of hartvormige vorm worden o.m. de vindplaatsen te Rotselaar -- Toren ter Heide[^342] en Gent-Port Arthur[^343] tot het MTA gerekend. Het KMG kenmerkt zich dan weer door diverse types van asymmetrische bifaces en bifaciaal bewerkte werktuigen. Voor Vlaanderen neemt de vindplaats Oosthoven-Heieinde[^344] hierin een belangrijke positie in. Binnen het ensemble van 107 artefacten komen 18 bifaciale werktuigen voor. De kernen tonen aan dat er verschillende debitagemethodes werden toegepast (levallois, discoïde en klingen). De bifaciale werktuigen worden vooral gedomineerd door zogenaamde *Keilmesser* en kenmerken zich door kleine dimensies (\< 6 cm), een fijn, continu geretoucheerde spits en onbewerkte basis.[^345] 'Micoquieaan' of KMG elementen zijn eveneens herkend te Vollezele -- Congoberg (De twee vuistbijlen en bifaciale spitsen met bladvormige morfologie)[^346], Veldwezelt-Hezerwater (VBLB, gedateerd in MIS 5, met o.m. een bifaciale bladvormige spits en een

*Kostienki* mes)[^347], te Aalter (o.m. bladvormige spitsen)[^348], te 's Gravenvoeren-Snauwenberg, op de Kemmelberg[^349] en te Ronse Pont-West[^350]. Een relatief recente herevaluatie van bifaciale werktuigen lijkt er op te wijzen dat deze werktuigtypes in België vooral voorkomen op vindplaatsen daterend in het late middenpaleolithicum en dan specifiek het vroege Weichseliaan (MIS 5d t.e.m. MIS 5a) en de middenpleniglaciale fase van het Weichseliaan (MIS 3). Omdat de Belgische vindplaatsen met bifaciale componenten zich onderscheiden van de zuidelijke MTA vindplaatsen en noordoostelijke KMG sites stelt Ruebens voor om deze ensembles als een aparte groep te beschouwen en ze aan te duiden als MBT ofwel *Mousterian with bifacial tools*[^351]*.*

Verder kenmerken de vindplaatsen uit het Weichseliaan zich vaak door een belangrijke aanwezigheid van levalloisproducten, naast discoïde en minder georganiseerde reductiestrategieën, in combinatie met diverse werktuigen.

Te Vollezele -- Congoberg zijn levallois- en discoïdekernen aangetroffen en worden de werktuigen gedomineerd door schrabbers. Daarnaast komen ook mousteriaanspitsen, '*limaces'*, gekerfde en getande werktuigen evenals messen met natuurlijke rug voor. De twee vuistbijlen en bifaciale spitsen met bladvormige morfologie wijzen op een micoquiaan/KMG invloed^378^.

Te Heuvelland -- Kemmelberg komen zowel Levallois- als discoïdekernen voor. Het werktuigenensemble bestaat uit schrabbers, spitsen, messen, getande en gekerfde werktuigen. Maar ook enkele bifaces en bifaciaal bewerkte afslagen zijn er geattesteerd[^352].

De vindplaatsen te Aalter -- Hageland en Nieuwendam kenmerken zich vooral door het hoge aantal onregelmatige kernen. Mogelijk is dit gerelateerd aan de lokale grondstof met beperkte kwaliteit en afmetingen. In mindere mate komen ook discoïde- en levalloiselementen voor. De werktuigen bestaan er uit schrabbers, messen met natuurlijke rug, *limaces* en bifaciale werktuigen (met KMG affiniteiten, zie boven)[^353].

Ook te 's Gravenvoeren -- Snauwenberg werd een divers ensemble, dat o.m. Levallois- en discoïdekernen bevat, ingezameld. Binnen de werktuigen valt het relatieve hoge aantal bifaciale werktuigen op, waaronder zogenaamde *Keilmesser* en bifaciale werktuigen[^354].

Dit betreffen uiteraard minder goed bewaarde vindplaatsen, die ongetwijfeld ook meerdere occupaties vertegenwoordigen. De diversiteit binnen deze collecties is dus wellicht eerder het resultaat van het gemengde karakter ervan. Wederom bieden de vindplaatsen te Kesselt en Veldwezelt een beter inzicht.

Te Kesselt -- steengroeve Nelissen is in het archeologisch niveau A5 een lithisch ensemble aangetroffen in associatie met resten van paard (*Equus caballus*) en wolharige neushoorn (*Coelodonta antiquitatis*). Op basis van chronostratigrafie wordt dit niveau in het pleniglaciaal gedateerd. Binnen het lithisch ensemble komt o.m. een bifaciaal bewerkte schrabber (met rug) voor[^355].

Te Kesselt -- Albertkanaal is een collectie van lithisch materiaal (700 stuks) geassocieerd met fauna. Het lithisch materiaal wijst op een dominantie van de levalloismethode, maar lijkt er sprake dat er in de laatste fases van de exploitatie van de kern werd overgeschakeld naar een discoïdemethode. Binnen het ensemble komt een gevarieerde groep van werktuigen voor (o.m. bifaciale werktuigen)[^356].

Veldwezelt -- Hezerwater is één van de weinige vindplaatsen uit het Weichsel waar een volumetrische klingendebitage is aangetroffen (niveau VBLB, gedateerd in MIS 5). Daarnaast komt ook levalloisdebitage voor. Het werktuigenensemble omvat o.m. een bifaciale bladvormige spits en een *Kostienki* mes[^357].

Middenpaleolithische klingendebitage lijkt in Vlaanderen minder vaak gerapporteerd. Dat is mogelijk het resultaat van een selectieve inzameling. Het inzicht dat volumetrische klingendebitage reeds in het middenpaleolithicum een rol speelde, is in onze contreien immers pas gegroeid vanaf de jaren '90 van vorige eeuw. Het is dus goed mogelijk dat bij het inzamelen of determineren ervan een middenpaleolithische datering niet als mogelijk geacht werd.

De meeste vindplaatsen kenmerken zich door het gebruik van diverse soorten vuursteen, zowel lokaal gewonnen als aangevoerd, voor het vervaardigen van artefacten. Ook andere grondstoffen worden echter aangewend. Zo zijn kernen en een vuistbijl vervaardigd in Wommersomkwartsiet te Wommersom -- Steenberg aangetroffen en is een vuistbijl vervaardigd in tertiaire zandsteen aangetroffen te Kuringen-Larestraat[^358]. Te Rotselaar -- Toren ter Heide blijkt een grote diversiteit aan grondstof gebruikt te zijn, bestaande uit Wommersomkwartsiet, micahoudend kwartsiet, verschillende soorten vuursteen en ftaniet[^359]. Opvallend is het mogelijk gebruik van fossiel palmhout te Aalter, wat een uitzonderlijk gegeven is binnen Europa en daardoor ook moeilijk te plaasten. Te

Aalter wordt, naast het lokale vuursteen van beperkte kwaliteit, ook lokale zandsteen aangewend.[^360] Te Zemst-Bos van Aa werd een klopper in bitumen aangetroffen waarvan de petrografische analyse een herkomst uit zuidelijk Engeland aangeeft[^361]. Dit hoeft niet te verwonderen aangezien transport over lange afstanden al vaker werd vastgesteld voor het middenpaleolithicum en de Noordzee bovendien gedurende de koude fases van het laatste glaciaal een open vlakte was.

Uitgezonderd faunaresten met snij- of slachtsporen (o.m. te Veldwezelt-Hezerwater[^362] en te ZemstBos van Aa[^363]) zijn uit het middenpaleolithicum nauwelijks vindplaatsen gekend met bewerkt bot. In de groeve van Oekene - Rennevoordestraat straat is een mogelijk gepolijst botfragment aangetroffen, maar verder onderzoek is noodzakelijk om het intentionele karakter ervan te verifiëren[^364].

### Laatpaleolithicum 

#### Gravettiaan 

In de collectie van het Schulensbroek komt mogelijk één vuurstenen werktuig voor uit deze periode.

Oorspronkelijk werd het op basis van typologische kenmerken als een Aurignac-kling gedetermineerd. Op basis van de specifieke voorbereiding van de hiel, die enige overeenkomsten vertoont met de zgn. *en éperon*-voorbereiding, wordt het artefact nu iets jonger gedateerd. De *en éperon*-voorbereiding verschijnt namelijk pas ten vroegste tijdens het gravettiaan[^365], maar deze manier van voorbereiden is vooral kenmerkend voor het laatmagdaleniaan en gerelateerde groepen[^366]. Het gaat hier dus louter om een toewijzing op basis van typo-technologische kenmerken. Te Schulensbroek werd eveneens een gegraveerd fragment van een lang been van mammoet aangetroffen. In eerste instantie werd het tot het middenpaleolithische ensemble toegewezen en als mogelijk muziekinstrument geïnterpreteerd[^367]. Een heranalyse, aan de hand van 14C dateringen en 3D-scan, lijkt het antropogene karakter ervan te bevestigen maar plaatst het stuk qua ouderdom in het gravettiaan (gemiddelde waarde (ongecalibreerd) komt uit op 27417 [+]{.underline} 225 BP)[^368].

#### Magdaleniaan 

Het magdaleniaan in Noordwest-Europa en het Maas-Rijngebied in het bijzonder (met o.m. Kanne) onderscheidt zich van de andere laat- of finaalpaleolithische culturen door het (grotendeels) ontbreken van spitsen. De artefacten die met de jacht in verband kunnen worden gebracht zijn kleine klingen voorzien van één of twee steil geretoucheerde boorden. Deze steilgeretoucheerde klingen werden vermoedelijk lateraal op assegaaien (werpsperen) gemonteerd en in combinatie met een speerdrijver gebruikt. Hun aandeel in het werktuigspectrum schommelt sterk van vindplaats tot vindplaats. In Kanne bezitten ze slechts een beperkt aandeel.

Andere kenmerkende werktuigtypes zijn bekken, bekstekers en Lacanstekers. Bekken en bekstekers worden gekenmerkt door een relatief lange, stevige punt, aangebracht door tweezijdige retouches. Wanneer ventraal één of meerdere kleine stekerafslagen zichtbaar zijn spreekt men van een beksteker. Lacanstekers zijn te herkennen aan de hand van een zeer schuine afknotting die is aangebracht na het afhaken van de stekerafslag. Hierdoor is het proximale deel van het negatief van de stekerafslag niet meer aanwezig.

Ten slotte zijn er nog de grote eindschrabbers op kling. De voorkeur voor relatief grote klingen is trouwens kenmerkend voor alle werktuigtypes. Exemplaren met een lengte boven 10cm zijn daarbij geen uitzondering. Alleen de steilgeretoucheerde klingen wijken af van dit patroon. Voor de productie van dit werktuigtype zijn relatief kleine klingen geselecteerd, afkomstig uit de eindfase van de reductiesequentie of van kernen die specifiek voor dit doel zijn bestemd.

Voor het vervaardigen van de werktuigen viel de keuze op kwaliteitsvolle vuursteen. Het merendeel van de magdaleniaanvindplaatsen in het Maas-Rijn-gebied ligt dan ook in de onmiddellijke nabijheid van vuursteenontsluitingen. Dit kan terrasvuursteen zijn, maar ook eluviale vuursteen zoals Rullen-, Orsbach-, Simpelveld-, Valkenburg- of Rijckholt-vuursteen. Daarnaast worden af en toe ook exotische grondstoffen aangetroffen zoals zoetwaterkwartsiet uit het Duitse midden-Rijngebied.

Het magdaleniaan staat bekend voor zijn verzorgde klingtechnologie. Er werd dan ook veel tijd en energie geïnvesteerd in de voorbereiding en het onderhoud van de kernen. Kernrandklingen en kernvernieuwingsproducten komen dan ook regelmatig voor. Bijzonder is de individuele voorbereiding van de hiel bij een belangrijk deel van de klingen uit de *plein débitage*, daarbij wordt de slagvlakrand in de richting van het slagvlak zo bijgewerkt dat de plaats waar moet worden geslagen om de kling af te haken als het ware uit het slagvlak omhoog komt, de zgn. *en éperon*-voorbereiding. Op basis van het voorkomen van deze specifieke voorbereiding wordt een mogelijke datering in het magdaleniaan gesuggereerd voor onder meer een deel van het materiaal op de Kluisberg[^369].

### Finaalpaleolithicum 

#### Federmesser 

In vergelijking met het magdaleniaan is materiaal van de federmessergroepen goed vertegenwoordigd in Vlaanderen. Verschillende tientallen vindplaatsen zijn gekend, het merendeel oppervlaktevindplaatsen. Kenmerkend zijn de steilgeretoucheerde spitsen die sporadisch reeds opduiken op het eind van het magdaleniaan. Deze spitsen zijn vervaardigd op kleine klingen en voorzien van steile retouches en minimaal één spitse punt. Al naargelang de positie van het spitse uiteinde, de retouches en de morfologie van het artefact worden verschillende spitstypes onderscheiden. Het meest voorkomende type is de federmesserspits, een spits voorzien van een asymmetrisch convex geretoucheerde boord. Maar daarnaast komen in federmesservindplaatsen ook nog aziliaan-, gravette-, creswell-, cheddar, kremser, malaurie-, blanchère-, p*enknife*-, kerf- en steelspitsen[^370].

De federmessergroepen vormen geen homogeen blok maar kennen een zekere evolutie doorheen hun bestaansperiode. Op basis van de huidige inzichten kunnen ruwweg een drietal fases worden onderscheiden. De oudste federmesservindplaatsen verschijnen reeds op het eind van de Bølling of de Oude Dryas en vormen als het ware de verderzetting van het magdaleniaan (zuiden) en/of hamburgiaan (noorden). Ze worden in hun werktuigspectrum gekenmerkt door het voorkomen van aziliaan-, kerf- en creswellspitsen. Technologisch sluiten ze nog nauw aan bij hun voorgangers. Hun klingentechnologie wordt nog steeds gekenmerkt door een grondige voorbereiding en onderhoud van de kernen. Ook de hiel wordt nog regelmatig individueel voorbereid door middel van facettering, maar van een voorbereiding '*en éperon*' is nog zelden sprake. Op andere vindplaatsen geeft men eerder de voorkeur aan het grondig afschuren en retoucheren van de slagvlakrand. Tijdens de *plein débitage* wordt ook niet langer gebruik gemaakt van een geweihamer zoals tijdens het magdaleniaan, men prefereert vanaf nu een zachte stenen hamer.

Tijdens de middenfase verdwijnen de aziliaan-, kerf- en creswellspitsen en nemen de federmesserspitsen het over. Daarnaast is onder de spitstypes een grotere typologische variabiliteit zichtbaar dan in voorgaande fase. Op technologisch vlak is er sprake van een verdere vereenvoudiging. De kernvoorbereiding wordt meer en meer afgesteld op de grootte en de morfologie van de knol. Een individuele voorbereiding van de hiel komt nog zelden voor. Ook de kwaliteit van de ingezamelde vuursteen vertoont grote verschillen. Wanneer deze klassieke federmessergroepen verschijnen is onduidelijk, vermoedelijk pas tegen het midden van de Allerød.

De jonge federmesserfase valt samen met de laatste fase van het Allerød-interstadiaal en het begin van de Jonge Dryas. In het werktuigspectrum verschijnen naast federmesserspitsen nu ook malaurie- en blanchèrespitsen, ook de eerste microlieten duiken op. De productie van malauriespitsen gebeurt op klingen, voor de vervaardiging van blanchèrespitsen dragen microklingen de voorkeur weg. Beide spitstypes vertonen een grote mate van standaardisering wat zich vertaalt in het gebruik van een kwalitatief hoogstaande grondstof en een grondige kernvoorbereiding waarbij het regulariseren van de tafel een grote rol speelt. Net zoals in het magdaleniaan is er een tweedeling in de productie: grote knollen voor klingen; kleine knollen en (vorst)afslagen voor microklingen, hoewel in een aantal gevallen de reductiesequentie na het afhaken van de klingen gewoon worden verdergezet.

Het aantal vindplaatsen dat aan de vroege federmessergroepen kan worden toegewezen is vooralsnog beperkt. Er is de vindplaats van Verrebroek-Dok 2 die op basis van een 14C-datering op de overgang van de Oude Dryas naar de Allerød wordt gedateerd en gekenmerkt wordt door een verzorgde klingendebitage (hoog aandeel aan individueel voorbereide hielen, frequent onderhoud van de tafel)[^371]. Ook Doel-Deurganckdok sluit technologisch aan bij deze vroege fase. Daarnaast zijn op deze vindplaats ook enkele aziliaanspitsen aangetroffen. Andere mogelijke voorbeelden zijn MaldegemTegelhoogte, Oedelem-Maandagse, St-Michiels-Steenbrugge, Zolder-Terlamen, Meer IV en enkele clusters in Weelde[^372]. Vindplaatsen waar malaurie- of blanchèrespitsen zijn aangetroffen zijn respectievelijk Merendree[^373], Oedelem-Maandagse, Klein-Sinaai-Baudelo[^374], en MaldegemPrinsenveld[^375] en Evergem-Nest[^376].

Voor het finaalpaleolithicum zijn er maar drie sites met botmateriaal: Weelde-Eindegoorheide, Verrebroek *Dok 2*[^377] en Tongeren-Plinius^405^. Het gaat steeds om zwaar verbrande en dus deels ge(her)mineraliseerde resten die door de hoge fragmentatiegraad bijzonder moeilijk te determineren zijn. Voorlopig konden hierin enkel fragmenten van wild varken herkend worden. Verder is er, op de hars na die in Rekem op een spits was bewaard, voorlopig geen organisch archeologisch materiaal gekend.

#### Ahrensburgiaan 

Het meest kenmerkende artefact voor het ahrensburgiaan is de steelspits. Op basis van de vorm, grootte en bewerkingswijze kunnen verschillende types worden onderscheiden. De exemplaren die in ahrensburgcontexten voorkomen zijn over het algemeen vrij klein, met een lengte onder de 50mm. Daarnaast komen heel vaak microlithische spitsen voor, met name van het type schuine afknotting. Deze zijn in het algemeen in het bezit van een relatief stompe en vaak zwak concave afknotting. Deze spitsen worden nog niet vervaardigd door middel van het kerfhalveringsprocedé. Andere microliettypes zijn driehoeken en zgn. zonhovenspitsen. Deze laatste bezitten naast een afknotting ook een geretoucheerde basis. Eindschrabbers, stekers en boren lijken minder talrijk te worden, in de

plaats komen afgeknotte klingen. De grens met de oudste mesolithische ensembles is in een aantal gevallen zeer vaag.

De lithische technologie laat een zekere tweedeling zien tussen een eerder opportunistische aanpak op grondstoffen van mindere kwaliteit en een zeer verzorgde klingendebitage op kwaliteitsvolle vuursteen. Bepaalde klingen uit deze sequenties halen lengtes tot 150mm wat aangeeft dat voor de bewerking grote vuursteenknollen zijn geselecteerd.

Naast een aantal losse steelspitsen is alleen in Zonhoven-Molenheide[^378] voor het ahrensburgiaan kenmerkend materiaal aangetroffen. Een belangrijke waarneming op deze vindplaats is het lage aantal ahrensburgsteelspitsen. Bovendien blijven deze spitsen beperkt tot één sector. In de overige sectoren zijn enkel microlithische spitsen aanwezig. Refitting toont echter aan dat de verschillende sectoren vermoedelijk gelijktijdig zijn. Door veel onderzoekers wordt het ontbreken van steelspitsen gezien als een recente ontwikkeling binnen het ahrenburgiaan, vermoedelijk op de overgang naar het Preboreaal

(zgn. Epi-Ahrensburgiaan). Het onderzoek in Zonhoven lijkt er echter op te wijzen dat beide assemblagetypes naast elkaar in gebruik waren.

[^261]: Vandendriessche *et al.* 2016; Verbrugge *et al.* 2021.
[^262]: Vroomans *et al.* 2006; Van Baelen *et al.* 2007; 2008; Van Baelen 2014; 2017.
[^263]: Van Baelen & Ryssaert 2011.
[^264]: Lauwers 1985a; Lauwers & Meijs 1985.
[^265]: Vroomans *et al.* 2006; Van Baelen *et al.* 2007; 2008; Van Baelen 2014; 2017.
[^266]: Bringmans *et al.* 2003; Bringmans 2006.
[^267]: Van Baelen 2014; 2016.
[^268]: Van Baelen & Ryssaert 2011.
[^269]: Bringmans 2006.
[^270]: De "Lower Sites" (VLL- en VLB-sites) zijn gelegen in een klein bronamfitheater, waar de erosieve kracht van het Hezerwater silex blootlegde. Het onderzoek toonde aan dat Neanderthalers meermaals op deze plekken zijn langsgekomen om vuursteen te exploiteren, waardoor de sites als openlucht vuursteenextractieplaatsen geïnterpreteerd worden.
[^271]: Werktuig vervaardigd op een massieve of dikke afslag en met uitgesproken meervoudige, getrapte retouches. ^289^ Bringmans 2006.
[^272]: Kolen *et al.* 1999.
[^273]: Reubens 2006; Ruebens *et al.* 2014; Van Peer & Verbeek 1994.
[^274]: Allemeersch *et al.* 2013.
[^275]: Van Peer 1986; 2001.
[^276]: Bogemans & Caspar 1984; Van Peer & Smith 1990; Germonpré 1999.
[^277]: Van Peer 1982b.
[^278]: Van Peer 1982b; Van Peer *et al.* 2017.
[^279]: Van Peer *et al.* 2017.
[^280]: Van Peer 2020.
[^281]: Crombé & Van der Haegen, 111-113.
[^282]: Heyse & De Moor 1979.
[^283]: Germonpré & Ervynck 1988.
[^284]: Crombé & Van der Haegen 1994b, 126-129.
[^285]: Crombé & Van der Haegen 1994b.
[^286]: Vandendriessche *et al.* 2016. ^305^ Crombé 1989.
[^287]: Vandendriessche *et al.* 2016.
[^288]: Crombé 1994.
[^289]: Crombé & Van der Haegen 1994b.
[^290]: Vynckier *et al.* 1988.
[^291]: Buchanan *et al.* 2019.
[^292]: Crombé & Van der Haegen 1994b.
[^293]: Van Peer 2020.
[^294]: Vermeersch *et al.* 1985.
[^295]: Vandendriessche *et al.* 2016.
[^296]: Vermeersch & Symens 1988, 247, fig. 7.1.
[^297]: Crombé 1998a; Crombé 2020; Crombé & Verbruggen 2002; De Bie & Van Gils 2006; Vanderbeken 1998.
[^298]: Van Vlaenderen *et al.* 2006.
[^299]: Crombé 2020.
[^300]: Crombé 2020.
[^301]: Vanmoerkerke 1983.
[^302]: Van Gils & Bellens 2013.
[^303]: Crombé *et al.* 2017.
[^304]: Lauwers 1985a, 557-559. ^324^ Meylemans *et al.* 2013.
[^305]: Van Vlaenderen *et al.* 2006.
[^306]: De Bie 1999; Nijs 1990; Van Noten 1978.
[^307]: Cahen & Keeley 1980.
[^308]: Federmessersite Meirberg https://id.erfgoed.net/erfgoedobjecten/302887 (Geraadpleegd op 27 mei 2021).
[^309]: Vermeersch 1976.
[^310]: Vanmoerkerke & De Belie 1984.
[^311]: Crombé *et al.* 2020.
[^312]: De Bie & Caspar 2000.
[^313]: Verbeek & Vermeersch 1993; Verbeek 1994; 1997; 1998 & 1999.
[^314]: Crombé *et al.* 1999; Crombé 2005; Perdaen & Ryssaert 2002; Perdaen *et al.* 2004. ^335^ Crombé *et al.* 2000; Perdaen *et al.* 2004.
[^315]: De Bie *et al.* 2003; De Bie & Van Gils 2004; 2005; 2006a; Geerts *et al.* 2006 & 2008.
[^316]: Vanmontfort *et al.* 2010; Van Gils & De Bie 2003; Van Neste *et al.* 2009.
[^317]: Dijkstra *et al.* 2007; Brink 2007.
[^318]: Meirsman *et al.* 2008; Van Gils *et al.* 2009; Vanmontfort *et al.* 2010.
[^319]: https://inventaris.onroerenderfgoed.be/aanduidingsobjecten/4427. ^341^ Perdaen *et al.* in voorbereiding.
[^320]: Vanmoerkerke 1983; Sergant 2004, 31, 53-55.
[^321]: Van Gils & Bellens 2013.
[^322]: Crombé *et al.* 2017.
[^323]: De Bie *et al.* 2002, 139-164.
[^324]: Verhagen *et al.* 2011, 32-33.
[^325]: Vermeersch 2015.
[^326]: Ryssaert *et al.* 2003.
[^327]: Crombé *et al.* 2014; Jacquier *et al.* 2018, Vandendriessche 2021.
[^328]: Crombé *et al.* 2019.
[^329]: Meylemans *et al.* 2021; Perdaen *et al.* 2013. ^352^ Meijs *et al.* 2012; Van Baelen 2014.
[^330]: Discoïdetechnologie is verwant aan de levalloismethode, maar kenmerkt zich vaak door een minder doorgedreven voorbereiding en afwezigheid van een duidelijke hiërarchie tussen slag- en productievlak. De productie van afslagen en spitsen wordt vooral gecreëerd door een continue proces van opeenvolgende afhakingen waarbij de negatieven telkens de voorbereiding vormen voor de volgende afhaking.
[^331]: Volumetrische of prismatische klingentechnologie heeft betrekking op de productie van voorbereide lange, smalle afhakingen waarbij een groot deel of het volledige volume van de kern wordt geëxploiteerd. Deze technologie werd lang beschouwd als kenmerk voor 'modern gedrag', maar het is ondertussen aanvaard dat klingentechnologie reeds voorkomt tijdens het middenpaleolithicum.
[^332]: Ruebens & Di Modica 2011; Van Baelen & Ryssaert 2011; Herisson *et al.* 2016.
[^333]: Ruebens & Di Modica 2011.
[^334]: Van Baelen 2014.
[^335]: Bringmans 2006.
[^336]: Bosquet *et al.* 2011.
[^337]: Van Baelen 2014.
[^338]: Cahen *et al.* 1983; Ryssaert 2006.
[^339]: Herisson *et al.* 2016; Scott & Ashton 2010; Moncel *et al.* 2020.
[^340]: Herisson *et al.* 2016. ^366^ Bringmans 2006.
[^341]: Ruebens *et al.* 2014.
[^342]: Van Peer *et al.* 2017.
[^343]: Crombé & Van der Haegen 1994b.
[^344]: Ruebens & Van Peer 2011.
[^345]: Ruebens 2006.
[^346]: Vynckier *et al.* 1988; Ruebens & Di Modica 2011.
[^347]: Bringmans 2006.
[^348]: Crombé & Van der Haegen 1994d.
[^349]: Crombé & Van der Haegen 1994b.
[^350]: Vandendriessche *et al.* 2016.
[^351]: Ruebens & Di Modica 2011; Ruebens *et al.* 2014. ^378^ Vynckier *et al.* 1988; Ruebens & Di Modica 2011.
[^352]: Crombé & Van der Haegen 1994b.
[^353]: Crombé & Van der Haegen 1994d.
[^354]: Kolen *et al.* 1999.
[^355]: Groenendijk *et al.* 2001.
[^356]: Ruebens & Di Modica 2011.
[^357]: Bringmans 2006.
[^358]: Ruebens & Di Modica 2011, 246.
[^359]: Van Peer 1982, Van Peer *et al.* 2017.
[^360]: Crombé & Van der Haegen 1994d.
[^361]: Ryssaert 2004.
[^362]: Bringmans 2006.
[^363]: Germonpré *et al.* 1993.
[^364]: Hameeuw *et al.* 2012.
[^365]: Van Peer 2020.
[^366]: Barton 1990.
[^367]: Huyghe 1990.
[^368]: Van Peer 2020.
[^369]: Vandendriessche *et al.* 2016.
[^370]: Voor een definitie van de verschillende types zie o.m. Amkreutz *et al.* 2016.
[^371]: Crombé *et al.* 1999; Perdaen & Ryssaert 2002; Perdaen *et al.* 2004.
[^372]: Zie o.m. De Bie & Vermeersch 1998; Perdaen 2004; Vanderbeken 1998.
[^373]: Crombé 1996, 483.
[^374]: Vanmoerkerke & De Belie 1984.
[^375]: Crombé 1996, 397.
[^376]: Devriendt *et al.* 2011.
[^377]: Van Neer *et al.* 2005, 279-297. ^405^ Laarman 2007, 88.
[^378]: Vermeersch 2015.
