# KENNIS EN HIATEN 

## ALGEMEEN 

Hoewel het paleolithicum in het Vlaamse gewest bij het begin van de 20^ste^ eeuw voor het eerst aan het licht komt, komt er in Vlaanderen zélf pas in de tweede helft van die eeuw ernstig paleolithisch onderzoek op gang. Het duurt dan nog tot het laatste kwart van die eeuw eer dit enig volume aanneemt, zowel in terreinonderzoek als in publicaties. Fundamenteel toegenomen is het onderzoeksvolume sindsdien in feite niet meer, maar er zijn wel accentverschuivingen, zowel op het terrein (grootschaliger en de laatste jaren ook gericht op prospectie en waarderingsonderzoek), als in publicaties (meer volume in het Engels bijvoorbeeld).

Met betrekking tot het **vroegpaleolithicum** is de kennis in Vlaanderen bijzonder beperkt. Nochtans kan -- op basis van vondsten in de omringende regio's -- verwacht worden dat ook hier bewoning plaatsvond. Algemeen wordt aangenomen dat noordwest-Europa al tussen 800.000 en 500.000 jaar geleden bewoning kende. Vondsten uit de Noordzee lijken zelfs een ouderdom tot 1 miljoen jaar geleden te suggereren. In Vlaanderen is enkel te Kesselt-Op de Schans lithisch materiaal gedateerd voor 390.000 jaar BP. De overige vondsten in Vlaanderen zijn louter op basis van hun morfologische kenmerken in deze periode geplaatst. Ondertussen weten we dat de typotechnologische variatie in het paleolithicum een grote complexiteit vertoont en vaak niet eenduidig met een specifieke periode in verband kan gebracht worden. Dateringen die puur op basis van de vorm of het type gebeuren zijn dan ook weinig betrouwbaar.

Deze vaststelling geldt in principe ook voor het **middenpaleolithicum**. In de vorige eeuw werden vindplaatsen voornamelijk op basis van het werktuigenspectrum (schrabbers, messen met natuurlijke rug, diverse spitsen, getande en gekerfde werktuigen, bifaciale werktuigen) ingedeeld in culturele faciës. Daarnaast was er eveneens een sterke focus op de rol van de levalloismethode. Dankzij een beter begrip van het chronostratigrafisch kader en onder impuls van het technologisch onderzoek, weten we ondertussen dat zogenaamde typische mousteriaankenmerken al aan het begin van de Saale voorkomen. Hiermee doelen we o.m. op het voorkomen van een volledig ontwikkelde levalloistechnologie, al dan niet in combinatie met een gevarieerd werktuigenspectrum, zoals dit ook op de site te Kesselt-Op de Schans is vastgesteld. Daarnaast is er doorheen de jaren ook meer aandacht gekomen voor andere reductiemethodes, naast de levalloistechnologie, die alleen of in wisselende verhoudingen binnen ensembles kunnen voorkomen. Naast eenvoudige productiesystemen waarbij weinig energie wordt gestoken in de voorbereiding en onderhoud van de kern, kenmerken middenpaleolithische ensembles zich eveneens door het voorkomen van discoïdemethodes en verschillende klingenmethodes. Wat deze laatste betreft, is het onderscheid met laat- of finaalpaleolithische strategieën niet altijd evident. Het ziet er naar uit dat zaken als grondstofvoorziening (locatie van de bronnen, kwaliteit), mobiliteit en functionele aspecten een invloed hadden. Een glimp van deze strategieën werd opgevangen op de sites te Veldwezelt en Kesselt. Maar momenteel zijn nog onvoldoende vindplaatsen gekend om een goed begrip te hebben over het gedrag van neanderthalers doorheen de tijd en in wisselende klimatologische omstandigheden.

Het is opvallend dat de dataset aan goed bewaarde middenpaleolithische vindplaatsen beperkt blijft. Nochtans heeft het onderzoek de afgelopen 40 jaar aangetoond dat er binnen Vlaanderen een belangrijk potentieel aanwezig is. Vooral binnen de Vlaamse vallei en zijn uitlopers, maar eveneens in de zandleem- en leemstreek van midden-België mag men verwachten dat er afgedekte vindplaatsen voorkomen. Het kan gaan van kleine, kortstondig bewoonde clusters met een goede in situ bewaring, tot ensembles die weliswaar verplaatst zijn maar door hun afdekking en/of associatie met fauna eveneens perspectieven bieden op kenniswinst.

Deze problematiek gaat eigenlijk ook op voor het **jong- of laatpaleolithicum**, waarvan slechts in beperkt mate indicaties zijn in Vlaanderen. Uitgezonderd te Kanne, gaat het voornamelijk om oppervlaktevindplaatsen waarvan de toewijzing niet altijd onderbouwd is. Laatpaleolithische culturen kenmerken zich door de productie van verzorgde klingen, vaak op vuursteen van goede kwaliteit. Er wordt over het algemeen verondersteld dat omwille van het koude klimaat bewoning in Vlaanderen in deze periode nauwelijks voorkwam en daarom sites zo goed als ontbreken. Terwijl dit zeker voor de koudste fases plausibel is, valt niettemin op dat in de omringende regio's (Noord-Frankrijk, Wallonië en Nederland) wel een sterkere laatpaleolithische compontent aanwezig is. We dienen er dus rekening mee te houden dat de beperkte aanwezigheid van laatpaleolithische vindplaatsen eerder het resultaat is van het ontbreken van gericht onderzoek tot op heden.

Uit het **finaalpaleolithicum** zijn in Vlaanderen voornamelijk vindplaatsen gekend die tot de federmessergroep wordt gerekend en in mindere mate tot het ahrensburgiaan. Het creswelliaan lijkt afwezig. Aan de hand van enkele goed bewaarde vindplaatsen en een doorgedreven analyse (o.m. refitting en technologische attributenanalyse) zijn voor deze periode belangrijke inzichten verkregen met betrekking tot de lithische technologie. Deze kenmerkt zich door een productie gericht op kleinere klingen en afslagen en de productie van kenmerkende spitstypes en 'algemene' werktuigen. Ook voor deze periode zijn de meeste vindplaatsen echter gekend aan de hand van oppervlaktecollecties, waarbij de toewijzing dus louter op basis van typotechnologische kenmerken en het gebruik van specifieke grondstoftypes gebeurt. Daarnaast baseert een belangrijk deel van onze kennis over deze periode zich op basis van vindplaatsen of complexen die louter aan de hand van boor- of testputtenonderzoek in kaart gebracht zijn en waarvan een deel op basis van de associatie met een afgedekte paleobodem (vaak een Usselobodem) is gedateerd. De voorbije decennia is er een rijk potentieel geopenbaard van sites met een enorme omvang als Weelde, Meer en Lommel, van de rijke paleo-ecologische contexten in Lommel en Arendonk, van sites in de Leemstreek (Tongeren-Plinius), van gestratifieerde contexten in alluviale gebieden (Verrebroek, Doel) tot het recent aangeboorde potentieel van afgedekte vindplaatsen in zuidoost-vlaanderen (Ruien-Rosalinde, Oudenaarde-Markt). Ondanks deze verschoven aandacht voor de landschappelijke context, blijft het verbinden van de archeologie met de omgeving vaak problematisch. Sites waar directe links voorkomen zijn nog steeds eerder zeldzaam.

Aansluitend hierbij lijkt een voor de hand liggende opdracht een grondige evaluatie door specialisten van de duizenden sites die op dit moment in de Centrale Archeologische Inventaris zijn geregistreerd als 'steentijd' zonder verdere specificatie. Dit zal vooral moeten duidelijk maken of het hier een gebrek aan expertise van de vinder of inventariseerder betrof dan wel reële afwezigheid van diagnostisch materiaal. Daarnaast verdient het aanbeveling ook de wel toegewezen vindplaatsen aan een kritische *screening* te onderwerpen. In het bijzonder de sites die nu als vroeg- of als laatpaleolithicum geregistreerd staan, verdienen een kritische evaluatie. Om dit naar behoren te kunnen vervullen zal ook werk moeten worden gemaakt van een registratie van de collecties zelf. Tot slot dient ook de volledigheid van deze inventaris te worden nagegaan. Naast verdere controle van de literatuur kan een actieve 'prospectie' naar ongeregistreerde paleolithische collecties in Vlaanderen hierbij nuttig zijn.

## DE IMPACT VAN MALTA-ONDERZOEK OP DE PALEOLITHISCHE DATASET 

De actualisatie van de onderzoeksbalans, waarvan de huidige tekst het resultaat is, biedt de opportuniteit om de impact na te gaan van Malta-onderzoek op zowel de onderzoekspraktijk als de kenniswinst die vergaard werd. Hoewel het Verdrag van Malta reeds in 1992 werd vastgelegd, duurde het tot 2002 vooraleer België het verdrag tekende en ging het in de praktijk in Vlaanderen in 2011 van kracht. De implementatie van Malta ging in Vlaanderen gepaard met een liberalisering en de opkomst van commerciële bedrijven, dit terwijl voor die tijd het onderzoek voornamelijk in handen was van overheden, academische instellingen en amateurverenigingen. Sinds het nieuwe erfgoeddecreet, dat in 2016 van kracht ging, zet deze liberalisering zich nog door. De eerste versie van de onderzoeksbalans (2008) schetste dus de situatie uit het pre-Maltatijdperk en bood een goede basis om na te gaan in welke zin het onderzoek wijzigde.

Wanneer we puur de kwantitatieve data bekijken, zien we dat er heel wat nieuwe vindplaatsen aan het licht gekomen zijn. Wanneer echter kritisch wordt gekeken naar de bronnen en de wijze waarop ze werden onderzocht, blijkt de oogst een stuk minder groot. Met betrekking tot de oudste periodes (vroeg-, midden- en laatpaleolithicum) stellen we vast dat de toename aan Malta-onderzoek slechts heeft geleid tot een beperkte kenniswinst voor deze periodes. Dit in tegenstelling tot bijvoorbeeld de situatie in Noord-Frankrijk. Hier gaat men systematisch door middel van een dicht grid aan profielputten en -- sleuven op zoek naar afgedekte paleolithische niveaus.[^469] Sinds de implementatie van Malta zijn er in Vlaanderen weliswaar nieuwe vindplaatsen aan het licht gekomen. Maar het gaat vaak om één of enkele stukken die als losse vondst tijdens onderzoek naar jongere vindplaatsen aan het licht kwamen en waarvoor geen bijkomende waardering werd uitgevoerd. Door amateurarcheologen werden nog hier en daar prospecties uitgevoerd. Deze vondsten zijn van belang aangezien ze inzicht geven over de geografische verspreiding van vindplaatsen binnen een bepaalde (sub)periode. Ze getuigen bovendien van het rijke potentieel voor het paleolithicum in Vlaanderen, ook in regio's waar in het pré-Malta tijdperk nauwelijks onderzoek was verricht.

Enkel vanuit academische hoek zijn initiatieven genomen voor een meer doorgedreven onderzoek, weliswaar vooral gericht op de evaluatie van reeds gekende vindplaatsen zoals te Schulensbroek, Oosthoven -- Heieinde en Rotselaar - Toren ter Heide. Hiervoor zijn een aantal verklaringen. Ten eerste vereist onderzoek naar middenpaleolithische contexten een specifieke expertise, zowel op vlak van archeologie als geo(morfo)logie, die over het algemeen niet aanwezig is bij de uitvoerders van Maltaarcheologie. Ten tweede leidt de manier waarop Malta geïmplementeerd is in Vlaanderen tot een projectgebonden aanpak waarbij enerzijds de onderzoeksvragen heel lokaal gericht zijn, maar het onderzoek ook de draagkracht van een individueel project niet mag overstijgen. Tot slot ontbreekt een overkoepelende onderzoeksagenda waarbij prioriteiten uitgestippeld worden en daaraan gekoppelde onderzoeksstrategieën zodat stelselmatig kennislacunes opgevuld worden. Eén van die kennislacunes is ongetwijfeld de beperkte kennis die we hebben over de evolutie van het paleolandschap doorheen de tijd. Die paleolandschappelijke kennis is noodzakelijk om doelgericht paleolithische vindplaatsen op te sporen.

In tegenstelling tot de oudere periodes zien we dat de implementatie van Malta voor het finaalpaleolithicum wel heeft geleid tot de ontdekking en opgraving van nieuwe vindplaatsen. De meeste vindplaatsen kwamen eveneens eerder toevallig aan het licht tijdens onderzoek naar jongere periodes, tijdens het proefsleuvenonderzoek of de opgraving. Enkel ter hoogte van Beveren -- LPW was de opgraving van de finaalpaleolithische clusters het resultaat van een doelgerichte prospectie. Ook voor deze periode vermoeden we dat de beperkte expertise op vlak van paleolithische archeologie en het paleolandschap de systematische opsporing van finaalpaleolithische vindplaatsen in de weg staat, met name wanneer ze zich in een afgedekte context bevinden. In dat geval worden ze soms wel als bijvangst bij onderzoek naar recentere periodes aangetroffen. Het valt op dat dit vaak voorkomt bij stedelijk onderzoek (bijv. Lier -- Sionsplein, Oudenaarde -- Markt en Gent-Tweekerkenstraat).

Er is echter nog een ander aspect dat inherent verbonden is aan de Vlaamse Malta-archeologie en tot nu toe niet werd aangestipt, maar zowel impliciet als expliciet valt te traceren in de verschillende rapporten, archeologienota's en nota's. En dat heeft te maken met de keuzes die gemaakt worden in functie van de kostprijs van archeologie. Sinds het invoeren van het 'verstoordersprincipe' is het debat naar wat een aanvaardbare kostprijs is voor het veiligstellen van archeologische waarden steeds actueel geweest. Door de keuze om de archeologische markt te liberaliseren en de projectgebonden aanpak in Vlaanderen wordt dit debat nog aangescherpt. In de huidige praktijk is het immers aan de

erkend archeoloog om telkens een verwachting op te stellen en kosten-batenafweging te maken over welke onderzoeken zinvol zijn. De druk om het steentijdpotentieel te minimaliseren is dan ook groot. In de praktijk zien we dat steentijdtrajecten vaak enkel worden opgestart wanneer een gekende of hoge verwachting geldt. Dit contrasteert fel met archeologisch onderzoek naar jongere periodes. Daar zien we dat een archeologisch traject wordt opgestart wanneer de afwezigheid van sporen niet kan uitgesloten worden.

Die druk vinden we ook terug in de selectie die doorgevoerd wordt bij vlakdekkend onderzoek. Momenteel is het de norm in Vlaanderen dat steentijdvindplaatsen slechts gedeeltelijk (vaak 30 à 40%) worden opgegraven.

De beperkingen van Malta-archeologie hebben ook een impact op de graad aan uitwerking van het materiaal, dat enkel aan een beperkt assessment wordt ontworpen, terwijl er geen mogelijkheden zijn tot financiering van attributen-, refitting-, microwear- of residuenanalyse en gedetailleerd paleolandschappelijk onderzoek. Terwijl net op dat vlak belangrijke kenniswinst valt te halen. Ze laten immers toe om op verschillende niveaus inzicht te krijgen over de materiële cultuur: op het niveau van de site, op het niveau van de cultuur of chronologische fase en globaal met betrekking tot idiosyncratisch gedrag. Dat de projectsubsidies die sinds 2018 jaarlijks worden toegekend hier enigzins kunnen remidiëren, werd aangetoond met de reeds eerder vermelde studie van Tracéolab. Ook zien we een belangrijke rol weggelegd voor de academische sector, bijvoorbeeld wanneer het gaat om onderzoek naar de regionale paleo-ecologische context of dateringsonderzoek, of detailanalyses van het materiaal. Het zijn zaken die, ondanks dat ze essentieel zijn om de sites naar behoren te interpreteren, blijkbaar de mogelijkheden van de huidige Malta-archeologie overstijgen. Helaas kampt het academisch onderzoek ook onder een nijpend tekort aan onderzoeksmiddelen, waardoor veel data uit het Malta-onderzoek niet verder kunnen uitgediept worden.

Terwijl het debat rond wat archeologie aan de maatschappij en een individuele ontwikkelaar of bouwheer mag kosten zeker terecht is, dient hiertegenover toch afgewogen te worden wat we als maatschappij bereid zijn om op te geven. Het probleem voor het paleolithicum in Vlaanderen, is dat we voor deze periode - ondanks het duidelijke potentieel -bijzonder weinig kennis hebben. Scherp gesteld wordt in het kader van Malta-archeologie het minst ingezet op de periode waar we het minst over weten en dus ook de meeste kenniswinst kunnen behalen. Dat is geen nieuwe conclusie. Ook in de vorige versie van de onderzoeksbalans werd een stagnerende 'omzet' opgemerkt en vastgesteld dat de paleolithische archeologie voorlopig niet mee profiteerde van het groeiende preventieve terreinwerk dat plaatsvond als gevolg van de Malta-conventie.

Een positief aspect dat vervat zit in het verdrag van Malta, heeft betrekking tot het streven naar in situ bewaring. In de praktijk gebeurt dit bij een minderheid van dossiers, maar met name voor ontwikkelingen binnen grootschalige gebieden, zoals in het kader van het Sigmaplan of natuurontwikkelingen, wordt op basis van voorafgaandelijke prospecties rekening gehouden met de (potentiële) aanwezigheid van steentijdwaardes. Door het bijstellen van de plannen of werkwijze kan op die manier het archeologisch erfgoed bewaard blijven en de kostprijs van het archeologisch onderzoek beperkt worden.

Een tweede positief effect die we vaststelden, heeft betrekking met de ontsluiting van de data. Naar aanleiding van de wijziging van het decreet in 2016, werd in Vlaanderen de mogelijkheid gecreëerd om alle onderzoeksrapporten (archeologienota's, nota's en eindverslagen) online te consulteren. Tevens zijn deze gekoppeld aan een geoportaal. Op een laagdrempelige en eenvoudige manier kan dus inzage verkregen worden omtrent de onderzoeksresultaten. Ook voor de onderzoeksrapporten uit de preventieve archeologie daterend voor 2016 is een grote inhaalbeweging gerealiseerd door het agentschap Onroerend Erfgoed en zijn deze voor een groot deel beschikbaar via het open archief ofwel OAR(Open Access (digital) Repository). Daar tegenover staat echter dat de doorstroming van de onderzoeksdata naar wetenschappelijke publicaties sterk gedaald is. Wetenschappelijke publicaties blijken vooral door academische onderzoekers geschreven, terwijl uitvoerders die verbonden zijn aan

commerciële instellingen veel minder publiceren. Dit heeft wellicht deels te maken met het feit dat de uitwerking van onderzoeken vaak beperkt blijft tot een basisassessment (zoals we hoger reeds opmerkten). Maar tevens is het inherent aan het feit dat het archeologisch onderzoek momenteel door de individuele bouwheer of 'verstoorder' wordt betaald en dat deze geen baat heeft bij het bekostigen van meer doorgedreven onderzoek of een publicatie. We dienen de vraag te stellen of hier geen verantwoordelijkheid weggelegd is voor de overheid. Dit wordt ten dele ingevuld door de jaarlijkse subsidies voor syntheseonderzoek, maar blijkt evenwel onvoldoende.

Een laatste aspect dat we wensen te belichten, heeft betrekking op de kaart met gebieden waar geen archeologisch erfgoed verwacht wordt, ofwel de zogenaamde GGA-kaart. Deze wordt o.m. opgesteld op basis van reeds uitgevoerd (voor)onderzoek. Indien een vooronderzoek negatief was of een opgraving afgerond, wordt daarbij verondersteld dat er geen archeologische verwachting meer geldt. Zoals we hierboven aankaartten, wordt het paleolithisch potentieel echter vaak niet onderzocht. In die gevallen is de aanduiding met andere woorden niet correct, aangezien de paleolithische verwachting onbekend is.

[^469]: Depaepe & Séara 2010.
