# REFERENTIES 

S.N. *Federmessersite Meirberg* \[online\][. [https://id.erfgoed.net/erfgoedobjecten/302887]{.underline}](https://id.erfgoed.net/erfgoedobjecten/302887) (geraadpleegd op 27 mei 2021).

S.N. *Finaalpaleolithisch en mesolithisch sitecomplex De Liereman* \[online\]. [[https://id.erfgoed.net/erfgoedobjecten/140136]{.underline} (](https://id.erfgoed.net/erfgoedobjecten/140136)geraadpleegd op 26 maart 2021).

S.N. Genk Kattevennen I \[online\]. [[https://id.erfgoed.net/waarnemingen/980453]{.underline}](https://id.erfgoed.net/waarnemingen/980453) (geraadpleegd 11 mei 2021).

S.N. Gilbert Mulliedreef \[online\] [[https://id.erfgoed.net/waarnemingen/980551]{.underline} (](https://id.erfgoed.net/waarnemingen/980551)geraadpleegd op 12 mei 2021).

S.N. Heirweg I \[online\] [[https://id.erfgoed.net/waarnemingen/162320]{.underline}](https://id.erfgoed.net/waarnemingen/162320) (geraadpleegd op 11 mei 2021).

S.N. Kikbeek 4 \[online\] https://id.erfgoed.net/waarnemingen/209008 (Geraadpleegd op 12 mei 2021).

S.N. Opgrimbie 1 \[online\] https://id.erfgoed.net/waarnemingen/50086 (geraadpleegd op 12 mei 2021).

S.N. Ven Onder De Berg \[online\] [[https://id.erfgoed.net/waarnemingen/160764]{.underline} (](https://id.erfgoed.net/waarnemingen/160764)geraadpleegd op 11 mei 2021).

ALLEMEERSCH L., BATS M., CRUZ F. & DE BRANT R. 2013: *NIR Liereman Archeologische studie. Eindrapport - Deel I: doelstellingen, methodiek en resultaten van de inventarisatie en prospectie. 58*, GATE.

AMEELS V. 1993: *Een epipaleolithisch en mesolithisch site op de Mont de la Hutte te Ploegsteert*, onuitgegeven licentiaatsverhandeling, Universiteit Gent.

AMEELS V. & VAN VLAENDEREN L. 1995: Epipaleolithische en Vroeg-Mesolithische sites langsheen de Moervaart (Oost-Vlaanderen), *Notae Praehistoricae* 15, 35-44.

AMKREUTZ L., BROUNEN F., DEEBEN J., MACHIELS R., VAN OORSOUW M.F. & SMIT B. 2016: *Vuursteen verzameld. Over het zoeken en onderzoeken van steentijdvondsten en -vindplaatsen*, NAR 50, Amersfoort.

AMKREUTZ L., VERPOORTE A., WATERS-RIST A., NIEKUS M., VAN HEEKEREN V., VAN DER MERWE A., & JOHANSEN L. 2018: What lies beneath \... Late Glacial human occupation of the submerged North Sea landscape, *Antiquity*, 92(361), 22-37.

ANGELROTH H. 1956: Mise au point sur la question du Périgordien et de l\'Aurignacien, *Bulletin de la Société Royale Belge d\'Anthropologie et de Préhistoire* 67, 26-30.

ANTOINE P., LIMONDIN-LOZOUET N., AUGUSTE P., LOCHT J., GALHEB B., REYSS J., ESCUDE É., CARBONEL P., MERCIER N., BAHAIN J., FALGUERES C. & VOINCHET P. 2006: Le tuf de Caours (Somme, France): mise en évidence d\'une séquence eemienne et d\'un site paléolithique associé, *Quaternair* 17, 281-320.

ARTS N. & DEEBEN J. 1981: Prehistorische jagers en verzamelaars te Vessem: een model, *Bijdrage tot de studie van het Brabants heem deel* 20, Eindhoven.

BARTON N. 1990: The en éperon technique in the British Late upper Palaeolithic, *Lithics* 11, 31-33.

BATS M., BASTIAENS J. & CROMBÉ P. 2006: Prospectie en waardering van alluviale gebieden langs de BovenSchelde, CAI-Project 2003-2004, in: COUSSERIER K., MEYLEMANS E. & IN \'T VEN I. (Red.), *Centrale Archeologische Inventaris (CAI) II. Thematisch inventarisatie- en evaluatieonderzoek*, VIOE-rapporten 2, Brussel, 75-100.

BATS M. & DE REU J. 2006: Evaluerend onderzoek van boringen in de Kalkense Meersen (Oost-Vlaanderen, België)*,* *Notae Praehistoricae* 26, 171-176.

BATS M. 2007: The Flemish Wetlands: an archaeological survey of the valley of the River Scheldt, *Archaeology from the wetlands. Recent perspectives. Proceedings of the 11^th^ WARP conference (Edinburgh 2005)*, 93-100.

BATS, M., DE REU, J., DE SMEDT, P., ANTROP, M., BOURGEOIS, J., COURT-PICON, M., DE MAEYER, P. 2009:

Geoarchaeological research of the large palaeolake of the Moervaart (municipalities of Wachtebeke and Moerbeke-Waas, East Flanders, Belgium): from Late Glacial to Early Holocene, *Notae Praehistoricae* 29, 105-- 112.

BATS M, DE SMEDT P, WERBROUCK I, ZWERTVAEGHER A, COURT-PICON M, DE REU J. 2010: Continued geoarchaeological research at the Moervaart palaeolake area (East Flanders, Belgium): preliminary results, *Notae Praehistoricae*, 30, 55--61.

BEECKMANS L., DE BROUWER N. & VAN LIEFFERINGE N. 2010: Een middenneolithische site bij het \'Hof te Put\' in Vollezele (Galmaarden), *Archeologie 2010: Recent archeologisch onderzoek in Vlaams-Brabant*.

BEUKER J. 2010: *Vuurstenen werktuigen. Technologie op het scherp van de snede*, Leiden.

BINK M. 2007: *Tongeren Plinius-terrein. Archeologisch onderzoek van resten uit het laat paleolithicum, de ijzertijd en de nieuwe tijd*, BAAC-rapport 06.177, s\'Hertogenbosch.

BOGEMANS F. & CASPAR J.P. 1984: Bois de A, Site des Artefacts, *Bulletin van de Belgische Vereniging voor Geologie* 93/3, Brussel, 245-248.

BOGEMANS F., MEYLEMANS E., JACOPS J., PERDAEN Y., STORME A., VERDURMEN I. & DEFORCE K. 2012: The evolution of the sedimentary environment in the lower River Scheldt valley (Belgium) during the last 13,000 a BP, *Geologica Belgica* (1-2), 105-112.

BOHMERS A. 1947: Jong-Paleolithicum en Vroeg-Mesolithicum, in: VAN GELDER H. E., GLAZEMA P., BONTEKOE G. A., HALBERTSMA H. & GLASBERGEN W. (Red.), *Een kwarteeuw Oudheidkundig Bodemonderzoek in Nederland, Gedenkboek A.E. Van Giffen*, Meppel, 129-201.

BOHMERS A. 1956: Statistics and Graphs in the Study of Flint Assemblages. I. Introduction. II. A Preliminary Rapport on the Statistical Analysis of the younger Palaeolithic in Northern Europe, *Palaeohistoria* 5, 1-26.

BORDES F. 1950: Principes d\'une méthode d\'étude des techniques de débitage et de la typologie du Paléolithique ancien et moyen*,* *L\'Anthropologie* 54, 17-34.

BOS J.A.A., DE SMEDT P., DEMIDDELE H., HOEK W.Z., LANGOHR R., MARCELINO V., VAN ASCH N., VAN DAMME D., VAN DER

MEEREN T., VERNIERS J., BOECKX P., BOUDIN M., COURT-PICON M., FINKE P., GELORINI V., GOBERT S., HEIRI O., MARTENS K., MOSTAERT F., SERBRUYNS L., VAN STRYDONCK M. & CROMBE, P. 2017: Multiple oscillations during the Lateglacial as recorded in a multi-proxy, high-resolution record of the Moervaart palaeolake (NW Belgium), *Quaternary Science Reviews* 162, 26-41.

BOS J.A.A., DE SMEDT P., DEMIDDELE H., HOEK W.Z., LANGOHR R., MARCELINO V., VAN ASCH N., VAN DAMME D., VAN DER MEEREN T., VERNIERS J. & CROMBE P. 2018a: Weichselian Lateglacial environmental and vegetation development in the Moervaart palaeolake area (NW Belgium); implications for former human occupation patterns, *Review of Palaeobotany and Palynology* 248, 1-14.

BOS J.A.A., GELORINI V., VAN DER MEEREN T., PELEMAN J., COURT-PICON M., DEMIDDELE H., DE SMEDT P., BOUDIN M.,

VERNIERS J., BOECKX P. & CROMBÉ P. 2018b: The Younger Dryas and Preboreal landscape in the Moervaart area (northwestern Belgium) and the apparent decrease in human occupation, *Vegetation History and Archaeobotany* 27*,* 697--715.

BOSQUET D., HAESAERTS P., DAMBLON F., JARDON GINER P. & RYSSAERT C. 2011 : Legisement paléolithique de Remicourt-En BiaFlo I. In: TOUSSAINT M., DI MODICA K. & PIRSON S. (Red.), *Le Paléolithique moyen en Belgique*.

*Mélanges Marguerite Ulrix-Closset, Bulletin de la Société Belge d'études Géologiques et Ar-chéologiques « Les Chercheurs de la Wallonie » (hors-série, n° 4) et Études et Recher-ches archéologiques de l'Université de Liège* (ERAUL, 128), Luik, 375-384.

BRINGMANS P. 2006: *Multiple Palaeolithic Occupations in a Loess-soil Sequence at Veltwezelt-Hezerwater, Limburg, Belgium*, onuitgegeven doctoraatsverhandeling, Katholieke Universiteit Leuven.

BRINGMANS P., BUBEL S., GROENENDIJK A., MEIJS E., DE WARRIMONT J., GULLENTOPS F. & VERMEERSCH P. M. 2000: The Middle palaeolithic Valley Settlements at Veldwezelt-Hezerwater, Belgian Limburg: Excavation Campagne 2000*,* *Notae Praehistoricae* 20, 7-19.

BRINGMANS P., VERMEERSCH P. M., GULLENTOPS F., GROENENDIJK A., MEIJS E., DE WARRIMONT J.-P. & CORDY J.-M. 2003: Preliminary Excavation Report on the Middle Palaeolithic Valley Settlements at Veldwezelt-Hezerwater (prov. of Limburg)*,* *Archeologie in Vlaanderen* 7, 9-30.

BUBEL S. 2003: Detecting the Effects of Faunaturbation. A Close Look at the Prehistoric Sites of Meeuwen, Meer 6 and Brecht-Moordenaarsven 2*,* *Notae Praehistoricae* 23, 39-44.

BUCHANAN B., ANDREWS B., KILBY J., & EREN M. 2019: Settling into the country: comparison of Clovis and Folsom lithic networks in western North America shows increasing redundancy of toolstone use. *Journal of Anthropological Archaeology* 53, 32-42.

CAHEN D. 1976: Das Zusammensetzen Geschlagener Steinartefakte, *Archäologisches Korrespondenzblatt* 6, 8193.

CAHEN D. 1984: Paléolithique inférieur et moyen en Belgique, in: CAHEN D. & HAESAERTS P. (Red.) *Peuples chasseurs de la Belgique préhistorique dans leur cadre naturel*, Brussel, 133-155.

CAHEN D., HAESAERTS P., SZABO B.J., VAN NEER W. & WANET P. 1983: An early Middle Palaeolithic site at Mesvin IV (Mons, Belgium). Its significance for stratigraphy and palaeontology, *Bulletin de l\'Institut Royal des Sciences Naturelles de Belgique - Bulletin van het Koninklijk Belgisch Instituut voor Natuurwetenschappen* 55, 1-20.

CAHEN D., KARLIN C., KEELEY L. H. & VAN NOTEN F. 1980: Méthodes d\'analyse technique, spatiale en fonctionelle d\'ensembles lithiques*,* *Helinium* 20, 209-259.

CAHEN D. & KEELEY H. 1980: Not less than two, not more than three (Meer)*,* *World Archaeology* 12, 166-180.

CAHEN D., KEELEY H. & VAN NOTEN F. 1979: Stone tools, toolkits and human behaviour in prehistory*,* *Current Anthropology* 20, 661-672.

CAMPBELL J.B. 1977: *The Upper Palaeolithic of Britain. A Study of Man and Nature in the Late Ice Age*, Oxford.

CASPAR J.-P. & DE BIE M. 1996: Preparing for the Hunt in the Late Paleolithic Camp at Rekem, Belgium*,* *Journal of Field Archaeology* 23**.**4, 437-460.

CASPAR J.-P. & DE BIE M. 2000: Le travail de la peau dans un campement des groupes à Federmesser. Analyse spatio-fonctionnelle des grattoirs de Rekem (Belgique), In VALENTIN B., BODU P. & CHRISTENSEN M. (Red.), *L'Europe centrale et septentrionale au Tardiglaciaire,* Mémoires du Musée de Préhistoire d'Ile de France 7, Nemours, APRAIF, 341-355.

CAUWE N., HAUZEUR A. & VAN BERG P.-L. (Red.) 2001: Prehistory in Belgium, *Anthropologica et Praehistorica* 112, Brussel.

CELIS D., DRIESEN P., STEEGMANS J. & VAN DE STAEY I. 2016: *Prospectie met ingreep in de bodem aan het Heilderveld te Dilsen,* Aron-rapport 277.

CHARLES R. 1994: Towards a new chronology for the Lateglacial archaeology of Belgium part II: recent radiocarbon dates from the Oxford AMS system, *Notae Praehistoricae* 13, 31-39.

CNUTS D., TOMASSO S., COPPE J. & ROTS V. 2021: Functioneel onderzoek van Laat-Paleolithische en VroegMesolithische sites in Vlaanderen, *SYNTAR Synthese-onderzoek op archeologisch materiaal uit Vlaanderen* 1, Brussel: Agentschap Onroerend Erfgoed.

CROMBÉ P. 1989: Oude vuursteenvondsten op de Muziekberg te Ronse: Paleo-, Meso- en Neolithicum, *Vobovinfo* 34/35, 1-27.

CROMBÉ P. 1994: Een Midden-Paleolithische site op de Kluisberg (Amougies, Orroir, Ruien), in: CROMBÉ P. & VAN DER HAEGEN G. (Red.), *Het Midden-Paleolithicum in Noordwestelijk België*, Archeologische Inventaris Vlaanderen, Buitengewone Reeks 3, Zingem, 7-42.

CROMBÉ P. 1996: *Epaleolithicum en Vroeg- en Midden-Mesolithicum in zandig Vlaanderen. Bijdrage tot de studie van de typo-chronologie en de nederzettingsstructuur*, onuitgegeven doctoraatsverhandeling, Universiteit Gent.

CROMBÉ P. 1998a: *The Mesolithic in Northwestern Belgium. Recent excavations and surveys*, British Archaeological Reports, International Series 716, Oxford.

CROMBÉ P. 1998b: Noodonderzoek van een uitgestrekte vroeg-mesolithische nederzetting in de Wase

Schekdepolders, gemeente Verrebroek (provincie Oost-Vlaanderen, België), in: DEEBEN J. & DRENTH E. (Red.), *Bijdragen aan het onderzoek naar de Steentijd in Nederland. Verslagen van de \"Steentijddag\" 1*, Rapportage Archeologische Monumentenzorg 68, 1200, 29-40.

CROMBÉ P. (red.) 2005: *The Last Hunter-Gatherer-Fishermen in Sandy Flanders (NW Belgium). The Verrebroek and Doel Excavation Projects. Volume 1: Palaeo-environment, chronology and features*, Archaeological Reports Ghent University 3, Gent.

CROMBÉ P. 2006: The Wetlands of Sandy Flanders (Northwest Belgium): Potentials and prospects for prehistoric research and management, in: RENSINK E. & PEETERS M. (red.), *Proceedings of the international symposium \"Preserving the Early Past. Investigation, Selection and Preservation of Palaeolithic and Mesolithic Sites and Landscapes\" (Amersfoort, 2002)*, Nederlandse Archeologische Rapporten 31, 41-54.

CROMBÉ P. 2018: Abrupt cooling events during the Early Holocene and their potential impact on the environment and human behaviour along the southern North Sea basin (NW Europe). *Journal of Quaternary Science* 33/3, 353--367.

CROMBÉ P. 2019: The impact of environmental changes on the human occupation of the Scheldt basin during the Younger Dryas, *Préhistoire de l'Europe du Nord-Ouest: mobilités, climats et identités culturelles: volume 2: Paléolithique supérieur ancien, Paléolithique final -- Mésolithique*, 407-416.

CROMBÉ P. 2020: The environmental setting for the Lateglacial recolonization of the Scheldt basin (North-west Europe) by the Federmesser Gruppen. *RGZM-TAGUNGEN* 40, 51-66.

CROMBÉ P., BOS J., CRUZ F. & VERHEGGE J. 2020: Repeated Aeolian deflation during the Allerød /GI-&a-c in the coversand lowland of NW Belgium, *Catena* 188.

CROMBÉ P., BOUDIN M. & VAN STRYDONCK M. 2021: Can calcined bones be used to date final palaeolithic and mesolithic open-air sites? A case-study from the Scheldt basin (NW Belgium), *Journal of Archaeological Science* 131*.*

CROMBÉ P., CRUZ F., DE GRAEVE A., DE GRAVE J., DE MAEYER W., HALBRUCKER E., TEETAERT D., VANDENBERGHE D. &

VANDENDRIESSHE H. 2018: Optically stimulated luminescence dating of an aeolian dune, occupied during the Final Palaeolithic an Neolithic, along the Upper Scheldt valley at Oudenaarde "Markt" (prov. of East Flanders, BE), *Notae Praehistoricae* 38, 49-70.

CROMBÉ P., DEEBEN J., & VAN STRYDONCK M. 2014: Hunting in a changing environment: the transition from the Younger Dryas to the (Pre)boreal in Belgium and the southern Netherlands. In MICHEL S., NAUDINOT N., (Red.), *Congrès Préhistoriques de France*, Bordeaux-Lez Eyzies, France, 583--604.

CROMBÉ P., DE SMEDT P., DAVIES N., GELORINI V., ZWERTVAEGHER A., LANGOHR R., VAN DAMME D., DEMIDDELE H., VAN

STRYDONCK M., ANTROP M., BOURGEOIS J., DE MAEYER P., DE REU J., FINKE P., VAN MEIRVENNE M. & VERNIERS J. 2013:

Hunter-gatherer responses to the changing environment of the Moervaart palaeolake (Nw Belgium) during the Late Glacial and Early Holocene, *Quaternary International* 308--309, 162-177, https://doi.org/10.1016/j.quaint.2013.05.035.

CROMBÉ P. & MEGANCK M. 1996: Results of an auger survey research at the Early Mesolithic site of Verrebroek \"Dok\"*,* *Notae Praehistoricae* 16, 101-115.

CROMBÉ P., PERDAEN Y. & SERGANT J. 1999a: The Early Mesolithic site of Verrebroek \"Dok 1\": Preliminary results of the 1999 excavation campaign*,* *Notae Praehistoricae* 19, 71-74.

CROMBÉ P., PERDAEN Y., SERGANT J., LANGOHR R., LOUWAGIE G., VERBRUGGEN C. & DEFORCE K. 1999b: A small FinalPalaeolithic knapping site at Verrebroek \"Dok 2\" (Flanders, Belgium): preliminary results on the litho- and biostratigraphy and the lithic industry*,* *Notae Praehistoricae* 19, 63-68.

CROMBÉ P., PERDAEN Y. & SERGANT J. 2008: La Transition du Mésolithique ancien au Mésolithique moyen/récent dans le nord-ouest de la Belgique: quelques réflexions concernants l\'occupation du territoire, in: FAGNART J.-P., THEVENIN A., DUCROCQ T., SOUFFI B. & COUDRET P. (Red.), *Le debut du Mésolithique en Europe du Nord-Ouest. Actes de la table ronde d\'Amiens (octobre, 2004)*, Mémoires de la Société Préhistorique Française 45, Amiens, 195205.

CROMBÉ P., ROBINSON E., & VAN STRYDONCK M. 2014: Sychronizing a late glacial abrupt cooling event with paleoenvironmental and population changes: case study of the Moervaart paleolake area (NW Belgium), *Radiocarbon* 56, 899--912.

CROMBÉ P. & VAN DER HAEGEN G. 1994a: Een midden-paleolithische vindplaats te Aalter \"Nieuwendam\" (OostVlaanderen)*,* *Notae Praehistoricae* 14, 29-37.

CROMBÉ P. & VAN DER HAEGEN G. 1994b: *Het Midden-Paleolithicum in Noordwestelijk België*, Archeologische Inventaris Vlaanderen, Buitengewone Reeks 3, Zingem.

CROMBÉ P. & VAN DER HAEGEN G. 1994c: Inventaris van de Midden-Paleolithische vindplaatsen in Noordwestelijk België, in: CROMBÉ P. & VAN DER HAEGEN G. (Red.), *Het Midden-Paleolithicum in Noordwestelijk België*, Archeologische Inventaris Vlaanderen, Buitengewone Reeks 3, Zingem, 103-130.

CROMBÉ P. & VAN DER HAEGEN G. 1994d: Twee Midden-Paleolithische vindplaatsen te Aalter (O-Vl.), in: CROMBÉ P. & VAN DER HAEGEN G. (Red.), *Het Midden-Paleolithicum in Noordwestelijk België*, Archeologische Inventaris Vlaanderen, Buitengewone Reeks 3, Zingem, 49-95.

CROMBÉ P., VAN ROEYEN J.-P., SERGANT J., PERDAEN Y., CORDEMANS K. & VAN STRYDONCK M. 2000: Doel \"Deurganckdok\" (Flanders, Belgium): settlement traces from the Final Palaeolithic and the Early to Middle Neolithic*,* *Notae Praehistoricae* 20, 111-119.

CROMBÉ P., VAN STRYDONCK M., BOUDIN M., DERESE C., VANDENBERGHE D., VAN DEN HAUTE P., COURT-PICON M. & VERNIERS

J. 2011: Absolute dating (14C and OSL) the formation of coversand ridges occupied by prehistoric man in NW Belgium. In: *Radiocarbon and Archaeology, 6th International symposium, Abstracts. Presented at the 6th International symposium on Radiocarbon and Archaeology*, Pafos, Griekenland.

CROMBÉ P. & VERBRUGGEN C. 2002: The Late Glacial and Early Post Glacial occupation of northern Belgium: the evidence from Sandy Flanders, in: ERIKSEN B. V. & BRATLUND B. (Red.), *Recent studies in the Final Palaeolithic of the European plain, Proceedings of a U.I.S.P.P. Symposium (Stockholm, october 1999)*, Jutland Archaeological Society Publications 39, Arhus, 165-180.

CROMBÉ P. & VERHEGGE J. 2015: In search of sealed palaeolithic and mesolithic sites using core sampling: the impact of grid size, meshes and auger diameter on discovery probability, *Journal of Archaeological Science* *53*, 445--458.

DEPAEPE P. & SÉARA F. 2010: Le diagnostic des sites paléolithiques et mésolithiques. Inrap. Séminaire méthodologique, Dec 2006, Parijs, *Les Cahiers de l'Inrap*, doi: 2-915816-12-9.

DE BIE M. 1988: '*Tjongeriaan'. Kritische terugblik op conceptie en gebruik in de archeologische literatuur*, onuitgegeven licentiaatsverhandeling, Katholieke Universiteit Leuven.

DE BIE M. 1998: Late Palaeolithic tool production strategies: technological evidence from Rekem (Belgium), in:

MILLIKEN S. & PERESANI M. (Red.), *Proceedings of the XIIIthe International Congress of Prehistoric and*

*Protohistoric Sciences (Forli, september 1996). Workshop 12: Lithic technology: from raw material procurement to tool production*, Forli, 818-823.

DE BIE M. 1999: Knapping techniques from the Late Palaeolithic to the Early Mesolithic in Flanders (Belgium): preliminary observations, in: THÉVENIN A. & BINTZ P. (Red.), *l\'Europe des derniers chasseurs, Epipaléolithique et Mésolithique. Peuplement et paléoenvironnement de l\'Epipaléolithique et du Mésolithique. Actes du 5e Colloque International U.I.S.P.P. (Grenoble, septembre 1995)*, Parijs, 179-188.

DE BIE M. 2000: *Het Steentijdmonument te Meer-Meirberg (Hoogstraten). Archeologisch waarderingsonderzoek, campagne 1999*, Intern IAP-rapport, Asse-Zellik.

DE BIE M. 2005a: Het onderzoek van de steentijden. Synthese en reflectie, in: IN \'T VEN I. & DE CLERCQ W. (Red.), *Een lijn door het landschap. Archeologie en het vTn-project 1997-1998*, Archeologie in Vlaanderen 5, Brussel, 229-234.

DE BIE M. 2005b: Case-studies archeologie in bos- en natuurgebied. In: BASTIAENS J. (Ed.) *Archeologisch en paleoecologisch erfgoed*, Inverde & VIOE, Hoeilaart, 6.1-6.10.

DE BIE M. 2006: La dynamique des burins dans les industries à *Federmesser* (aziliennes): observations sur le site de Rekem (Belgique). In: DE ARAUJO IGREJA M., BRACCO J.-P. & LE BRUN-RICALENS F. (red.) *Burins préhistoriques: formes, fonctionnements, fonctions*. (ArchéoLogiques 2), Luxembourg, Musée national d'histoire et d'art, 277295.

DE BIE M. 2007: Benefitting from refitting in Intra-Site Analysis: Lessons from Rekem. In: SCHURMANS U. & DE BIE M. (red.): *Fitting Rocks. Lithic Refitting Examined*, BAR International Series 1596, Oxford: Archaeopress, 31-44.

DE BIE M. & CASPAR J.-P. 2000: Rekem, A Federmesser Camp on the Meuse River Bank, *Archeologie in Vlaanderen 3 & Acta Archaeologica Lovaniensa* 10, Asse-Zellik & Leuven.

DE BIE M., GULLENTOPS F. & VAN GILS M. 2003: Een laat-paleolithische concentratie in een Usselo-bodem op de Maatheide in Lommel, *Notae Praehistoricae* 23, 33-37.

DE BIE M., HUYGE D. & VERMEERSCH P. M. 1992: Laat-Paleolithicum op de Luienberg te Assent (gem. Bekkevoort, prov. Brabant)*,* *Archeologie in Vlaanderen* 2, 11-20.

DE BIE M., SCHURMANS U. & CASPAR J.P. 2002: On knapping spots and living areas: intrasite differentiation at Late Palaeolithic Rekem. In: ERIKSEN B.V. & BRATLUND B. (red.) *Recent studies in the Final Palaeolithic of the European plain. Proceedings of a U.I.S.P.P. Symposium, 14.-17. October 1999*. Jutland Archaeological Society Publications 39, Århus, Aarhus University Press, 139-164.

DE BIE M. & VAN GILS M. 2004: Steentijdsites op de Maatheide te Lommel. Archaeologisch waarderingsonderzoek 2003*,* *Te Lommele op die Campine* 30.2, 13-21.

DE BIE M. & VAN GILS M. 2005: Steentijdsites op de Maatheide te Lommel. Archaeologische opgravingen 2004, *Te Lommele op die Campine* 31.2, 3-13.

DE BIE M. & VAN GILS M. 2006a: Federmessersites te Lommel-Maatheide: opgravingscampagne 2005, in: CALLEBAUT D. (Ed.), *Vlaams Instituut voor het Onroerend Erfgoed. Een nieuw perspectief voor erfgoedonderzoek*, Brussel, 118-119.

DE BIE M. & VAN GILS M. 2006b: Les habitats des groupes à *Federmesser* (aziliens) dans le Nord de la Belgique, *Bulletin de la Société Préhistorique Française* 103, 781-790.

DE BIE M., VAN GILS M. & DEFORCE K. 2009: Human occupation in a Late Glacial Landscape: the Federmesser site complex at Lommel (Belgium). In: STREET M., BARTON N.R.E. & TERBERGER T. (Eds), *Humans, Environment and Chronology of the Late Glacial of the North European Plain. Proceedings of workshop 14 (Commission XXXII) on the 15th U.I.S.P.P. congress, Lisbon, September 2006*, RGZM-Tagungen 6, Mainz, 77-87.

DE BIE M. & VERMEERSCH P. M. 1998: The Pleistocene-Holocene transition in the Benelux*,* *Quarternary International* 49/50, 29-43.

DE CLERCQ W., BATS M., BOURGEOIS J., CROMBÉ P., DE MULDER G., DE REU J., HERREMANS D., LALOO P., LOMBAERT L., PLETS G., SERGANT J. & STICHELBAUT B. 2012: Development-led archaeology in Flanders: An overview of practices and results in het period 1990-2010. In: WEBLEY L., VANDER LINDEN M., HASELGROVE C. & BRADLEY R. (Red.). *Developmentled Archaeology in Northwest Europe. Proceedings of a Round-Table at the University of Leicester, 19^th^-21^st^ November 2009*. Oxbbow Books, Oxbow, 29-55.

DEEBEN J., DRENTH E., VAN OORSOUW M.F. & VERHART L. 2005: De steentijd van Nederland, *Archeologie* 11/12, Meppel.

DEEBEN J. & RENSINK E. 2005: Het Laat-Paleolithicum in Zuid-Nederland. In: DEEBEN J., DRENTH E., VAN OORSOUW M.F. & VERHART L. 2005: De steentijd van Nederland, *Archeologie* 11/12, Meppel, 171-199.

DEFLEUR A. R. & DESCLAUX E. 2019: Impact of the last interglacial climate change on ecosystems and Neanderthals behavior at Baume Moula-Guercy, Ardèche, France, *Journal of Archaeological Science* 104, 114-124.

DÉBENATH A. & DIBBLE H. 1993: *Handbook of Paleolithic typology. Volume One. Lower and Middle Paleolithic of Europe*, Philadelphia: University of Pennsylvania.

DELVOIE S. 2017: *Caracteérisation multiéchelle du loess de Hesbaye (Belgique) par une approche couplé géologique et géotechnique*, onuitgegeven doctoraatsverhandeling, Faculté des Sciences Appliquées Université de Liège, Luik.

DELVOIE S., BOULVAIN F., CAHRLIER R. & COLLIN F. 2016: Detailed characterization of the Late Pleistocene loess sequence stratigraphy of Remicourt (Hesbaye Region, Belgium) with cone penetration tests, *Geologica Belgica* 19 (3/4), 281-289.

DELVOIE S., PIRSON S., CHARLIER R. & COLLIN F. 2016: Étude de la séquence stratigraphique des loess de la carrière de Romont (Eben-Emael, Belgique) par une campagne géotechnique. *Notae Praehistoricae* 36, 5-21.

DEMARS P.-Y. & LAURENT P. 2000: *Types d'outils lithiques du paléolithique supérieur en Europe*, Parijs.

DEMEY, D. 2011: *Opgravingen aan de Steenbakkersstraat te Gistel. Een brandrestengraf uit de Romeinse tijd en sporen van vol- en laatmiddeleeuwse landelijke bewoning*, onuitgegeven rapport Ruben Willaert bvba.

DERESE C., VANDENBERGHE D., VAN GILS M., MEES F., PAULISSEN E. & VAN DEN HAUTE P. 2012: Final Palaeolithic settlements of the Campine region (NE Belgium) in their environmental context: Optical age constraints, *Quaternary International* 251, 7--21.

DEVRIENDT I., MESSIAEN L., DECONYNCK J., LALOO P., SERGANT J. & BATS M. 2011: *Evergem -- De Nest: Rapportage van het archeologisch onderzoek van enkele steentijdvindplaatsen en van een laatmiddeleeuws greppelsysteem*, GATE rapport 13, Gent.

DEWERTE E. & CROMBÉ P. 2018: The ethnography of prehistoric forest fires, *Notae Praehistoricae* 39, 5-14.

DE HEINZELIN J. 1949: Présentation des gisements Paléolithiques de la Belgique dans le cadre des régions naturelles*,* *Koninklijk Belgisch Instituut Voor Natuurwetenschappen*, 1-18.

DE HEINZELIN J. 1962: *Manuel de typologie des industries lithiques*, Brussel.

DE HEINZELIN J. & SPITAELS P. 1962: Moustérien, Tjongérien et Mésolithique à Mol*,* *Helinium* 2, 244-251.

DE LAET S. J. 1957: *Archaeology and its Problems*, Londen.

DE LAET S. J. 1958: *The Low Countries*, Londen.

DE LAET S.J. 1963: Un gobelet campaniforme à Huise (Flandre orientale) et la distribution des vases campaniformes en Belgique*,* *Helinium* 3, 235-241.

DE LAET S. J. 1974 (2^de^ Ed. 1979): *Prehistorische Kulturen in het Zuiden der Lage Landen*, Wetteren.

DE LAET S. J. 1982: *La Belgique d\'avant les Romains*, Wetteren.

DE LAET S. J. & GLASBERGEN W. 1959: *De Voorgeschiedenis der Lage Landen*, Groningen.

DE LOECKER D. 2005: Beyond the Site: The Saalian Archaeological Record at Maastricht-Belvédère, The Netherlands, *Analecta praehistorica Leidensia* 35-36.

DE MOOR G. & HEYSE I., 1974: Lithostratigrafie van de quartaire afzettingen in de overgangszone tussen Kustvlakte en de Vlaamse Vallei in Noordwest-België, *Natuurwetenschappelijk Tijdschrift* 56, 85-109.

DE NUTTE G. 2008: *Het Magdaleniaan gedurende het Laat-Glaciaal in Noordwest-Europa. Een lithische, fauna, prospectie en topografische analyse in functie van (herkolonisatie)nederzettingspatronen*, onuitgegeven licentiaatsverhandeling, Katholieke Universitiet Leuven.

DE SONNEVILLE-BORDES D. 1961: Le Paléolithique supérieur en Belgique*,* *l\'Anthropologie* 65, 421-443.

DE SONNEVILLE-BORDES D. & PERROT J. 1956: Lexique typologique du Paléolithique supérieur*,* *Bulletin de la Société Préhistorique Française*, 327-335.

DE SMEDT PH., VAN MEIRVENNE M., MEERSCHMAN E., SAEY T., BATS M., COURT-PICON M., DE REU J., ZWERTVAEGHER., ANTOP M., BOURGEOIS J., DE MAEYER P., FINKE, P.A., VERNIERS J., CROMBÉ PH. 2011: Reconstructing palaeochannel morphology with a mobile multicoil electromagnetic induction sensor, *Geomorphology* 130, 3-4, 136-141.

DE SMEDT PH., VAN PARYS V., VAN MEIRVENNE M. 2011: *Geofysisch bodemonderzoek. Electromagnetische inductie. Moervaart Noord (Sint-Kruis-Winkel/ Mendonk)*, onderzoeksrapport UGent.

DE WILDE B. 2011: Pleistocene Zoogdieren Uit De Kleigroeve Van Oekene. *West-Vlaamse Archaeologica* 24, 5056.

DIJKSTRA P., BINK M. & DE BIE M. 2007: Sporen, structuren en vondsten uit de steentijden. In: BINK M. (Red.) *Tongeren-Pliniusterrein. Archeologisch onderzoek van resten uit het laat paleolithicum, de ijzertijd en de nieuwe tijd*, BAAC-rapport 06.177, 16-47.

DI MODICA K. 2010: *Les productions lithiques du Paléolithique moyen de belgique: variabilité des systèmes d'acquisition et des technologies en réponse à une mosaïque d'environnements contrastés*, Luik: Université de Liège.

DI MODICA K. 2011a : La documentation du Paléolithique moyen en Belgique aujourd'hui, état de la question. In:

TOUSSAINT, M., DI MODICA, K., PIRSON, S. (Red.), *Le Paléolithique moyen en Belgique*. *Mélanges Marguerite UlrixClosset*, Luik, 75-104.

DI MODICA K. 2011b : Variabilité des systèmes d'acquisition et de production lithique en réponse à une mosaïque d'environnements contrastes dans le Paleolithique moyen de Belgique. In: TOUSSAINT M., DI MODICA K., PIRSON S. (Red.), *Le Paleolithique moyen en Belgique. Mélanges Marguerite Ulrix-Closset*, Luik, 213-228.

DI MODICA K., TOUISSAINT M., ABRAMS G. & PIRSON S. 2016: The Middle Palaeolithic from Belgium:

Chronostratigraphy, territorial management and culture on a mosaic of contrasting environments, *Quaternary International* 411A, 77-106.

DYSELINCK T. 2015: *Archeologische opgraving Wevelgem Zuid*, BAAC Vlaanderen Rapport 137, Gent.

FIERS G., HALBRUCKER E., DE KOCK T., LAFORCE B., VANDENDRIESSCHE H., MESSIAEN L., VINCZE L., CROMBÉ P. & CNUDDE V.

2017: Preliminary characterization of flint raw material used on prehistoric sites in NW Belgium. *Geoarchaeology* 34*,* 400-412, doi: 10.1002/gea.21719.

GAFFNEY V., *Europe\'s Lost Frontiers* \[online\][, https://lostfrontiers.teamapp.com/ (](https://lostfrontiers.teamapp.com/)geraadpleegd op 31 mei 2021).

GEERTS F. 1984: The Caris collection of Lommel*,* *Notae Praehistoricae* 4, 17-22.

GEERTS F., DEFORCE K., VAN GILS M. & DE BIE M. 2006: Federmessersites te Lommel-Maatheide (prov. Limburg). Opgravingscampagne 2006 en eerste resultaten van het paleo-ecologisch onderzoek*,* *Notae Praehistoricae* 26, 125-128.

GEERTS F., VAN GILS M. & DE BIE M. 2008: Federmessersites te Lommel-Maatheide (prov. Limburg, B). De opgravingscampagne van 2008, *Notae Praehistoricae* 28, 43-45.

GELORINI V., MEERSSCHAERT L., BATS M., BOUDIN M., CALJON L., VAN STRYDONCK M., CROMBÉ P., THOEN E. 2007: Archeologisch en paleoecologisch onderzoek in het landinrichtingsproject Grote Netegebied voor de inrichtingsplannen Kempisch Plateau en open ruimte tussen Hechtel en Eksel. UGent Archeologische Rapporten 6, Gent.

GERMONPRÉ M. & ERVYNCK A. 1988: Pleistocene zoogdierresten te Uitbergen (Oost-Vlaanderen, België), *Cranium* 5/1, 5-7.

GERMONPRÉ M. 1999: Mammoth taphonomy of two fluvial sites from the Flemish Valley, Belgium. *Advances in Mammoth Research*, 171-184.

GERMONPRÉ M., BOGEMANS F. & VAN NEER W. 1993: The Dating of two Pleistocene Mammal Assemblages from the Flemish Valley (Belgium)*,* *Contributions Tertiary and Quaternary Geology* 30, 147-153.

GIERTS I. & CORNELIS L. 2014: Archeologische opgraving Maldegem, Oude Staatsbaan, *BAAC Vlaanderen Rapport,* doi: 90 2013/004.

GIJSELINGS G. & DOPERÉ F. 1983: Een midden-paleolithisch site te Lauw*,* *Notae Praehistoricae* 3, 4-24.

GODERIS J. & HAMEEUW H. 2011: Roeselare-Oekene Archeologisch onderzoek op vondsten uit het Paleotithicum, *West-Vlaamse Archeologica 24*, 40-49.

GORDON CHILDE V. 1956: *Man makes Himself*, Londen.

GOVAL, E. 2012 : *Peuplements néandertaliens dans le nord de la France*, Inrap CNRS Éditions, Recherches archéologiques 4.

GROENENDIJK A., MEIJS E., GULLENTOPS F., BRINGMANS P. & VERMEERSCH P. M. 2001: Overview of the Stratigraphy and the Archaeological Levels in the Nelissen Brickyard Quarry at Kesselt (Belgium), in: BRINGMANS P. (red.), *Stratigraphy and Prehistory of the River Maazs Valley in Limburg. Excursion guide*, 15-20.

GROUPE D\'ETUDE DE L\'EPIPALEOLITHIQUE ET DU MESOLITHIQUE 1969: Epipaléolithique-Mésolithique. Les microlithes géometriques*,* *Bulletin de la Société Préhistorique Française* 66, 355-366.

GROUPE D\'ETUDE DE L\'EPIPALEOLITHIQUE ET DU MESOLITHIQUE 1972: Epipaléolithique-Mésolithique. Les armatures non géométriques (1)*,* *Bulletin de la Société Préhistorique Française* 69, 364-375.

GROUPE D\'ETUDE DE L\'EPIPALEOLITHIQUE ET DU MESOLITHIQUE 1975: Epipaléolithique-Mésolithique. L\'outillage du fonds communs (1)*,* *Bulletin de la Société Préhistorique Française* 72, 319-332.

GULLENTOPS F. 1956: Etude stratigraphique et géologique du gisement paléolithique de Lommel 3, in:

VERHEYLEWEGHEN J. (Ed.) Le Paléolithique final de culture périgordienne du gisement préhistorique de Lommel (Province de Limbourg-Belgique), *Bulletin de la Société Royale Belge d\'Anthropologie et Préhistoire* 57, 54-62.

Habermehl D., Boreel G., Van Beurden L., Chtcheglov M., Hebinck K., Van Kampen J., Kubistal P., Van Renswoude J., Sinke A., Smits L., De Vos K. & Wesdorp M. 2014: *Opgravingen aan de Spelverstraat te Bilzen.*

*Een nederzetting uit de Ijzertijd,* Zuidnederlandse Archeologische Notities 324, Amsterdam: VUhbs Archeologie.

HAMAL-NANDRIN J. & SERVAIS J. 1909: Contribution à l\'étude du préhistorique dans la campine Limbourgeoise*,* *Annales de la Fédération Archéologique et Historique de la Belgique* 21, 202-225.

HAMAL-NANDRIN J., SERVAIS J. & LOUIS M. 1935: Nouvelle contribution à l\'étude du préhistorique dans la Campine limbourgeoise (Belgique)*,* *Bulletin de la Société Préhistorique Française* 32, 175-203.

HAMEEUW, H., ANDRIES, G., GODERIS, J. & HANTSON, W. 2012: Some preliminary notes on the Late Pleistocene contexts and Middle Palaeolithic finds in Oekene (West Flanders, B). *Notae Praehistoricae* 32, 141--145.

HAESAERTS P. & DE HEINZELIN J. 1979: *Le site paléolithique de Maisières-Canal*, Brugge.

HERISSON D., BRENET M., CLIQUET D., MONCEL M-H., RICHTER J., SCOTT B., VAN BAELEN A., DI MODICA K., DE LOECKER D.,

ASHTON N., BOURGUIGNON L., DELAGNES A., FAIVRE J-P., FOLGADO-LOPEZ M., LOCHT J-L., POPE M., RAYNAL J-P., ROEBROEKS W., SANTAGATA C., TURQ A. & VAN PEER, P. 2016: The emergence of the Middle Palaeolithic in north-western Europe and its southern fringes, *Quaternary International* 411, 233-283.

HEYSE I. & DEMOULIN A. 2018: The Flemish Valley: response of the Scheldt drainage system to climatic and GlacioEustatic oscillations. In: DEMOULIN A. (red.), *Landscapes and landforms of Belgium and Luxembourg*, 297-311.

HEYSE I. & DE MOOR G. 1979: Fysische aspekten van Binnen-Vlaanderen. Verslag van de excursie van 26 oktober 1977, *De aardrijkskunde* 1979-1, 25-49.

HUBLIN J., WESTON D., GUNZA P, RICHARD M., ROEBROEKS W., GLIMMERVEEN J. & ANTHONIS L. 2009: Out of the North Sea: the Zeeland Ridges Neandertal, *Journal of Human Evolution* 57.6, 777-785.

HUYGE D. 1990: Mousterian skiffle? Note on a Middle Palaeolithic engraved bone from Schulen, Belgium*,* *Art Rock Research (AURA)* 7, 125-132.

JACOPS J., MEYLEMANS E., PERDAEN Y., BOGEMANS F., DEFORCE K., STORME A. & VERDURMEN I. 2010: Prospectie- en evaluatieonderzoek in het kader van het Sigmaplan, deel 3, *Notae Praehistoricae* 30, 101-109.

JACQUIER J., VANDENDRIESSCHE H. & CROMBÉ P. 2018: Ruien \'Rosalinde\' (comm. de Kluisbergen, BE): étude fonctionnelle de l'industrie lithique du Paléolithique final, *Notae Praehistoricae* 38, 5-14.

JANSSENS P. 1965: Een paleolithische vindplaats te Merksplas*,* *Noordgouw* 5, 169-182.

JANSSENS M. 2013: *IJzertijdsporen langs de Koude Beek. Onderzoeksgebied Park Groot Schijn te Deurne, gemeente Antwerpen; archeologische opgraving*, RAAP-RAPPORT 2695.

JARRY M., BOURGUIGNON L., BRENET M., FOLGADO M., LELOUVIER L., ORTEGA I. 2007 : L\'enregistrement des données issues de sites paléolithiques : principes et méthodes à partir de quelques exemples, *Séminaire méthodologique de l'Inrap (Nîmes 25-27 septembre 2007).*

KOLEN J., DE LOEKER D., GROENENDIJK A. & DE WARRIMONT J.P. 1999: Middle Palaeolithic surface scatters: how informative? A case study from Southern Limburg (The Netherlands). In: ROEBROEKS W. & GAMBLE C. (Red.), *The Middle Palaeolithic Occupation of Europe,* Leiden: University of Leiden Press, 77-191.

LAARMAN F. 2007: Archeozoölogisch onderzoek, in: BINK M. (Ed.), *Tongeren Plinius-terrein. Archeologisch onderzoek van resten uit het laat paleolithicum, de ijzertijd en de nieuwe tijd*, BAAC-rapport 03.177, s\'Hertogenbosch, 88.

LAFORCE B., FIERS G., VANDENDRIESSCHE H., CROMBÉ P., CNUDDE V. & VINCZE L. 2021: Monte Carlo Simulation Aided Quantitative Laboratory X-ray Fluorescence Analysis and Its Application in Provenancing Studies for GeoArchaeological Samples, *Analytical Chemistry* 93, 3898--3904, doi: 3898-3904.

LAUWERS R. 1985a: Découverte d\'un vaste campement du Paléolithique final dans la vallée de la Meuse, Belgique*,* *L\'Anthropologie* 89, 557-559.

LAUWERS R. 1985b: Eerste opgravingscampagne op de Tjongeriaannederzetting te Rekem*,* *Archaeologia Belgica* I (2), 7-12.

LAUWERS R. 1985c: Het Tjongeriaansite van Rekem: De campagne 1985*,* *Notae Praehistoricae* 5, 135-136.

LAUWERS R. 1985d: Tjongeriaannederzetting te Rekem (Limburg): Eerste opgravingscampagne*,* *Notae Praehistoricae* 5, 43-50.

LAUWERS R. 1986a: Een tweede opgravingscampagne op de Tjongeriaannederzetting van Rekem*,* *Notae Praehistoricae* 6, 33-42.

LAUWERS R. 1986b: Verder onderzoek op de Tjongeriaannederzetting te Rekem(gem. Lanaken)*,* *Archaeologia Belgica* II (1), 9-14.

LAUWERS R. 1988: Le gisement Tjongerien de Rekem (Belgique). Premier bilan d\'une analyse spatiale, in: OTTE M. (Ed.) *De la Loire à l\'Oder. Les civilisations du Paléolithique final dans le nord-ouest européen, Actes du Colloque (Liège, décembre 1985)*, British Archaeological Reports, International Series 444, Oxford, 217-234.

LAUWERS R. & MEIJS E. 1985: Ein Mittelpaläolitischer Fundplatz in Kesselt (prov.Limburg, Belgien). Erste Ergebnisse*,* *Archäologisches Korrespondenzblatt* 15, 123-129.

LEYSEN N. 2003: *De nuchtere en pragmatische houding van de Vlaamse archeologie ten opzichte van theorievorming. Een zegen of een vloek?*, onuitgegeven licentiaatsverhandeling, Universiteit Gent.

MEIJS E.P.M. 2011: The Veldwezelt site (province of Limburg, Belgium): environmental and stratigraphical interpretations, *Netherlands Journal of Geosciences* 90, 73-94.

MEIJS E.P.M. VAN PEER P. & DE WARRIMONT J.P.L.M.N. 2012: Geomorphologic context and proposed chronostratigraphic position of Lower Palaeolithic artefacts from the Op de Schans pit near Kesselt (Belgium) to the west of Maastricht, *Netherlands Journal of Geosciences* 91, 137-157: doi: 10.1017/S0016774600001554 (geraadpleegd op 31 mei 2021).

MEIRSMAN E., VANMONTFORT B. & VAN PEER P. 2008: *Waardering van de site Bergstraat te Oud-Turnhout (OudTurnhout, provincie Antwerpen) in het kader van een eventuele toekomstige bescherming, Evaluatie- en waarderingsonderzoeken archeologie*, Onroerend Erfgoed.

MEYLEMANS E., BASTIAENS J., DEFORCE K., DE SMEDT P., STORME A., VAN DEN BREMT P., VAN DRIESSCHE T. & VAN MEIRVENNE M. 2011: *Pro-actief onroerend erfgoedonderzoek in de Moervaart- en Kalevallei in het kader van de natuurcompensatie voor de ontwikkeling van de Gentse Zeehaven. Eindverslag*, Rapport Agentschap Onroerend Erfgoed.

MEYLEMANS E., DE SMEDT P., STORME A., BASTIAENS J., DEFORCE K., DESLOOVER D. & MEIRVENNE M. 2011: A multidisciplinary palaeoenvironmental survey in the western Moervaart-depression (Ghent, prov. Oost-Vlaanderen, B), *Notae Praehistoricae* 31, 191-200.

MEYLEMANS E., BOGEMANS F.,STORME A.,PERDAEN Y.,VERDURMEN I. & DEFORCE K. 2013: Lateglacial and Holocene fluvial dynamics in the Lower Scheldt basin (N-Belgium) and their impact on the presence, detection and preservation potential of the archaeological record, *Quaternary International* 308--309, 148-161, https://doi.org/10.1016/j.quaint.2013.03.034.

MEYLEMANS E., PERDAEN Y. VANHOLME N., COOREMANS B., DEFORCE K., DE GROOTE K., ERVYNCK A., HANECA K., LENTACKER A. & VERDURMEN I., 2021: *Archeologische opgraving van een meerperiodensite in de 'Bergenmeersen'in het kader van het sigmaplan (Gem. Wichelen, prov. Oost-Vlaanderen)*, Onderzoeksrapporten agentschap Onroerend Erfgoed 185.

MISSIAEN T., EVANGELINOS D., CLAERHOUT C., DE CLERCQ M., PIETERS M. & DEMERRE, I. 2018: Archaeological prospection of the nearshore and intertidal area using ultra-high resolution marine acoustic techniques: Results from a test study on the Belgian coast at Ostend-Raversijde, *Geoarchaeology* 33.3, 386-400, https://hdl.handle.net/10.1002/gea.21656

MONCEL M., ASHTON N., ARZARELLO M., FONTANA F., LAMOTTE A., SCOTT B., MUTTILLO B., BERRUTI G., NENZIONI G., TUFFREAU A. & PERETTO C. 2020: Early Levallois core technology between Marine Isotope Stage 12 and 9 in Western Europe, *Journal of Human Evolution* 139, https://doi.org/10.1016/j.jhevol.2019.102735.

MOREAU G. 1986: *Studie van het lithische en het ceramische materiaal van drie prehistorische sites, gelegen in Bierbeek (Brabant)*, onuitgegeven licentiaatsverhandeling, Katholieke Universiteit Leuven.

NARR K. 1968: Studien zur Älteren und Mittleren Steinzeit der Niederen lande, *Antiquitas* 2.7, Bonn.

NICHOLSON C. 2017: Eemian paleoclimate zones and Neanderthal landscape-use: A GIS model of settlement patterning during the last interglacial, *Quaternary International* 438, 144-157.

NIJS K. 1986a: Epipaleolithicum te Meer: Het onderzoek op Meer IV*,* *Notae Praehistoricae* 6, 95-102.

NIJS K. 1986b: *Meer IV, een nederzetting van Epi-pleolitisch jagers-verzamelaars. Refitting en de*

*Paleoetnografische onderzoeksmethode*, onuitgegeven licentiaatsverhandeling, Katholieke Universiteit Leuven.

NIJS K. 1990: A Tjonger and a Mesolithic site at Meer, Belgium, in: CZIESLA E., EICKHOFF S., ARTS N.& WINTER D. (red.), *The big puzzle. International Symposium on refitting Stone Artefacts*, Studies in Modern Archaeology 1, Bonn, 493-506, 10 fig.

NOENS G. & LALOO P. (red.) 2013: NIR Liereman. Archeologische studie, *GATE rapport* 58, 2 delen, Gent.

NOENS G., VAN BAELEN A., DECONYNCK J. & RENIERE S. 2013: Vondstmelding: een paleolithisch bifaciaal bewerkt lithisch artefact ('vuistbijl') uit een middeleeuws grachtspoor te beernem (prov. West-Vlaanderen, B), *Notae Praehistoricae* 33, 139-145.

NOENS G. 2018: The use of auger survey to detect prehistoric artefact distributions in Flanders (1996-2017), *Notae Praehistoricae* 38, 191-220.

NOENS G. 2019: Steentijdprospectie via verkennende archeologische boringen in het kader van de huidige Vlaamse regelgeving, *Notae Praehistoricae* 39, 59-87.

OPHOVEN C. 1938: L'Aurignacien en Belgique. Quelques pointes de Gravette inédites, *Bulletin de la Société Préhistorique Française* 35, 90-105.

OPHOVEN C. 1939: L'Aurignacien en Belgique. Les burins de Lommel, Zonhoven et Zolder, *Bulletin de la Société Préhistorique Française* 36, 454-465.

OPHOVEN C. 1943: L'Aurignacien en Belgique. Les perçoirs de Lommel, Zonhoven et Zolder, *Bulletin de la Société Préhistorique Française* 40, 181-188.

OPHOVEN C. 1947: L\'Aurignacien en Belgique. Les grattoirs de Lommel, Zonhoven et Zolder*,* *Bulletin de la Société Préhistorique Française* 44, 91-96.

OPHOVEN M. 1943: *Quarantes années de Préhistoire du professeur Hamal-Nandrin, 1903-1943*, Luik.

OTTE M., VANDERMOERE N., HEYSE I. & LEOTARD J.-M. 1984: Maldegem et le paléolithique récent du nord-ouest européen*,* *Helinium* XXIV, 105-126.

PEETERS J.H.M., FLEMMING N. & MURPHY P. 2009: *North Sea prehistory research and management framework (NSPRMF) 2009*, Amersfoort: Rijksdienst voor het Cultureel Erfgoed/English Heritage.

PEETERS, J.H.M., AMKREUTZ L.W.S.W., COHEN K.M. & HIJMA M.P. 2019: *North Sea Prehistory Research and Management. Retuning the research and management agenda for prehistoric landscapes and archaeology in the Dutch sector of the continental shelf*, Nederlandse Archeologische Rapporten 63, Amersfoort: Cultural Heritage Agency of the Netherlands.

PELEMAN C., VERMEERSCH P. M. & LUYPAERT I. 1994: Ahrenburgnederzetting te Zonhoven-Molenheide-2*,* *Notae Praehistoricae* 14, 73-80.

PERDAEN Y. 2004: *De lithische technologie van het finaal Paleolithicum en vroeg Mesolithicum: een studie aan de hand van enkele recent opgegraven vindplaatsen in de Wase Scheldepolders*, onuitgegeven doctoraatsverhandeling, Universiteit Gent.

PERDAEN Y., CROMBÉ P. & SERGANT J. 2008: Lithic Technology and the Cultural Identity of Early Mesolithic groups*,* *Current Anthropology* 49**.**2, 317-327.

PERDAEN Y., DEPAEPE I. & WOLTINGE I. in voorbereiding: *Archeologische Opgraving Beveren, Logistiek Park Waasland fase West*, BAAC Vlaanderen Rapport, Bassevelde.

PERDAEN Y., MEYLEMANS E., VANHOLME N. 2013: Preventief onderzoek in het kader van het Sigmaplan te WichelenBergenmeersen (Oost-Vlaanderen, B), *Notae Praehistoricae* 33, 75-89.

PERDAEN Y. & RYSSAERT C. 2002: The Final Palaeolithic site of Verrebroek Dok 2: a confrontation between debitage-typology, attribute analysis and refitting*,* *Notae Praehistoricae* 22, 75-81.

PERDAEN Y., SERGANT J. & CROMBÉ P. 2004: Early Mesolithic Landscape-Use and Site-Use in Northwestern Belgium:

The Evidence from Verrebroek \"Dok\", in: CROMBÉ P. (Ed.), *Proceedings of the XIVth Congress of the \"Union*

*International de Sciences Pré- et Protohistoriques\" (Belgium, September 2001). Proceedings of the symposium \"Landscape-Use during the Final Palaeolithic and Mesolithic in NW Europe; The Formation of Extensive Sites and Site-Complexes*\", British Archaeological Rapports, International Series 1302, 11-18.

PERDAEN Y., WOLTINGE I., DE LOECKER D., VANDER CRUYSSEN M. & OPBROEK M. 2015: *Archeologische opgraving Beveren LPWW. Evaluatierapport fase 2*, BAAC Vlaanderen rapport*,* Bassevelde*.*

PEYRONY D. 1933: Les industries 'aurignaciennes' dans le bassin de la Vézère, *Bulletin de la Société Préhistorique Française* 30, 543-559.

PIETERS M., DEMERRE I., LENAERTS T., ZEEBROEK I., DE BIE M., DE CLERCQ W., DICKINSON W. & MONSIEUR P. 2010: De Noordzee: een waardevol archief onder water. Meer dan 100 jaar onderzoek van strandvondsten en vondsten uit zee in België: een overzicht, *Relicta* 6, 177-218.

PIETERS M., MISSIAEN T., DE CLERCQ M., DEMERRE I., VAN HAELST S. 2020: prehistoric and protohistoric archaeology in the intertidal and subtidal zones of the North Sea, in: *The archaeology of Europe's drowned landscapes,* Cham: Springer, 175--187.

PIRSON ST., SPAGNA P., DELVOIE S., BOSQUET D., DI MODICA K., HAESAERTS P., JUVIGNÉ É. & VAN DER SLOOT P. 2019: Nouvelles recherches à l'ancienne sablière Gritten à Rocourt (comm. de Liège, BE), *Notae Praehistoricae* 38, 99137.

PRILAUX G. & TALON M. 2012: Le programme archéologique du canal Seine-Nord Europe: une opportunité hors normes pour l'étude de la Préhistoire dans le Nord de la France, *Notae Praehistoricae* 32, 99-114.

RENSINK E. 1993: *Moving into the North: Magdalenian Occupation and Exploitation of the Loess Landscapes of Northwestern Europe*, onuitgegeven doctoraatsverhandeling, Rijksuniversiteit Leiden.

RENSINK E. 2010: Eyserheide. A Magdalenian Open-Air Site in the Loess Area of the Netherlands and its Archaeological Context, *Analecta Praehistorica Leidensia* 42, Leiden.

RENSINK E. 2016: Magdalénien, in: AMKREUTZ L., BROUNEN F., DEEBEN J., MACHIELS R., VAN OORSOUW M.-F. & SMITH B. (rred.): *Vuursteen verzameld. Over het zoeken en onderzoeken van steentijdvondsten en -vindplaatsen*, Nederlandse Archeologische Rapporten 50, Amersfoort, 78-85.

RÉVILLION S. 1995: Technologie du débitage laminaire au Paléolithique moyen en Europe septentrionale : état de la question, *Bulletin de la Société préhistorique française* 92/4, 425-442.

ROZOY J.-G. 1968: Typologie de l\'Epipaléolithique (Mésolithique) franco-belge, Issoudun.

ROZOY J.-G. 1978: *Les Derniers Chasseurs. L\'Epipaléolithique en France et en Belgique. Essai de synthèse*, Bulletin de la Société archéologique Champenoise, numéro spécial, Charleville.

RUEBENS K. 2005: Het *Midden-Paleolithisch ensemble van Oosthoven (België). Een techno-typologische en vergelijkende analyse*, onuitgegeven licentiaatsverhandeling, Katholieke Universiteit Leuven.

RUEBENS K. 2006: A typological dilemma: Micoquian elements in continental Northwestern Europe during the last glacial cycle (MIS 5d-3), *Lithics. The Journal of the Lithic Studies Society* 27, 58-73.

RUEBENS K. 2014: Late Middle Palaeolithic bifacial technologies across northwest Europe: Typo-technological variability and trends, *Quaternary International* 350, 130-146.

RUEBENS K. & DI MODICA K. 2011: Les productions bifaciales du Paléolithique moyen sur le territoire belge. Présentation d\'industries entre deux mondes. In: Toussaint M., Di Modica K., Pirson S., (Red.), *Le Paléolithique moyen en Belgique*. *Mélanges Marguerite Ulrix-Closset*, Luik, 239-260.

RUEBENS K. & VAN PEER P. 2011: A Middle Palaeolithic site with small bifaces at Oosthoven-Heieinde (Northern Belgium). In: TOUSSAINT M., DI MODICA K. & PIRSON S. (Red.), *Le Paléolithique Moyen en Belgique*. *Mélanges Marguerite Ulrix-Closset,* Luik, 353-358.

RUEBENS K., SMITH G. & VAN PEER P. 2014: *Contextualisering van het Midden Paleolithisch ensemble van Oosthoven (Noord-België)*: Veldwerkrapport, Leuven.

RYSSAERT C. 2004: Het Midden-Paleolithicum in Vlaams-Brabant. Neanderthalers aan de rand van de Vlaamse Vallei, *Archeologie 2004: Provinciale infodag. Recent archeologisch onderzoek in Vlaams-Brabant*, 15-18.

RYSSAERT C. 2006: Lithische technologie te Mesvin IV: selectiecriteria voor geretoucheerde werktuigen en hun relatie met Levalloiseindproducten. *Anthropologia et Praehistorica* 117, 13-34.

RYSSAERT C., DEGRYSE J., TYS D., BAETEMAN C., ORBONS J., PYPE P. & PERDAEN Y. 2010: Steentijdvondsten te VerAssebroek (Brugge, West-Vlaanderen): hoe het onderzoek naar een middeleeuws kasteel naar een steentijdlandschap kan leiden, *Notae Praehistoricae*, 43-48.

RYSSAERT C., PERDAEN Y. & VAN DEN BREMT A. 2003: Een verrassende steentijdvondst te Gent-Tweekerkenstraat*,* *Notae Praehistoricae* 23, 45-53.

RYSSAERT C., PERDAEN Y., DE MAEYER W., LALOO P., DE CLERCQ W. & CROMBÉ P. 2007: Searching for the Stone Age in the harbour of Ghent. How to combine test trenching and Stone Age Archaeology*,* *Notae Praehistoricae* 27, 6974.

SCHWABEDISSEN H. 1954: *Die Federmesser-Gruppen des nordwesteuropaïschen Flachlandes. Zur Ausbreitung des Spät-Magdalénien*, Neumunster.

SCOTT B. & ASHTON N. 2011: The Early Middle Palaeolithic: The European Context. In: ASHTON N., LEWIS S., STRINGER C. (Red.) *Developments in Quaternary Sciences* 14, 91-112.

SERGANT J. 1995: *Een onderzoek naar de steentijd in het Aalsterse*, onuitgegeven licentiaatsverhandeling, Universiteit Gent.

SERGANT J. 2004: Steentijdvondsten in de regio Aalst (Oost-Vlaanderen en Brabant, België). Inventaris en geografische analyse, *Archeologische Inventaris Vlaanderen. Buitengewone reeks* 8, Gent.

SEVENANTS W. 2009: *Archeologische prospectie met ingreep in de bodem. Wijk Wolsemveld (fase 1) Zuurweidestraat te Dilbeek*, 16-17.

SMITH, G., GARCÍA-MORENO, A., KINDLER, L., GAUDZINSKI-WINDHEUSER, S. 2014: The Middle Palaeolithic site of Neumark Nord 2: Neanderthal adaptation and behaviour within an Eemian lakeland environment. *Conference paper XVII World Congress UISPP*.

STORME A., LOUWYE S., CROMBÉ P., & DEFORCE K. 2017: Postglacial evolution of vegetation and environment in the Scheldt Basin (northern Belgium), *Vegetation History and Archaeobotany*, 26, 293--311.

TOUSSAINT M., DI MODICA K. & PIRSON S. (Red.) 2011: Le Paleolithique moyen en Belgique. Mélanges Marguerite Ulrix-Closset, *Bulletin de la Société Belge d'études Géologiques et Archéologiques « Les Chercheurs de la Wallonie » (hors-série, n° 4) et Études et Recher-ches archéologiques de l'Université de Liège* (ERAUL, 128), Luik.

ULRIX-CLOSSET M. 1975: *Le paléolithique moyen dans le bassin mosan en Belgique*, Wetteren: Éditions Universa.

ULRIX-CLOSSET M., OTTE M. & GOB A. 1981: *Paléolithique et mésolithique au Kemmelberg*, Luik.

VANDENDRIESSCHE H. 2009: *Klimaat, landschap en lithische productie in het vroege Midden-Paleolithicum van Noordwest-Europa*, onuitgegeven thesis, UGent.

VANDENDRIESSCHE H. 2021: *Flintknapping in a Changing World : The Organization of Lithic Technology during the Lateglacial and Early Holocene in the Belgian Scheldt Valley*, onuitgegeven doctoraatstudie, Universiteit Gent, Faculteit Letteren en Wijsbegeerte.

VANDENDRIESSCHE H. & CROMBÉ P. 2019a: Flint knapping at the end of an era: final palaeolithic and early mesolithic technological traditions in northwestern Belgium. *25th EAA annual meeting* (Bern, 2019), 430.

VANDENDRIESSCHE H. & CROMBÉ P. 2019b: L'occupation préhistorique de l'Escaut belge et son cadre paléoenvironnemental: les sites de Ruien et de Kerkhove, *Actes de la journée d'étude : la Vallée de l'Escaut: de l'histoire aux projets de territoire.*

VANDENDRIESSCHE H. & CROMBÉ P. 2019c: Steentijden. Aalter Woestijne: een geschiedenis van meer dan 5000, *Relicta Monografieën* 18, 57-80.

VANDENDRIESSCHE H. & CROMBÉ P. 2020: Formalized reduction sequences from the site of Kerkhove, Belgium: new perspectives on early Mesolithic flint knapping, *Lithic Technology* 45.2, 110-124.

VANDENDRIESSCHE H., VERBRUGGE A., DEGRAEVE A., CHERRETTÉ B. & CROMBÉ P. 2016: De midden- en finaalpaleolithische vondsten van Ronse-Pont West (Oost-Vlaanderen, BE), *Notae Praehistoricae* 36, 91-102.

VANDERBEKEN T. 1998: *De Federmessercultuur in België en Zuid-Nederland: een technologische fasering?*, onuitgegeven licentiaatverhandeling, Katholieke Universiteit Leuven.

VANMOERKERKE J. 1983: Epipaleolithicum onder het Onze-Lieve-Vrouw-Hospitaal te Aalst, in: *Conspectus MCMLXXXII, Archeologia Belgica* 253, 14-16.

VANMOERKERKE J. & DE BELIE A. 1984: Epipaleolithicum en Laat-Neolithicum te Klein-Sinaai*,* *Vobov-info* 14, 1-13.

VANMONTFORT, B., VAN GILS, M., PAULISSEN, E., BASTIAENS, J., DE BIE, M. & MEIRSMAN, E. 2010: Human occupation of the Late and Early Post- Glacial environments in the Liereman Landscape (Campine, Belgium), *Journal of Archaeology in the Low Countries* 2.2, 21.

VANMONTFORT B., VERMEERSCH P. M., GROENENDIJK A. J., MEIJS E. P. M., DE WARRIMONT J.-P. & GULLENTOPS F. 1998: The Middle Palaeolithic Site of Hezerwater at Veldwezelt, Belgian Limburg*,* *Notae Praehistoricae* 18, 5-11.

VANMONTFORT B., YPERMAN W., LAMBRECHTS B., VAN GILS M. & GEERTS F. 2010: Een finaalpaleolithisch en mesolithisch sitecomplex te Lommel, Molse Nete. Opgravingscampagne 2010, *Notae Praehistoricae* 30, 29-34.

VAN ACKER R. 1986: Prehistorische vondsten ten oosten van Brugge*,* *Westvlaamse Archaeologica* 2, 91-103.

VAN BAELEN A. 2014: *Kesselt-Op de Schans (Limburg, Belgium) and the Lower-Middle Palaeolithic transition*. Katholieke Universiteit Leuven.

VAN BAELEN A. 2016: Kesselt‐Op de Schans: een vroeg midden‐paleolithische vindplaats in de löss. In: AMKREUTZ

L., BROUNEN F., DEEBEN J., MACHIELS R., VAN OORSOUW MF. & SMIT B (Red.): *Vuursteen verzameld. Over het zoeken en onderzoeken van steentijdvondsten en ‐vindplaatsen* *Vol.* 50, 314 -- 315.

VAN BAELEN A., MEIJS E., VAN PEER P., DE WARRIMONT J.-P. & DE BIE M. 2007: An Early Middle Palaeolithic site at Kesselt-Op de Schans (Belgian Limburg): Preliminary results*,* *Notae Praehistoricae* 27, 19-26.

VAN BAELEN A., MEIJS E., VAN PEER P., DE WARRIMONT J.-P. & DE BIE M. 2008: The Early Middle Palaeolithic Site of Kesselt - Op de Schans (Belgian Limburg). Excavation Campaign 2008, *Notae Praehistoricae* 28, 5-9.

VAN BAELEN A. & NOENS G. in voorbereiding: *Zoeken naar steentijdartefactensites... of niet? Criteria voor de advisering van een steentijdvervolgtraject in de preventieve archeologie in Vlaanderen*, Rapport synthesestudie.

VAN BAELEN A. & RYSSAERT C. 2011: The Early Middle Palaeolithic of Belgium, in: TOUSSAINT, M., DI MODICA, K. & PIRSON, S. (Red.), *Le Paléolithique moyen en Belgique*. *Mélanges Marguerite Ulrix-Closset*, Luik, 197-212.

VAN BAELEN A., VROOMANS, J.-M. & VAN PEER, P. 2011: A diachronic perspective on the Palaeolithic occupations at Kesselt-Op de Schans, in: TOUSSAINT, M., DI MODICA, K., PIRSON, S. (Red.), *Le Paléolithique moyen en Belgique*. *Mélanges Marguerite Ulrix-Closset*, Luik, 395-398.

VAN DER SLOOT P., PIRSON S. & HAESAERTS P. 2009: Campagne de fouilles 2009 sur le site paléolithique moyen de la Cour Saint-Hubert à Liège (Belgique). Résultats préliminaires, *Notae Praehistoricae* 29, 23-35.

VAN DER VEKEN B. (red.) 2019: *Kasterlee, Binnenpad, Parking. Een archeologische opgraving*, Vlaams Erfgoed Centrum.

VAN DER WAA M. & WILLEMS M. 2019: *Nota Lommel Kristalpark III -- Vario Food Group. Fase 3,* Rapport Archeoworks, Leuven.

VAN DIJCK F. & OTTE M. 2019: Paléolithique en général, et spécialement Moustérien, à Orp-Jauche et Hannut (Prov. Du Brabant wallon, BE). Etat en 2017, *Notae Praehistoricae 39,* 103-112.

VAN GILS M., BELLENS T. 2013: Lithische artefacten uit de burchtzone te Antwerpen (B), *Notae Praehistoricae* 33, 27-31.

VAN GILS M. & DE BIE M. 2001: Prospectie en kartering van laat-glaciale en vroeg-holocene sites in de Kempen: resultaten van de boorcampagne 2001*,* *Notae Praehistoricae* 21, 77-78.

VAN GILS M. & DE BIE M. 2002: Prospectie en kartering van laat-glaciale en vroeg-holocene sites in de Kempen, Boorcampagne 2001, IAP-rapporten 12, Asse-Zellik.

VAN GILS M. & DE BIE M. 2003: Een uitgestrekt Laat-Mesolithisch site-complex langs de Molse Nete in Lommel. *Notae Praehistoricae* 23, 71-73.

VAN GILS M. & DE BIE M. 2006: Steentijd in de Kempen. Prospectie, kartering en waardering van het laatpaleolithisch en mesolithisch erfgoed, in: COUSSERIER K., MEYLEMANS E. & IN \'T VEN I. (Red.), *Centrale*

*Archeologische Inventaris (CAI) II. Thematisch inventarisatie- en evaluatieonderzoek*, VIOE-rapporten 2, Brussel, 7-16.

VAN GILS M. & DE BIE M. 2007: *Kartering en waardering van een nieuw mesolithisch site-complex te Wuustwezel - Het Moerken,* Intern VIOE-rapport, Brussel.

VAN GILS M., DE BIE M., PAULISSEN E. & DEFORCE K. 2009: Katering en waardering van een finaalpaleolithsich/mesolitisch sitecomplex te Arendonk-Korhaan (prov. Antwerpen). Boorcampagne 2003, *Relicta* 4, 9--22.

VAN GILS M., DE WILDE D. & DE BIE M. 2010: Lithic scatters in the plough zone: variability and value, in ARIAS P. (Ed.) *Proceedings of the Eighth International Conference of the Mesolithic in Europe*, *Santander, Spain, September 13-17, 2010*.

VAN GILS M., PAULISSEN E., VANMONTFORT B., DE BIE M., BASTIAENS J. & GEERTS F. 2012: The impact of Late Glacial landscape changes on settlement locations in coversand areas. The evidence for northeastern Belgium. In:

RENSICK E., PEETERS H., VERPOORTE A. (Red.), *Pioneers at the end of the last ice age. Recent studies on Late Palaeolithic hunter-gatherers in Northern and Central Europe. Union Internationale des Sciences Préhistoriques et Protohistoriques, Meeting of Commission XXXII 'The Final Palaeolithic of the Great European Plain', 22nd25th may, 2012*, *Program and abstracts*. Amersfoort: Cultural Heritage Agency, 12-13.

VAN GILS M. & MEYLEMANS E. 2019: *Prospecteren naar steentijd artefactensites -- versie 1*, Agentschap Onroerend Erfgoed.

VAN LIEFFERINGE N. 2007. Jager-verzamelaars op de Grote Buizemont te Geraardsbergen. *Handelingen van het Zottegems genootschap voor Geschiedenis en Oudheidkunde* XIII-2, 5-17.

VAN NEER W., ERVYNCK A. & LENTACKER A. 2005: Archaeozoological analyses, in: CROMBÉ P. (Ed*.), The Last HunterGatherer-Fishermen in Sandy Flanders (NW Belgium). The Verrebroek and Doel Excavation Projects. Volume 1: Palaeo-environment, chronology and features*, Archaeological Reports Ghent University 3, Gent, 279-294.

VAN NESTE T., YPERMAN W., VANMONTFORT B., VAN GILS M. & GEERTS F. 2009: Nieuw onderzoek op het sitecomplex langs de Molse Nete te Lommel, *Notae Praehistoricae* 29, 87-91.

VAN NOTEN F. 1963: *De Tjongercultuur in België*, onuitgegeven verhandeling, Universiteit Gent.

VAN NOTEN F. 1967a: Een Tjongervindplaats te Meer*,* *Archaeologia Belgica* 98, 5-25.

VAN NOTEN F. 1967b: Le Tjongerien en Belgique, *Bulletin de la Société Royale Belge d\'Anthropologie et de Préhistoire* 78, 197-236.

VAN NOTEN F. 1968: Quelques outils Tjongeriens remarquables*,* *Helinium* 8, 149-153.

VAN NOTEN F. (Ed.) 1978: *Les Chasseurs de Meer*, Dissertationes Archaeologicae Gandenses 18, Brugge.

VAN PEER P. 1979: Midden-Paleolithicum te Schulen*,* *Acta Archaeologica Lovaniensia* 18, 1-10.

VAN PEER P. 1982a: A Middle paleolithic industry from Rotselaar (Brabant)*,* *Helinium* 22, 238-254.

VAN PEER P. 1982b: Rotselaar and Schulen. Two Middle Palaeolithic sites from Lower Belgium*,* *Notae Praehistoricae* 2, 11-21.

VAN PEER P. 1986: Le Paléolithique moyen dans le nord-est de la Belgique*,* *Helinium* 26, 157-176.

VAN PEER P. 1991: Epipaleolithicum te Weelde-Eindegoorheide*,* *Notae Praehistoricae* 11, 33-35.

VAN PEER P. 2001: A Status report on the Lower and Middle palaeolithic of Belgium, in: CAUWE N., HAUZEUR A. & VAN BERG P.-L. (Red.), *Prehistory in Belgium. Special issue on the occasion of the XIVth Congress of the International Union of Prehistoric and Protohistoric Sciences*, *Anthropologica et Praehistorica* 112, 11-20.

VAN PEER P. 2020: Het Schulensbroek (Demervallei, BE): een uniek paleolandschappelijk en archeologisch archief. *Notae Praehistoricae* 40, 129-144.

VAN PEER P., JANSSEN J. & VERMEERSCH P. M. 1984: Opgrimbie-De Zijp: deux concentrations lithiques a affinités epipaléolithiques et mésolithiques*,* *Notae Praehistoricae* 4, 9-16.

VAN PEER P., MEYLEMANS E., VAN GILS M. & VERBRUGGE A. 2007: Nijlen-Varenheuvel: Laat-Pleistocene en Holocene occupaties in fluviatiele context uit de vallei van de Kleine Nete*,* *Notae Praehistoricae* 27, 51-59.

VAN PEER P. & SMITH R. 1990: Zemst,\'Bos van AA\': un site du Paléolithique moyen de la partie orientale de la Vallée flamande*,* *Helinium* 30, 157-171.

VAN PEER P. & VERBEEK C. 1994: A middle palaeolithic site at Oosthoven (Northern Campine)*,* *Notae Praehistoricae* 13, 3-11.

VAN PEER P., WILLEMS M., DEGRYSE P., CLAEYS P. & MARINOVA E. 2017: A reconstruction of the stratigraphic position of a former Middle Palaeolithic surface site at Rotselaar -- Toren ter Heide (Flemish Valley, Belgium) using mechanical sounding and geochemical fingerprinting, *Journal of Archaeological Science* 16, 83-93.

VAN REYBROUCK D. 1993: *Theoretische archeologie. Betekenis en relevantie voor het jagers/verzamelaarsonderzoek in de periode 1960-1990*, onuitgegeven licentiaatsverhandeling, Katholieke Universiteit Leuven.

VAN STRYDONCK M. & CROMBÉ P. 2005: Radiocarbon dating, in: CROMBÉ P. (Ed.), *The Last Hunter-GathererFishermen in Sandy Flanders (NW Belgium). The Verrebroek and Doel Excavation Projects. Volume 1: Palaeoenvironment, chronology and features*, Archaeological Reports Ghent University 3, Gent, 180-212.

VAN VLAENDEREN, L., SERGANT, J., DE BOCK, H., DE MEIRELEIR, M. 2006: *Steentijdvondsten in de Moervaart*, Archeologische Inventaris Vlaanderen, Buitengewone reeks 9, Gent.

VERBEEK C. 1994: *Epipaleolithicum en Mesolithicum te Weelde, Eindegoorheide I en II*, onuitgegeven licentiaatsverhandeling, Katholieke Universiteit Leuven.

VERBEEK C. 1997: Epipaleolithische en Mesolithische concentraties in het \"Ruilverkavelingsblok Weelde\" (prov. Antwerpen)*,* *Notae Praehistoricae* 17, 81-84.

VERBEEK C. 1998: Recente opgravingen in het \"Ruilverkavelingsblok Weelde\". Nieuwe epipaleolithische en mesolithische concentraties te Weelde-Eindegoorheide (prov. Antwerpen)*,* *Notae Praehistoricae* 18, 93-99.

VERBEEK C. 1999: *Ruilverkavelingsblok Weelde, preventief noodonderzoek van bedreigde steentijdsites, administratief eindverslag*, Intern IAP-rapport, Asse-Zellik.

VERBEEK C. & VERMEERSCH P. M. 1993: Epipaleolithicum en Mesolithicum te Weelde-Eindegoorheide 2, *Notae Praehistoricae* 12, 77-81.

VERBRUGGE A., DE GRAEVE A., GUILLAUME V., CHERRETÉ B., SERGANT J. & CROMBÉ P. 2012: Een afgedekt finaalpaleolithische site langs de Bovenschelde te Ruien \"Rosalinde\" (gem. Kluisbergen, O-Vl., B): voorlopige resultaten, *Notae Praehistoricae* 32, 151-157.

VERBRUGGE A. & LOMBAERT L. 2008: *De Centrale Archeologische Inventaris (CAI). Evaluatierappport van de redactie op de provincie Oost-Vlaanderen*, UGent-Rapport.

VERBRUGGE A., VANDENDRIESSCHE H., DE GRAEVE A. GUILLAUME V. & CHERRETÉ B. 2021. *Ruien Rosalinde. Archeologisch onderzoek. Eindrapport,* Solva Archeologie Rapport 26.

VERBRUGGEN C., DENYS L. & KIDEN P. 1996: Belgium, IN BERGLUND B., BIRKS H., RALSKA-JASIEWICZOWA M. & WRIGHT H. (Red.), *Palaeoecological events during the last 15,000 years : regional syntheses of palaeoecological studies of lakes and mires in Europe*, Chichester, UK: John Wiley & Sons, 453--474.

VERBRUGGEN F. 2013: *Oud-Turnhout in het veen. Een laat-glaciale en holocene vegetatiegeschiedenis*, BIAX rapport 685.

VERBRUGGEN F., BOURGEOIS I., CRUZ F., BOUDIN M. & CROMBÉ P. 2019: Holocene vegetation dynamics in the Campine coversand area (Liereman, N Belgium) in relation to its human occupation. *Review of Palaeobotany and Palynology* 260, 27--37.

VERHAGEN J.W.H.P., RENSINK E., BATS B. & CROMBE P. 2011: *Optimale strategieën voor het opsporen van Steentijdvindplaatsen met behulp van booronderzoek. Een statistisch perspectief*, Rapportage Archeologische Monumentenzorg 197.

VERHEGGE, J. 2015: *Spatial and Chronological Prehistoric Landscape Reconstruction Using Geo-Archaeological Methods in the Lower Scheldt Floodplain (NW Belgium)*, Ghent University, Faculty of Arts and Philosophy.

VERHEGGE, J., VAN DEN WIJNGAERT, M., & CROMBÉ, P. 2018: Prehistoric landscape mapping along the Scheldt by camera- and conductivity CPT-E, in: HICKS M., PISANÒ F. & PEUCHEN J. (Red.), *Cone Penetration Testing 2018: Proceedings of the 4th International Symposium on Cone Penetration Testing (CPT\'18), 21-22 June, 2018, Delft, The Netherlands.* CRC Press, Londen, 663-668.

VERHEGGE J., STORME A., CRUZ F. & CROMBÉ P. 2021: Cone penetration testing for extensive mapping of deeply buried Late Glacial coversand landscape paleotopography, *Geoarchaeology - an International Journal* 36.1, 130148.

VERHEGGE J. & DELVOIE S. 2021: Direct push, in situ video imaging of buried prehistoric landscapes in soft soils: First results in the polders, coversands, and loess belt of Belgium, *Geomorphology* 373, doi: 107483.

VERHEYLEWEGHEN J. 1956: Le Paléolithique final de culture périgordienne du gisement préhistorique de Lommel (prov. de Limbourg, Belgique)*,* *Bulletin de la Société Royale belge d\'anthropologie et de préhistoire* 67, 179-258.

VERMEERSCH P. M. 1974: De steentijd in het Hageland, *Meer Schoonheid* 20, 1-10.

VERMEERSCH P. M. 1974: Epipaleolithicum en Mesolithicum te Helchteren, Sonnisse Heide*,* *Archaeologia Belgica* 169.

VERMEERSCH P. M. 1976: Un site Tjongérien à Harelbeke, Gavermeersen*,* *Westvlaamse Archaeologica* 4, 33-71.

VERMEERSCH P. M. 1979: Epipaleolithicum te Achel, De Waag*,* *Limburg* 57, 117-129.

VERMEERSCH P. M. 1999: Postdepositional Processes on Epipalaeolithic and Mesolithic Sites in the Sandy Area of

Western Europe, in: THÉVENIN A. & BINTZ P. (Red.), *l\'Europe des derniers chasseurs, Epipaléolithique et Mésolithique. Peuplement et paléoenvironnement de l\'Epipaléolithique et du Mésolithique. Actes du 5e Colloque International U.I.S.P.P. (Grenoble, septembre 1995)*, Parijs, 159-166.

VERMEERSCH P. M. 2006: Reliability of the Stratigraphy and Spatial Structures of Late Pleistocene and Holocene Sites in Sandy Areas -- Mesolithic-Neolithic Contacts in Central Benelux?, in: KIND C.-J. (Ed.) *After the Ice Age: Settlements, subsistence and social development in the Mesolithic of Central Europe*, Materialhefte zur Archäologie in Baden-Württemberg, Stuttgart, 297-303.

VERMEERSCH P. M. 2015: An Ahrensburgian site at Zonhoven-Molenheide (Belgium), *British Archaeological Reports International Series* 2471, Oxford.

VERMEERSCH P. M. & CAROLUS J. 1975: L\'Epipaléolithique de Zolder, Terlamen (Limbourg belge)*,* *Bulletin de la Société Royale belge d\'anthropologie et de préhistoire* 86, 163-176.

VERMEERSCH P. M., LAUWERS R. & VAN PEER P. 1985: Un site Magdalénien à Kanne*,* *Archaeologia Belgica* 1, 17-54.

VERMEERSCH P. M., SYMENS S., VYNCKIER P., GIJSELINGS G. & LAUWERS R. 1987: Orp, Site Magdalénien de plein air (Comm. de Orp-Jauche)*,* *Archaeologia Belgica* 3, 7-56.

VERMEERSCH P. M. & SYMENS N. 1988: Le Magdalénien de plein air en Belgique, in: OTTE M. (Ed.), De la Loire à l\'Oder. Les civilisations du Paléolithique final dans le nord-ouest européen, Actes du Colloque (Liège, décembre 1985), *British Archaeological Rapports*, *International Series* 444, Oxford, 243-258.

VROOMANS J.-M., GULLENTOPS F., VANDERBEKEN T., GROENENDIJK K. & VAN PEER P. 2006: De Midden-Paleolithische vindplaats Veldwezelt-Op de Schans (Limburg): een voorlopig rapport, *Anthropologica et Praehistorica* 117, 512.

VYNCKIER P. & VERMEERSCH P. M. 1988: Paléolithique moyen de Vollezele-Congoberg (Brabant, Belgique), in: *Actes du Colloque (Amiens, 1986)*, 133-139.

VYNCKIER P., VERMEERSCH P. M. & BEECKMANS L. 1988: Le Paléolithique moyen de Vollezele-Congoberg (Brabant, Belgique)*,* *Revue archéologique de Picardie, n° spécial*, 133-140.
