# INLEIDING 

In 2008 werd de eerst versie van de onderzoeksbalans online geplaatst. Dat instrument omvat een evaluatie van de stand van het onderzoek over het onroerend erfgoed in Vlaanderen. Naast een overzicht van de actuele kennis, bevat het ook een opsomming van hiaten in die kennis.

Vanuit het bewustzijn dat het wetenschappelijk onderzoek continu in verandering is, was de onderzoeksbalans oorspronkelijk voorzien om een dynamisch instrument te zijn, dat continu geactualiseerd zou worden onder meer op basis van input of reacties door externen. In de praktijk werkte de actualisering echter niet en bleef de onderzoeksbalans een statische rapportering van de stand van zaken rond 2008.

In 2020 werd vanuit het Agentschap Onroerend Erfgoed een studieopracht uitgeschreven, die tot doel had om de hoofdstukken paleolithicum, mesolithicum en neolithicum te actualiseren. De drie hoofdstukken werden afzonderlijk uitbesteed en respectievelijk aan RAAP België, Gate en Archeoworks - KU Leuven gegund.

De noodzaak tot de actualisatie is mede ingegeven door de grondige veranderingen in het archeologische werkveld tijdens de laatste 12 jaar. Er kwamen nieuwe spelers op de voorgrond, er ontstonden nieuwe uitdagingen en opportuniteiten. De preventieve archeologie naar aanleiding van economische en ruimtelijke ontwikkelingen zorgde voor een grote hoeveelheid nieuwe onderzoeksdata die tot op het niveau van het basisrapport is verwerkt. Bovendien wordt deze preventieve archeologie geconfronteerd met specifieke noden en uitdagingen, zowel op het vlak van beleid als beheer, waarvoor een breed gedragen en geactualiseerde onderzoeksbalans noodzakelijk is.

De onderzoeksbalans omvat een evaluatie van de stand van het onderzoek over het archeologisch erfgoed in Vlaanderen. Het bevat een gekwantificeerd overzicht van het onderzoek doorheen de tijd en in de ruimte, met achtereenvolgens het terreinwerk, de ontsluiting van het onderzoek via publicaties, de gekende vindplaatsen en de voor handen zijnde bronnen. Aanvullend bevat het eveneens een balans van de actuele onderzoeksthema's en -vragen, het methodologisch en theoretisch werk en duidt het de lacunes in de kennis. Aldus fungeert de onderzoeksbalans als kader voor het onderzoek en wil het ook een inspiratiebron zijn voor toekomstig onderzoek. Maar ook bij het sturen van beleid en beheer speelt de onderzoeksbalans een belangrijke rol.

Met het oog op het verzekeren van de continuïteit en uit respect voor de auteurs van de eerste versie van de onderzoeksbalans (nl. Marc de Bie, Philip Van Peer, Philippe Crombé, Marijn van Gils, Ann Van Baelen, Yves Perdaen & David De Wilde), werd voor deze actualisatie zoveel mogelijk vertrokken vanuit de bestaande structuur en teksten. Deze werden door de huidige auteurs (Caroline Ryssaert, Yves Perdaen en Ine Depaepe) aangevuld met nieuwe informatie, geactualiseerde inzichten en waar nodig uitgebreid. Hierbij werd vooral de focus gelegd op de hoofdstukken met betrekking tot de balans van het terreinwerk, ontsluiting, in de tijd, van de bronnen, onderzoeksvragen en methodiek. Terwijl de inleidende hoofdstukken slechts minimaal gewijzigd werden. De teksten werden nagelezen door een aantal belangrijke spelers binnen het paleolithisch onderzoek in Vlaanderen (Philip Van Peer, Philippe Crombé, Hans Vandendriessche, Ann Van Baelen & Gunther Noens) evenals door het begeleidingscomité van het Agentschap Onroerend Erfgoed (Marijn Van Gils, Erwin Meylemans & Marleen Martens). We zijn dan ook bijzonder erkentelijk voor de input en raadgevingen die we van hen mochten ontvangen.

## AFBAKENING IN TIJD EN RUIMTE 

De archeologie van het paleolithicum onderzoekt de vroegste aanwezigheid van de mens in zijn toenmalige milieu op basis van achtergelaten en bewaarde materiële sporen en resten.

Het gaat om de bij uitstek langste periode in de geschiedenis van de mens, waarbij die zelf ook fysiek evolueerde van archaïsche hominide tot de (huidige soort) Homo sapiens. Die biologische evolutie wordt onderzocht in de paleoantropologie, een discipline die in Vlaanderen nauwelijks aan bod komt door het volledig ontbreken van menselijk bot uit deze periode. Dit hoofdstuk bespreekt dus enkel het onderzoek van de nagelaten (materiële) cultuur van deze vroege gemeenschappen, weliswaar binnen de (veranderende) omgeving van het pleistocene milieu.

Het paleolithicum vangt aan met het verschijnen van de vroegste artefacten. De ouderdom daarvan varieert van regio tot regio. De oudste artefacten die in Vlaanderen met enige zekerheid gedateerd kunnen worden, zijn aangetroffen in een leemgroeve in Kesselt en gaan terug tot *Marine Isotope Stage*[^1] (MIS) 10 (ca. 390.000 B.P.), hoewel een oudere datering niet volledig kan worden uitgesloten[^2]. In onze gebieden duurt dat middenpaleolithicum wellicht tot zowat 35.000 jaar geleden. Uit het daaropvolgende jong- of laatpaleolithicum zijn in Vlaanderen bijzonder weinig sporen gekend. Eén enkele opgegraven site, in Kanne, kan hieraan met zekerheid worden toegeschreven[^3].

In de opwarmende laatste fase van de ijstijd is het grondegebied van het huidige Vlaamse gewest duidelijk wel bevolkt door finaalpaleolithische groepen[^4]. Het einde van het paleolithicum valt samen met het einde van de laatste ijstijd en het begin van het holoceen, zowat 11.600 jaar geleden.

Deze bijzonder lange periode in het pleistoceen wordt gekenmerkt door een afwisseling van ijstijden en tussenijstijden en daarmee gepaard gaande veranderingen in de natuurlijke omgeving. De '*afbakening in de ruimte*' vraagt dan ook wat toelichting.

Door uitbreiden van de poolkappen tijdens een ijstijd verdwenen enerzijds hele stukken land onder gletsjers (echter niet tot in het huidige Vlaanderen), maar kwamen anderzijds ook grote gebieden droog te liggen door het dalen van de zeespiegel, precies als gevolg van die ijsaccumulatie op de polen. Concreet bestond er bijvoorbeeld de meeste tijd een landbrug tussen het huidige vasteland en de Britse eilanden. Dit impliceert dat de 'afbakening in de ruimte' met enige flexibiliteit moet worden benaderd. We dienen er bijvoorbeeld rekening mee te houden dat ook in de territoriale zee en op het Belgische continentaal plat (BCP) nog paleolithische sites kunnen schuilgaan, zoals blijkt uit opgeviste geïsoleerde artefacten in steen, been en gewei in naburige regio's, evenals het lopende onderzoek op de Noordzee door de samenwerking van verschillende universiteiten en onderzoeksinstellingen[^5].

Tijdens de koudste fases van de ijstijden kon er door de afwezigheid van vegetatie vrij intensieve erosie plaatsvinden, maar anderzijds ook depositie in de vorm van eolische sedimenten (zand en loess). Naar de overgang naar de tussenijstijden zorgde het opwarmend klimaat enerzijds tot het vrijkomen van veel smeltwater (permafrost) met erosie tot gevolg, maar anderzijds ook depositie in de vorm van alluviale en colluviale afzettingen. In de uiteindelijk stabiele klimaatscondities van de interstadialen, zorgde de teruggekomen vegetatie voor een stabilisatie van landschapsoppervlakken met bodemvorming tot gevolg. Alles samen betekent dit dat het landschap doorheen deze cycli voortdurend veranderd is en dat de huidige kaarten of archeoregio's niet noodzakelijk representatief zijn voor de gehele tijdsperiode waarover ze uitspraak doen. Het impliceert ook dat heel wat sites aan erosieve processen onderhevig geweest moeten zijn, maar dat anderzijds diep begraven contexten, in het bijzonder onder de loess, binnen de Vlaamse vallei en in de huidige alluviale gebieden, nog heel wat potentieel te bieden hebben.

Naast het abiotische was ook het biotische landschap, onder invloed van de klimaatschommelingen, voortdurend in beweging. Bosgebieden met aangepast wild in een tussenijstijd maakten tijdens volle ijstijdperiodes plaats voor een poolwoestijn of een toendra met bijvoorbeeld mammoeten of

rendieren. Ook de mens moest zich als deelnemer in het ecosysteem op zijn beurt telkens aan die nieuwe leefomgeving aanpassen (of mee migreren). Concrete gegevens voor onderzoek naar het veranderende milieu komen vooral van de palynologie. Bijkomende paleo-ecologische informatie gebaseerd op dierlijk materiaal is nog bijzonder schaars. Algemeen kan men stellen dat onderzoek naar de biostratigrafie van deze periode in Vlaanderen tot hiertoe beperkt is gebleven, hoewel het afgelopen decennium er een opmerkelijke inhaalbeweging gestart is in verscheidene wetenschappelijke disciplines[^6].

Hoewel zowel (paleo)geografisch als paleo-ecologisch onderzoek essentieel zijn bij de studie van het paleolithicum nemen we in dit hoofdstuk enkel dat onderzoek mee dat een directe link heeft met de archeologische sites. Bij de voorstelling van het *tijdskader* past echter wel een korte schets van het paleomilieu.

Voor de archeologie van het paleolithicum in Vlaanderen zijn vooral de laatste drie ijs- en tussenijstijden van belang. Op een bepaald moment tijdens de koude fases behorend tot de Saale (MIS 10 tot en met MIS 6; 380.000 tot 128.000 geleden), rukte de noordelijke ijskap op tot in middenNederland en schuurde de Vlaamse Vallei uit tot op haar grootste diepte (tot 25 meter beneden het huidige zeepeil). Dit enorme valleistelsel omvatte alle huidige bijrivieren van de Schelde en voerde het water in een brede verwilderde rivier af via 'Gent' en 'Brugge' naar een veel verder afgelegen Noordzee.

Tijdens het Eemiaan (MIS 5e; 128.000 tot 112.000 jaar geleden), de (voor)laatste tussenijstijd, was het iets warmer en droger dan in het huidige interglaciaal. In dit gewijzigde ecosysteem pasten fauna en vegetatie zich aan. De zee drong binnen tot in de Vlaamse Vallei.

Het Weichseliaan (112.000 tot 11.650 jaar geleden) is tot nu toe de laatste ijstijd. In onze streken krijgt het landschap een toendra-vegetatie, in de meest koude fase zelfs een boomloze arctische steppe of poolwoestijn. De ijskap kwam maximaal tot in Denemarken, de zeespiegel lag dan tot 130 meter lager. De wind had vrij spel met het blootliggende sediment. Door intense noorderwinden werd het huidige Vlaamse gewest bedekt met dekzanden in het noorden en loess in het zuiden; het brede dal van de Vlaamse Vallei raakt gradueel voor de laatste keer volledig opgevuld. De dekzanden in het noorden hopen zich naar het einde van het glaciaal op tot een 4 meter hoge dekzandrug tussen 'Maldegem' en 'Stekene' die zorgde voor een afdamming van de natuurlijke noordelijke afvloei van het water. Het water kon initieel niet afstromen met de vorming van verschillende paleomeren langs de zuidelijke rand van de dekzandrug tot gevolg, waarvan de Moervaartdepressie veruit de grootste is. Maar het vond uiteindelijk een weg langs het noordoosten en zou voortaan via 'Antwerpen' en de huidige Oosterschelde het bekken van Maas en Rijn bereiken[^7].

Het laatste gedeelte van het Weichseliaan (14.650 tot 11.650 jaar geleden) wordt het tardi- of laatglaciaal genoemd. In deze fase, waarin op het grondgebied van het huidige Vlaamse gewest de oudste duidelijke bewijzen van aanwezigheid van de moderne mens verschijnen (archeologisch overeenkomend met het laat- en finaalpaleolithicum), begint de opwarming van het klimaat. Het laatglaciaal was een erg dynamische periode met snelle klimatologische veranderingen, en grote biodiversiteit. De rivieren gingen breed meanderen en zich insnijden en er werden grote rivierduinen gevormd. Tijdens de interstadialen lag de zomertemperatuur gemiddeld iets lager in vergelijking met het holoceen en raakte het open steppelandschap gradueel bebost met wilg en berk en later vooral den. De stadialen kenden een open landschap. Na de laatste felle koudeterugslag, tijdens de jonge dryas, met opnieuw steppevegetatie, volgt zowat 11.600 jaar geleden het eigenlijke begin van het holoceen.

## HISTORIEK VAN HET PALEOLITHISCH ONDERZOEK IN VLAANDEREN 

Terwijl het zuiden van België in de 19^de^ eeuw een belangrijke rol speelde in het internationale onderzoek van het paleolithicum en de paleoantropologie, vooral door vondsten en onderzoek door de universiteit van Luik en het Museum voor Natuurwetenschappen in grotsites (bijv. Engis en Spy voor Neanderthalers en het middenpaleolithicum, Chaleux en Goyet voor het laatpaleolithicum) en in het Hainebekken in Henegouwen, kwam het onderzoek van het paleolithicum in Vlaanderen in de eerste helft van de twintigste eeuw maar traag op gang. Ook dan was het vooral de Luikse school onder leiding van J. Hamal-Nandrin die uitstappen maakte naar openluchtsites in de Kempen, vooral in Lommel en Zonhoven. Deze vindplaatsen zouden lange tijd de belangrijkste bronnen blijven voor het paleolithicum in Vlaanderen.

J. Hamal-Nandrin was een industrieel die via de Luikse universiteit (o.a. M. De Puydt) geïnteresseerd raakte in de prehistorie en die in de eerste helft van de 20^ste^ eeuw een enorme collectie artefacten bijeen bracht (voor een overzicht zie C. Ophoven[^8]). Hij gaf de eerste Belgische cursus in prehistorische archeologie (Luik, 1926) en wordt beschouwd als de stichter van wat de *Ecole Liégeoise* is gaan heten, maar zijn manier van 'opgraven' is fel bekritiseerd[^9]. Hij schonk immers nauwelijks aandacht aan de context van het materiaal en haalde nooit het wetenschappelijke niveau van 19^de^-eeuwse onderzoekers als E. Dupont. Toch heeft J. Hamal-Nandrin een enorme stempel gedrukt op het Belgisch prehistorisch onderzoek in de eerste helft van de 20^ste^ eeuw. Aan de universiteiten in Vlaanderen kwam prehistorie toen niet aan bod en hoewel in 1903 bij de Koninklijke Musea voor Kunst en Geschiedenis de eerste Belgische Rijksdienst voor Opgravingen werd opgericht, had ook deze geen aandacht voor het paleolithicum.

Vanaf 1905 werden in Zonhoven vondsten gedaan die in een overgangsfase van het paleolithicum naar het mesolithicum werden geplaatst[^10] en vergeleken werden met magdaleniaan[^11] en tardenoisiaan[^12]. Het ging om oppervlaktemateriaal (40.000 stuks!) dat vaak tegen vergoeding was ingezameld door plaatselijke 'helpers' en dat aanvankelijk niet veel aandacht kreeg.

Na Zonhoven richtte J. Hamal-Nandrin zich een tijd op de Ardennen en Haspengouw, tot hij in 1934 het onderzoek in Lommel opstartte, nadat daar door verscheidene amateurs vondstmeldingen waren gedaan. In een vergelijkende studie plaatste hij het materiaal uit Lommel en Zonhoven in het aurignaciaan[^13]. Hoewel in Lommel voor de eerste keer ook echt werd gegraven, gebeurde dit opnieuw zonder enige aandacht voor de stratigrafische context. Het bleef een zoeken naar de stukken *an sich*. Tussen 1937 en 1939 werden op dezelfde manier ook in Zolder artefacten verzameld en toegewezen aan het aurignaciaan.

De publicatie van al het materiaal werd geleverd door C. Ophoven[^14], studente en assistente van J. Hamal-Nandrin. Zij beschreef afzonderlijk de gravettespitsen, stekers, boren en schrabbers, waarbij ze zonder voorbehoud aan deze klassen een zuiver functionele betekenis toekende. Evenmin werd de interpretatie van de sites in vraag gesteld. De gravettespitsen bewezen voor haar als gidsfossiel

zondermeer het bestaan van het aurignaciaan in de provincie Limburg[^15]. Intussen weten we dat het hier om materiaal van de *Federmesser*groepen[^16] ging.

Uit dit alles blijkt hoezeer in België de prehistorici en met name de *Ecole Liègeoise* lange tijd naar de Franse traditie bleven kijken. Het onderzoek bestond uit louter typologische vergelijkingen, gericht op het Franse paradigma[^17]. Deze onderzoekssituatie had tot gevolg dat de finaalpaleolithische sites in Vlaanderen aanvankelijk *a priori* onmogelijk bij noordelijke tradities konden aansluiten.

De visie om deze ensembles onder te brengen in de *federmesser*groepen (of het tjongeriaan) kwam bijgevolg pas na de Tweede Wereldoorlog, en wel uit Nederland[^18] en Duitsland^19^. Daar werd al vanaf de jaren 1930 veel aandacht geschonken aan de eigen stratigrafie en paleo-ecologie (ondermeer via pollenanalyses) en werd het vroege prehistorisch onderzoek bedreven vanuit diverse invalshoeken. Bij de verwerking werd bijvoorbeeld ook gewag gemaakt van 'etnologische vergelijkingen'. De tijdschriften waarin de prehistorisch publicaties in Nederland verschenen, respectievelijk van biologische, geografische en sociologische aard, reflecteren op treffende wijze de richtingen waarin de prehistorici zich daar al voor de Tweede Wereldoorlog oriënteerden en, vooral onder impuls van een eminent archeoloog als A.E. Van Giffen, een tijdlang toonaangevend waren in West-Europa. In Vlaanderen ontbrak tot dan zo een leidende figuur.

Hier bleef de discussie ook na de Tweede Wereldoorlog vooral gaan over cultuurhistorische toewijzingen. In een artikel waarin voor de eerste maal getracht werd de Limburgse finaalpaleolithische sites in hun stratigrafische en natuurlijke context te plaatsen, vergeleek J. de Heinzelin van het Museum voor Natuurwetenschappen het materiaal met het \"*Tardenoisien français, s\'allient au Tjongergroup neérlandais*\"[^19]. De tjongergroep moest daarmee als mesolithicum beschouwd worden. Angelroth[^20] daarentegen pleitte ervoor om de sites in verband te brengen met het perigordiaan, zoals dat in Frankrijk door Peyrony[^21] was gedefinieerd en situeerde de Vlaamse sites daarmee nog steeds exclusief in het Franse conceptuele kader. Ook de Brusselaar J. Verheyleweghen hield een krachtig pleidooi om ze daarin onder te brengen[^22]. Het perigordiaan zou daarbij gedurende het volledige jongpaleolithicum getuigd hebben van een opmerkelijke vitaliteit en verspreid zijn over Azië, Afrika, en Europa. J. Verheyleweghen toonde zich daarmee nog steeds een aanhanger van de oude Franse theorieën, voortvloeiend uit het ontstaan van de prehistorische archeologie vanuit de geologie, als zou er mondiaal een parallelle evolutie zijn vast te stellen (zie verder ook 'theoretisch kader').

Op zijn werkwijze kwam echter grondige kritiek van de Fransen zelf, bij monde van D. de SonnevilleBordes[^23]. Zij verweet J. Verheyleweghen de Franse jongpaleolithische typelijst foutief te hebben toegepast en onvoldoende op de hoogte te zijn van de klassieke perigordiaan- en magdaleniaansites. Volgens D. de Sonneville-Bordes[^24] maakte Lommel deel uit van het \"*grand complex de l\'Epimagdalénien*\", zoals dat in Noordwest-Europa was vastgesteld, verwant met de klassieke epipaleolitische en aziliaan industrieën in Frankrijk. Daarmee was het finaalpaleolithicum in Vlaanderen definitief geassocieerd met de *Federmesser*groepen en het aziliaan.

De belangrijkste bijdrage van het hernieuwd onderzoek in Lommel werd wellicht geleverd door het terreinwerk en de stratigrafische studie van F. Gullentops, die in associatie met de site een Usselobodem[^25] vaststelde^27^. Dergelijke directe associatie tussen finaalpaleolithisch materiaal en een laatglaciaal stratigrafisch niveau kon in Vlaanderen ook tot vandaag nog niet vaak worden geregistreerd.

Intussen waren aan de Vlaamse universiteiten ook de eerste leerstoelen in Nationale Archeologie opgericht. Verbonden aan de universiteit van Leuven begon J. Mertens, die eveneens verbonden was aan de Nationale Dienst voor Opgravingen, aan een indrukwekkende reeks opgravingen van de ijzertijd tot de middeleeuwen (geen steentijden), verbonden aan de Universiteit Gent profileerde S.J. De Laet zich als specialist in pre- en protohistorie, maar ook daar bleef het paleolithicum ondervertegenwoordigd. S.J. De Laet speelde wel een fundamentele rol in de verdere ontwikkeling van de prehistorische archeologie in Vlaanderen. Met zijn uitvoerige synthesewerken over de prehistorie van de Lage Landen[^26] bracht hij verspreide kennis bij elkaar. Door de prehistorie van Vlaanderen ook telkens samen te brengen met de inzichten uit het zuiden van België (en Luxemburg) en uit Nederland heeft het prehistorisch onderzoek hierdoor ongetwijfeld sterke impulsen gekregen.

S.J. De Laet was dan ook de eerste Belgische archeoloog na J. de Heinzelin die de Vlaamse finaalpaleolithische sites met het tjongeriaan associeerde. In zijn eerste (Engelstalig) overzicht van de prehistorie in de Lage Landen, nam hij voor de \"*Tjonger group*\" de sites over van Bohmers[^27], waaronder dus ook Lommel en Zolder[^28]. Ook Zonhoven werd met de tjongergroep in verband gebracht, zij het als uitzonderlijk site, waarin ook microlieten waren aangetroffen. De tjongergroep zou volgens De Laet het resultaat zijn van een tweede invasie in de Noordwest-Europese vlakte, afkomstig uit het Engelse creswelliaan. Verwantschap met het aurignaciaan zou ten onrechte zijn gezocht door \"*typologicallyminded archaeologists*\"[^29]. Met deze visie sloot De Laet[^30] zich grotendeels aan bij Bohmers[^31] en Schwabedissen[^32].

In de Nederlandstalige en uitgebreide versie van zijn synthesewerk werd dit bevestigd en verder uitgewerkt. Op basis van oude collecties van het Gruuthuse Museum in Brugge vulden De Laet en Glasbergen[^33] de inventaris verder aan met de sites Kemmelberg, Sint-Kruis en Steenbrugge (prov. West-Vlaanderen).

Daarmee was het finaalpaleolithicum ook in Vlaanderen definitief erkend. In de jaren 1960 konden er nog een aantal nieuwe vondsten aan toegevoegd worden, meer bepaald de sites van Merksplas[^34], Huise[^35], en Mol[^36]. Alleen op deze laatste site werden ook enkel coupes bestudeerd. Een Usselo bodem[^37] kon echter niet worden vastgesteld.

De site van Mol vormde, aangevuld met eigen studie van nog niet gepubliceerde collecties, ook het onderwerp van een synthetisch onderzoek over de tjongerkultuur in België door F. Van Noten^40^. Naast de al boven aangehaalde sites en het hierna besproken site Meer I, voegde hij in dit overzicht de nieuwe vindplaatsen Balen-Keiheuvels, Brasschaat-Driehoek (Ankerhof) en Brasschaat-Pompstation

Pidpa toe. Deze ensembles waren in openbare, zowel als in privécollecties teruggevonden, helaas zonder enige referentie naar de terreingegevens. Bij 'waarschijnlijke sites' vinden we voor Vlaanderen Zolder, Balen-Nethe (Munitiefabriek), Brasschaat-Bosduin, Gierle, Holsbeek-de Wing, Huise, Mendonk, Overpelt, Ravels en Wachtebeke terug. Hier beschikte F. Van Noten over zeer weinig en vaak gemengde gegevens, waardoor het grootste voorbehoud moet worden in acht genomen.

In 1966 startte F. Van Noten, met de steun van de Nationale Dienst voor Opgravingen zijn onderzoek op de Meirberg in Meer. Al in 1963 en 1964 was hier door A. Goossens opgegraven op een door zandwinning bedreigd terrein. Het materiaal uit deze beide opgravingen werd samen met dat van vroegere oppervlaktevondsten bestudeerd en gepubliceerd, met voor het eerst aandacht aan de horizontale verspreiding van het materiaal en aan de betekenis van de verschillende kuilen[^38]. Uit verspreide partikels uit de sleuven en uit één van die kuilen werd voor het eerst ook houtskool bemonsterd voor ^14^C-dateringen. Door de verrassend jonge ouderdom hiervan werd meteen de problematiek aangesneden rond problemen met absolute dateringen op de zandgronden.

We kunnen stellen dat het dus tot ver in de jaren 1960 heeft geduurd vooraleer er een behoorlijke opgraving plaatsvond van een paleolithische site in Vlaanderen. Vanaf 1967 begon F. Van Noten zijn onderzoek op Meer II[^39] wat de aanzet was tot nieuwe gegevens en vooral tot nieuwe interpretaties. Met de medewerking van D. Cahen, L Keeley en J. Moeyersons groeide dit uit tot een internationaal project dat vooral bekendheid verwierf door de combinatie van refitting, gebruikssporenanalyse en ruimtelijk onderzoek, waardoor een dynamisch beeld ontstond van activiteiten die zich in de kampplaats hadden afgespeeld[^40]. De benadering (door Van Noten wat ambitieus 'paleo-ethnografie' gedoopt) kreeg heel wat weerklank in de internationale literatuur. Later zou ze ook worden toegepast op nieuw terreinwerk in Meer IV[^41], maar ondanks zware investeringen in opgravingen en verwerking raakte deze sector nooit gepubliceerd.

Intussen was onder promotorschap van F. Gullentops ook aan de K.U. Leuven onderzoek in de steentijden opgestart. P. Vermeersch richtte er begin jaren 1970 het Laboratorium voor Prehistorie op en verrichtte aanvankelijk eerder kleinschalige opgravingen op finaalpaleolithische sites, ondermeer in Helchteren-Sonnisse Heide[^42], Zolder-Terlamen[^43], Harelbeke-Gavermeersen[^44] en Achel-De Waag[^45]. Speciale aandacht ging daarbij naar de problematiek van de verticale spreiding van artefacten in de bodem[^46], een onderwerp dat heel wat belangstelling is blijven krijgen[^47].

Tot hiertoe uniek in Vlaanderen is de opgraving door de KULeuven in 1978 van de laatpaleolithische magdaleniaansite van Kanne[^48]. Het betreft nog steeds de enige gekende, goed bewaarde magdaleniaansite in Vlaanderen. Ook hier werd refitting en ruimtelijke analyse toegepast.

Vanaf de jaren 1980 kwam ook het middenpaleolithicum voor het eerst ernstig aan bod, eerst met het onderzoek van opgespoten vondsten uit het oostelijk deel van de Vlaamse Vallei[^49], daarna ook met echte opgravingen, in Kesselt[^50] en in Vollezele-Congoberg^54^. Tot dan toe was het middenpaleolithisch

onderzoek in Vlaanderen beperkt gebleven tot kleine opgravingen op de Kluisberg in Ruien door J. de Heinzelin in 1949 en 1956 (Oost-Vlaanderen, op de taalgrens).

Ook aan de UGent kwam in de jaren 1980 paleolithisch onderzoek op gang, eerst onder invloed van J. Vanmoerkerke die op korte tijd verschillende opgravingen opstartte, onder meer op de finaalpaleolithische site Klein-Sinaai Baudeloo-Abdij[^51] en in Adegem "Berlaars". Daarnaast werden in deze periode de eerste contacten gelegd met verschillende amateurarcheologen, die soms een zeer aanzienlijke steentijdcollectie bezaten.

Voor het finaalpaleolithicum valt in de jaren 1980 vooral het onderzoek op de *Federmesser*-site van Rekem te melden, tot hiertoe nog steeds de grootste opgraving in Vlaanderen op een paleolithische vindplaats. De site op de rand van de Maasvallei werd opgegraven onder leiding van R. Lauwers[^52] en daarna grondig uitgewerkt tot een uitgebreide publicatie[^53]. Het project te Rekem was een samenwerking tussen de KULeuven en het Instituut voor het Archeologisch Patrimonium (IAP).

Deze Vlaamse wetenschappelijke instelling was in 1991 opgericht als opvolger van de Nationale Dienst voor Opgravingen, die zelf nooit activiteiten in de paleolithische archeologie heeft ontwikkeld. In het oprichtingsbesluit van het IAP werd naast een afdeling 'Historische tijden' wel een afdeling 'Prehistorie' voorzien. Hoewel deze afdelingen in de praktijk nooit operationeel zijn geworden en vooral de archeologie van de historische periodes is uitgegroeid, kunnen we stellen dat in Vlaanderen in de jaren 1990 voor het eerst de overheid zelf initiatief heeft genomen in onderzoek naar het paleolithicum. Het karteren en waarderen van het sitecomplex Meer-Meirberg, de eerste beschermde paleolithische site in Vlaanderen (1993) was daarbij één van de eerste eigen projecten[^54]. De methodologie die hier werd ontwikkeld zou de aanzet vormen voor nieuwe waarderingsprojecten in de jaren daarna.

In de jaren 90 vallen verder met betrekking tot terreinwerk nog de opgravingen van de KULeuven op de Ahrensburgsite in Zonhoven te vermelden[^55], waar eveneens refitting is toegepast, maar waarvan de resultaten pas in 2015 gepubliceerd werden. Daarnaast zijn in Weelde talrijke finaalpaleolithische sites in akkerland opgegraven[^56] grotendeels in het kader van een Ruilverkaveling, waarvoor voor het eerst het principe 'de veroorzaker betaalt' werd toegepast in paleolithisch onderzoek.

Belangrijk terreinonderzoek van jagers-verzamelaar in de jaren 1990 vond plaats in Zandig Vlaanderen. In het kader van het project *Archeologische Inventaris Vlaanderen* werden verschillende archeologiestudenten in de jaren 1980-1990 aangespoord om één prefusiegemeente archeologisch door te lichten. Daarbij namen ze niet alleen de gepubliceerde resultaten mee, maar contacteerden ze ook amateurarcheologen en voerden ze veldkarteringen uit. Een eerste evaluatie van het potentieel van Zandig Vlaanderen kwam er door het onderzoek van P. Crombé[^57]. Hij maakte een doorlichting van de bekende steentijdvindplaatsen in Zandig Vlaanderen met de klemtoon op het finaalpaleolithicum en mesolithicum. Tot dan toe was de informatie meer verspreid gebleven. In het kader van zijn onderzoek naar de typochronologie en de sitestructuur onderzocht P. Crombé ook de finaalpaleolithische site Maldegem. Bijzonder aan deze vindplaats was de aanwezigheid van blanchèrespitsen, een spitstype dat in de laatste fase van het finaalpaleolithicum thuishoort, een periode die bijzonder slecht gekend is. Daarnaast initieerde hij in het kader van de preventieve opgravingen te Verrebroek (zie hoofdstuk mesolithicum) interdisciplinair onderzoek van diverse laatglaciale-vroegholocene bodemsequenties (14C, pollen, macroresten, houtskool, micromorfologie,

enz.)[^58]. Bij controle van de graafwerken kwam ook een paleobodem aan het licht met daarin de resten van een zeer kleine vuursteenconcentratie[^59]. Verdere controle van de profielwanden, het zetten van een aantal proefsleuven en proefvakken leverde een goed beeld op van het landschap ten tijde van het laatglaciaal maar geen verdere artefacten. Ook de controle van de graafwerken bij de bouw van een containergetijdendok, het zogenaamde Deurganckdok in Doel tijdens dezelfde periode bracht verschillende finaalpaleolithische sites aan het licht[^60].

Ook het middenpaleolithicum kreeg in de jaren 1990 verdere aandacht, met publicatie van prospectievondsten door de UGent[^61], opgravingen in Oosthoven door de KULeuven[^62] en de start van terreinwerk in de leemgroeve van Veldwezelt[^63], eveneens door KULeuven, met steun van het IAP. Diverse academische onderzoekscampagnes hebben geleid tot het in kaart brengen van een bijzondere rijkdom aan goed bewaarde, afgedekte vindplaatsen zowel te Veldwezelt als te Kesselt waar in de jaren 2000 verschillende opgravingscampagnes plaatsvonden. Twee doctoraatsonderzoeken brachten nieuwe inzichten in de diachronische aanwezigheid van middenpaleolithische ensembles in de loess in dit gebied die o.m. betrekking hadden op lithische technologie en variabiliteit, grondstofgebruik als de organisatie en functie van nederzettingen[^64].

Zoals boven aangehaald lag de focus vanuit het IAP, later het VIOE, in de jaren 2000 vooral op inventarisatie, prospectie, kartering en waardering van finaalpaleolithische sites, hoofdzakelijk in de Kempen[^65]. Deze onderzoekscampagnes brachten een aantal goed bewaarde, uitgestrekte sitecomplexen aan het licht met zowel finaalpaleolithische als mesolithische vindplaatsen, zoals bijvoorbeeld het sitecomplex De Liereman[^66], dat tevens sinds 2013 een archeologische bescherming kreeg. Daarnaast werd tussen 2003 en 2008 opnieuw opgravingscampagnes op de paleolithische site waar ooit het eerste graafwerk is begonnen, met name de Maatheide in Lommel, opgestart[^67].

Onder impuls van de UGent vond sinds de jaren 2000 systematisch prospectief en vlakdekkend onderzoek plaats naar finaalpaleolithische en mesolithische vindplaatsen in Zandig Vlaanderen. Onderzoek naar de afgedekte finaalpaleolithische en mesolithische vindplaatsen te Verrebroek en Doel resulteerden o.m. in een doctoraat gericht op de technologische aspecten van de lithische materiaal, dit aan de hand van een attributenanalyse en (beperkte) refittingstudie[^68]. Tevens werd gefocust op de optimalisatie van prospectiemethodes, met name gericht op afgedekte vindplaatsen in de midden- en benedenloop van de Schelde[^69]. Deze studies richtten zich met name op de toepassing van systematisch booronderzoek in een vast grid en het nat uitzeven op een fijne maaswijdte van de boormonsters als succesvolle methode om dergelijke vindplaatsen in kaart te brengen. Een derde onderzoeksthema richtte zich op de Moervaartvallei. De regio was reeds langer gekend omwille van de aanwezigheid van talrijke vindplaatsen die zich op de noordrand van de depressie lijken te concentreren. Deze werden door middel van jarenlange prospectie, voornamelijk uitgevoerd door vrijetijdsarcheoloog Luc Van Vlaenderen, in kaart waren gebracht^74^. Door UGent, maar ook door het toenmalige VIOE werd de afgelopen decennia zowel landschappelijke als archeologische boringen, geofysisch onderzoek, gedetailleerd paleo-ecologisch onderzoek (gekoppeld aan een extensief ^14^Cdateringsprogramma) uitgevoerd en nieuwe inzichten in de landschapsevolutie en bewoning

verkregen.[^70] De Moervaartdepressie gaat terug op een ondiep laatglaciaal meer. Aan de westkant van de depressie getuigen verschillende opgevulde geulen van een anastomoserend[^71] netwerk aan waterlopen. Er bevinden zich opvallend veel federmesservindplaatsen op de noordrand van het toenmalige meer, evenals op de duinruggen en de randen van de geulen in het westen. Op basis van de recentste inzichten lijkt het erop dat de menselijke aanwezigheid grotendeels verdween wanneer het meer begon op te drogen op het einde van de Allerød en daaropvolgende koude Jonge Dryas.

Ondertussen vond in Vlaanderen een verschuiving plaats richting Malta-onderzoek. Sinds 1993 liet het archeologiedecreet toe om binnen het kader van grootschalige ontwikkelingen preventief archeologisch onderzoek te verrichten volgens het 'veroorzakers'-principe. Terwijl dergelijk onderzoek eind de 20^ste^ eeuw voornamelijk nog door overheden en wetenschappelijke instellingen werd uitgevoerd, zet de liberalisering en opkomst van commerciële uitvoerders zich vanaf het begin van de 21^ste^ eeuw in. De keuze waar en op welke wijze preventief onderzoek dient te gebeuren lag echter nog steeds in handen van het toenmalige VIOE (later Agentschap Onroerend Erfgoed). Het resulteert in een stelselmatige toename aan archeologische onderzoek. Steentijdonderzoek werd echter lange tijd onderbelicht, waarbij vindplaatsen vaak per toeval aan het licht kwamen. In een aantal gevallen werd weliswaar overgeschakeld naar een aangepaste methodiek (bijvoorbeeld op de finaapaleolithische vindplaatsen te Tongeren-Plinius[^72], Gent-Tweekerkenstraat[^73] en recent te Ruien-Rosalinde[^74]), maar vaker werd lithisch materiaal enkel als losse vondst ingezameld. Uitzondering hierop waren de onderzoeken in het kader van grootschalige waterbeheersingswerken en de uitbreiding van de Antwerpse haven op linkeroever waar systematische en interdisciplinair onderzoek gericht op afgedekte vindplaatsen vanaf het finaalpaleolithicum werd uitgevoerd door respectievelijk het toenmalige VIOE en UGent/Gate. Dit onderzoek richtte zich op de Benedenschelde en zijn bijrivieren (Dijle, Durme en Zenne) waarbij aan de hand van geoarcheologisch onderzoek het laatglaciaal en holoceen landschap en de bewoningsgeschiedenis in kaart werden gebracht[^75].

Met het invoege treden van het hoofdstuk archeologie van het onroerenderfgoeddecreet in 2016, voltrok zich een verdere opschaling en liberalisering van het preventieve onderzoek.[^76] Tegelijkertijd zien we de afgelopen jaren stilaan een toenemende aandacht voor steentijdonderzoek binnen dat traject. Dit lijkt het resultaat te zijn van voortschrijdend inzicht zowel bij de controlerende overheden als bij de uitvoerders. Een recente screening van archeologienota's en nota's[^77], evenals de evaluatierapporten opgesteld door het Agentschap[^78], maakt echter duidelijk dat in vergelijking met onderzoek gericht op jongere periodes (zogenaamde 'sporenarcheologie') steentijdonderzoek nog steeds een heel klein percentage van het vooronderzoek vertegenwoordigt. Voor de periode 20162019 gaat het om 8% voor gerichte steentijdprospecties, terwijl voor 49% van de dossiers een proefsleuvenonderzoek werd opgestart gericht op sporenvindplaatsen. Bovendien blijken de aangewende selectiecriteria sterk te verschillen en zijn ze soms weinig onderbouwd, wat leidt tot heel wat verschillen in de manier waarop met steentijdwaardes wordt omgegaan^84^. Bovendien lijkt het

onderzoek zich voornamelijk te richten op niet-afgedekte vindplaatsen vanaf het finaalpaleolithicum die vaak op eenzelfde manier worden benaderd als potentiële mesolithische vindplaatsen. Terwijl aandacht voor oudere periodes of begraven contexten eerder beperkt lijkt. Hiervoor zijn verschillende verklaringen. Mogelijk heeft het te maken met de beperkte expertise bij de heel diverse groep van uitvoerders die momenteel actief is in het archeologische werkveld. Kennis omtrent het potentieel aan paleolithische vindplaatsen in Vlaanderen en waar die te zoeken, ontbreekt enerzijds vaak. Anderzijds botst de complexiteit en interdisciplinaire aanpak die een dergelijk onderzoek vaak noodzaakt met de continue druk op de kostprijs en snelheid die door de liberalisering in de hand wordt gewerkt. Een steentijdtraject wordt dan vaak gezien als extra belastend en de druk op uitvoerders om het steentijdpotentieel te minimaliseren hoog. Deze problematiek beperkt zich niet enkel tot het preventief onderzoek van paleolithische vindplaatsen, maar geldt ook voor jongere steentijdvindplaatsen (voor een uitgebreide discussie verwijzen we naar hoofdstuk 2 van het hoofdstuk mesolithicum). Onderhavige tekst zal duidelijk maken dat er omtrent het paleolithisch potentieel in Vlaanderen nog heel wat kennishiaten en opportuniteiten tot kenniswinst bestaan, o.m. met betrekking tot de aanwezigheid van goed bewaarde, afgedekte contexten en hoe deze opgespoord kunnen worden. Dit zijn aspecten waaraan recent onderzoek vanuit academische hoek tracht tegemoet te komen. Zo heeft KU Leuven het *Flemish Valley Survey Project* opgestart dat zich richt op middenpaleolithische vindplaatsen in de oostelijke Vlaamse vallei[^79], terwijl vanuit UGent een onderzoeksproject is opgestart naar de aanwezigheid van finaalpaleolithische vindplaatsen in de rivierduinen binnen de Scheldevallei[^80]. Een tweede belangrijk kennishiaat dat sinds kort meer aandacht krijgt, en die eigenlijk qua problematiek enigszins aansluit hierbij, is het onderzoek naar paleolithische bewoning in het kustgebied (kustpolders, duinen/strand en subtidale zone)[^81].

## OVERZICHT VAN ACTUELE ONDERZOEKERS 

De trend die in de onderzoeksbalans uit 2008 reeds werd opgemerkt, heeft zich in de afgelopen jaren verdergezet. Er heeft een duidelijke verschuiving plaatsgevonden waarbij archeologisch veldwerk tegenwoordig bijna uitsluitend door de commerciële sector in het kader van projecten wordt uitgevoerd. De onderzoekers binnen de projectarcheologie hebben hierbij vaak slechts ruimte en middelen voor een basisverwerking van de materiële resten. Toch zien we dat personen en instanties met expertise voor wetenschappelijke begeleiding geconsulteerd worden. Gedetailleerde uitwerking (uitgebreide technologische analyse, grondstof-, refit- en gebruikssporenonderzoek) en kadering binnen een groter geheel blijven grotendeels het domein van wetenschappelijke instellingen en hun onderzoekers. In de Vlaamse commerciële archeologie, maar ook in de (inter)gemeentelijke, stedelijke of provinciale archeologische diensten, is namelijk nog steeds te weinig actieve expertise in paleolithisch onderzoek. Voorheen was deze expertise ook sterk persoonsgebonden. Iedere vorser had een vrij uitgesproken voorkeur voor een specifieke periode. Tegenwoordig is het onderzoek noodzakelijkerwijs voornamelijk regiogebonden geworden.

Vanuit museuminstellingen wordt momenteel weinig paleolithisch onderzoek uitgevoerd in Vlaanderen, hoewel een groot aantal over belangrijke collecties beschikt (bijv. KMKG, met materiaal van Lommel, Meer, etc.) en vroeger wel degelijk in Vlaanderen actief waren (bijv. Koninklijk Museum voor Midden-Afrika in Meer). Ook regionale musea beheren paleolithische collecties (bijv. GalloRomeins Museum in Tongeren, Vleeshuismuseum in Antwerpen), maar doen er in de regel geen onderzoek op. De enige uitzondering hierop vormt De Kolonie, Archeologisch en Historisch Museum in Lommel, waar Ferdi Geerts actief is rond het paleolithicum in de regio.

Terwijl het Vlaams archeologisch werkveld een hele metamorfose kende, bevindt de paleolithische expertise zich nog grotendeels binnen universiteits- en overheidsinstellingen.

Expertise in het **vroeg- en middenpaleolithicum** ligt nog steeds voornamelijk bij de onderzoeksgroep van de Eenheid Prehistorische Archeologie van de KULeuven, onder leiding van Philip Van Peer. Onder meer Els Meirsman, Karen Ruebens en Ann Van Baelen publiceerden in de afgelopen jaren resultaten van vroeg- en middenpaleolithisch onderzoek. Daarnaast maakte ook Kévin Di Modica, eerst verbonden aan de Universiteit vna Luik en later bij het *Centre archéologique de la grotte Scladina* overzichtswerken over het middenpaleolithicum in België. Occasioneel worden ook aan de UGent middenpaleolithische vondsten gepubliceerd door de Sectie Pre- en Protohistorie onder leiding van Philippe Crombé (o.a. Hans Vandendriessche). In de afgelopen ca. 15 jaar rondden enkelen met succes doctoraatsverhandelingen en masterthesissen met een (vroeg-/)middenpaleolithisch onderwerp af: het gaat meer specifiek om Ann Van Baelen (KULeuven)[^82], Glenn De Nutte (KULeuven)[^83] en Hans Vandendriessche (UGent)[^84].

De overgrote meerderheid van de kennis over het **laat- en** **finaalpaleolithicum** is ontwikkeld aan de UGent, onder leiding van Philippe Crombé. Hans Vandendriessche verdedigde er in 2021 met succes zijn doctoraatsverhandeling over de technologische aspecten tijdens het laatglaciaal/vroegholoceen in de Scheldevallei. Verschillende vorsers die aanvankelijk verbonden waren aan de universiteit zijn nu werkzaam in de privé-archeologie: Joris Sergant en Machteld Bats voerden archeologisch onderzoek uit onder GATE bv, Yves Perdaen onderzocht in de afgelopen jaren onder BAAC Vlaanderen vindplaatsen met o.a. finaalpaleolithische fases. Ook Marijn Van Gils (OE), Marc De Bie (VUB) en Ferdi

Geerts (Erfgoed Lommel vzw) leverden belangrijke bijdrages. Occasioneel komt het laat- en finaalpaleolithicum ook aan bod bij Pierre Vermeersch, Philip Van Peer, Els Meirsman en Bart Vanmontfort (KULeuven).

Naast de eerder periodegebonden expertise vallen enkele vorsers op door hun **expertise op gerelateerde vlakken**. Zo zijn Luc Allemeersch (GATE bv), Johanna A. A. Bos (ADC-projecten), Annelies Storme (UGent/Gate), Jeroen Verhegge (UGent/Gate) en Philippe De Smedt (UGent) gespecialiseerd in de reconstructie van laatglaciale en vroegholocene landschappen. Verder verdienen ook de amateurarcheologen Van Vlaenderen, De Bock en De Meireleir een eervolle vermelding voor hun expertise van de steentijdoppervlaktevondsten in de Moervaartdepressie en het Waasland.

Wanneer de wetenschappelijke output tussen 2007-2019 wordt bekeken, is er nog steeds een overwicht aan publicatie in de vorm van tijdschriftartikels, congrespapers, thesissen en boek(del)en (n=95; 62,8 %). Binnen deze groep is voornamelijk Philippe Crombé dominant als eerste auteur, met 18 publicaties als eerste auteur. Onderzoekers als eerste auteur met meer dan twee publicaties in de afgelopen jaren zijn Ann Van Baelen, Marijn Van Gils, Hans Vandendriessche, Johanna A. A. Bos, Kévin Di Modica en Bart Vanmontfort.

De overige ca. 37 % van de output van de afgelopen jaren wordt ingenomen door rapporten (n=58). Aangezien het bij de overgrote meerderheid over rapporten met een (korte) vondstmelding gaat of de eerste auteur vaak niet de onderzoeker van het materiaal is, zou bovenstaande oefening zoals bij de andere wetenschappelijke publicaties geen indicatie van actuele onderzoekers weerspiegelen.

[^1]: Chronostratigrafische opdeling waarbij de wisselende verhoudingen van isotopen van zuurstof binnen diepzeekernen worden gebruikt als proxies voor klimatologische schommelingen.
[^2]: Meijs *et al.* 2012; Van Baelen *et al.* 2007, 19-26.
[^3]: Vermeersch *et al.* 1985, 17-54.
[^4]: De Bie 1998, 818-823.
[^5]: Cf. het "[[Europe's Lost Frontiers]{.underline}"](https://lostfrontiers.teamapp.com/)-project; Missiaen *et al.* 2018; Pieters *et al.* 2020.
[^6]: e.g. Crombé *et al.* 2013; Meylemans *et al.* 2013.
[^7]: De Moor & Heyse 1974; Verbruggen *et al.* 1996; Bats *et al.* 2010; Crombé *et al.* 2013 & 2020; Bos *et al.* 2017; 2018a & b.
[^8]: Ophoven 1943, 181-188.
[^9]: Otte *et al.* 1984, 105-126.
[^10]: Cf. Hamal-Nandrin & Servais 1919, 202-225.
[^11]: laatpaleolithische cultuur die vanuit Zuidwest-Europa zich verspreidde naar Centraal- en West-Europa en grosso modo kan gedateerd worden tussen 17000 en 14000 BP.
[^12]: Vroegmesolithische traditie (technocomplex?) die voorkomt in West-Europa en zich o.m. kenmerkt door trapeziumvormige pijlpunten. Begin 20^ste^ eeuw (en in feite nog tot in het laatste kwart van de 20^ste^ eeuw) werd deze nog als finaalpaleolithisch beschouwd.
[^13]: Hamal-Nandrin & Servais 1935, 175-203. Het aurignaciaan is een laatpaleolitische cultuur die zowel in het Midden-Oosten als Europa voorkomt en in onze contreien dateert tussen 35.000 en 29.000 BP.
[^14]: Ophoven 1938, 90-105; Ophoven 1939, 454-465; Ophoven 1943, 181-188; Ophoven 1947, 91-96.
[^15]: Ophoven 1938, 90-105.
[^16]: Een finaalpaleolithische cultuur die chronologisch vanaf de Oude Dryas (13.900 BP -- 14.000 BP), maar voornamelijk met het Allerød interstadiaal (12.850 BP -- 13.900 BP) worden geassocieerd.
[^17]: Lange tijd werd de Franse indeling van de prehistorie in Vlaanderen als dé referentie beschouwd. De onderliggende opvatting, geënt op het biologisch evolutionisme, was dat er over de hele wereld een gelijkaardige algemene opeenvolging in de prehistorische materiële cultuur had plaatsgevonden.
[^18]: Bohmers 1947, 129-201. ^19^ Schwabedissen 1954.
[^19]: De Heinzelin 1949, 1-18.
[^20]: Angelroth 1956, 26-30.
[^21]: Peyrony 1933, 543-559.
[^22]: Verheyleweghen 1956, 179-258.
[^23]: De Sonneville-Bordes 1961, 421-443.
[^24]: De Sonneville-Bordes 1961, 421-443.
[^25]: Bodem die zich ontwikkelde tijdens het Allerød-interstadiaal (ca. 13.900 tot 12.850 jaar BP) ^27^ Gullentops 1956, 54-62.
[^26]: De Laet 1958; De Laet 1974; De Laet 1979; De Laet 1982.
[^27]: Bohmers 1947, 129-201.
[^28]: De Laet 1958.
[^29]: De Laet 1958.
[^30]: De Laet 1958.
[^31]: Bohmers 1947, 129-201.
[^32]: Schwabedissen 1954.
[^33]: De Laet & Glasbergen 1959.
[^34]: Janssens 1965, 169-182.
[^35]: De Laet 1963, 235-241.
[^36]: De Heinzelin & Spitaels 1962.
[^37]: Bodem die zich ontwikkelde tijdens het Allerød-interstadiaal (ca. 13.900 tot 12.850 jaar BP). ^40^ Van Noten 1963; Van Noten 1967a, 197-236.
[^38]: Van Noten 1967b.
[^39]: Van Noten 1967b; Van Noten 1968; Van Noten 1978.
[^40]: Cahen *et al.* 1979, 661-672; Cahen *et al.* 1980, 209-259; Cahen & Keeley 1980, 166-180.
[^41]: Nijs 1986a, 95-102; Nijs 1986b; Nijs 1990, 493-506, 10fig.
[^42]: Vermeersch 1974.
[^43]: Vermeersch & Carolus 1975, 163-176.
[^44]: Vermeersch 1976, 33-71.
[^45]: Vermeersch 1979, 117-129.
[^46]: Vermeersch 1979, 117-129.
[^47]: Vermeersch 1999, 159-166; Vermeersch 2006, 297-303; Bugel 2003, 39-44.
[^48]: Vermeersch *et al.* 1985, 17-54.
[^49]: Van Peer 1982a, 238-254; Van Peer 1982b; Van Peer 1986, 157-176.
[^50]: Lauwers & Meijs 1985, 123-129. ^54^ Vynckier *et al.* 1988, 133-140.
[^51]: Vanmoerkerke & De Belie 1984, 1-13.
[^52]: Lauwers 1985b, 7-12; Lauwers 1985c, 135-136; Lauwers 1985d, 43-50; Lauwers 1986a, 33-42; Lauwers 1986b, 9-14; Lauwers 1988, 217-234.
[^53]: De Bie 1988; Caspar & De Bie 1996, 437-460; De Bie & Caspar 2000.
[^54]: De Bie 2000.
[^55]: Peleman *et al.* 1994, 73-80; Vermeersch 2015.
[^56]: Van Peer 1979, 1-10; Verbeek 1999.
[^57]: Crombé 1996; Crombé 1998b, 29-40.
[^58]: Crombé 2005.
[^59]: Crombé *et al.* 1999b, 63-68; Perdaen & Ryssaert 2002, 75-81.
[^60]: Crombé & Verbruggen 2002, 165-180.
[^61]: Crombé & Van der Haegen 1994c, 103-130.
[^62]: Van Peer & Verbeek 1994, 3-11.
[^63]: Vanmontfort *et al.* 1998, 5-11.
[^64]: Bringmans 2006, Van Baelen 2014.
[^65]: Van Gils & De Bie 2001, 77-78.
[^66]: S.N. https://id.erfgoed.net/erfgoedobjecten/140136 (geraadpleegd op 26 maart 2021).
[^67]: De Bie & Van Gils 2004, 13-21; De Bie & Van Gils 2006a, 188-119, Geerts *et al.* 2008.
[^68]: Perdaen 2004.
[^69]: Bats *et al.* 2006; Crombé 2006; Crombé & Verhegge 2015; De Clercq *et al.* 2012; Verhegge *et al.* 2018; Verhegge *et al.* 2021. ^74^ Ameels & Van Vlaenderen 1995; Van Vlaenderen *et al.* 2006.
[^70]: Crombé & Verbruggen 2002, 165-180; Ameels & Van Vlaanderen 1995, 35-44; Crombé 2020; Bats *et al.* 2009; Bats *et al.* 2010; Crombé *et al.* 2013; Meylemans *et al.* 2011a & b.
[^71]: Verwilderd of vlechtend rivierenstelsel, waarbij de rivier bestaat uit een netwerk van meerdere ondiepe waterlopen die zich herhaaldelijk splitsen en weer samenvoegen.
[^72]: Bink 2007.
[^73]: Ryssaert *et al.* 2003.
[^74]: Verbrugge *et al.* 2012 & 2021.
[^75]: Meylemans *et al.* 2013; Jacops *et al.* 2010; Verhegge *et al.* 2018; Verhegge *et al.* 2021; Verhegge & Delvoie 2021.
[^76]: Deze wetgeving hanteert nog steeds het 'verstoordersprincipe'. Belangrijke wijzigingen omvatten o.m. de erkenning van de uitvoerders, het vastleggen van minimale oppervlaktecriteria voor het opstarten van een archeologisch traject en in dat geval de noodzaak tot een archeologienota bij het indienen van een omgevingsvergunning. De afweging of een (voor)onderzoek dient uitgevoerd te worden ligt sindsdien in handen van de erkend archeoloog, terwijl het agentschap Onroerend Erfgoed een stap terugzet en enkel nog akte neemt van de dossiers.
[^77]: Van Baelen & Noens in voorbereiding.
[^78]: Evaluatierapporten verschijnen jaarlijks op de websit[e [Publicaties \| Onroerend Erfgoed]{.underline}](https://www.onroerenderfgoed.be/publicaties?f%5B0%5D=publication_type%3A57) (geraadpleegd op 2 juli 2021). ^84^ Voor een uitgebreide discussie verwijzen we naar de reeds vermelde studie van Noens 2018 & 2019, evenals Van Baelen & Noens in voorbereiding. Deze problematiek komt eveneens aan bod in het hoofdstuk mesolithicum.
[^79]: Van Peer 2020; Van Peer *et al.* 2017.
[^80]: Postdoctoraal onderzoek P. Pincé.
[^81]: Missiaen *et al.* 2018; Pieters *et al.* 2020.
[^82]: Van Baelen 2014.
[^83]: De Nutte 2008.
[^84]: Vandendriessche 2009.
