# BALANS VAN ONDERZOEKSVRAGEN EN INTERPRETATIES 

## INLEIDING 

Bij het opstellen van de vorige versie van de onderzoeksbalans werd gesteld dat om dit overzicht enigszins objectief te kunnen onderbouwen, opnieuw een analyse van de bibliografie aan de orde was. Men merkte op dat de trefwoorden die gekozen werden in functie van deze nulversie van de onderzoeksbalans (ecologie, economie, materiële cultuur, sociale structuren, geestesleven), niet allemaal even goed van toepassing op het onderzoek van het paleolithicum en dus een relevante analyse in de weg staan. Onderzoeksvragen die daar aan de orde zijn sluiten meer aan bij thema's als technologie, functionaliteit, nederzettingsdynamiek, landgebruik, mobiliteit, populatieprocessen, adaptatie, regionaliteit, etniciteit, ritueel gedrag, etc. Onderhavige bespreking focust aldus eerder op deze thema's.

## HET MIDDENPALEOLITHICUM 

Voor het **middenpaleolithicum** komen bovenstaande thema's in de synthesewerken wel enigszins aan bod, maar hebben met name met betrekking tot de oudere publicaties toch met een overwegend descriptieve teneur: een eerder klassieke cultuurhistorische vraagstelling vanuit een chronologischregionaal perspectief. Op basis van de kwaliteit van het toenmalige databestand was het ook moeilijk om hier voorlopig ver op in te gaan. Vaak werd hierbij nog terug gegrepen naar de culturele faciës zoals deze omschreven werden door Bordes[^379] en in grote mate op basis van het werktuigenspectrum is gebaseerd. Sinds de jaren 90 van vorige eeuw wordt deze klassificaties steeds minder toegepast.

Met de onderzoeken te Kesselt en Veldwezelt is daar enigszins verandering in gekomen. De doctoraatsonderzoeken in de eerste decennia van de jaren 2000 en daaruit vloeiende publicaties hebben geleid tot aanvullende inzichten omtrent de lithische variabiliteit en complexiteit (met sterke focus op het technologische aspect), o.m. in relatie tot grondstofgebruik, functie van de site en chronostratigrafie[^380]. Lithische variabiliteit in relatie tot grondstofgebruik in België was tevens de focus van het onderzoek van Di Modica. Uit zijn analyse blijkt dat middenpaleolitische vindplaatsen in LaagBelgië zich vaak kenmerken door het gebruik van lokale grondstof, maar aangevuld werden met lithische materialen van goede kwaliteit uit midden-België[^381].

Deze werken hebben aangetoond dat lithische technologie vaak wordt aangepast aan de kwaliteit en beschikbaarheid van grondstof. Binnen studies rond mobiliteit en grondstofvoorziening, gaat er vaak specifieke aandacht uit naar de rol van vuistbijlen of bifaciale werktuigen. Ze worden beschouwd als multifunctionele werktuigen die vaak heraangescherpt werden, lang in gebruik bleven en een hoge mobiliteit kennen. Omwille van hun specifieke typotechnologische eigenschappen worden ze bovendien als een culturele '*marker'* aangewend[^382]. Een analyse van de bifaciale technologie in België, Nederland, Noord-, Oost- en West-Frankrijk heeft aangetoond dat Vlaanderen zich op de grens bevindt van respectievelijk het verspreidingsgebied van de MTA groep en de KMG groep (zie hoger). Niet alleen resulteert dit in een grote variatie aan types van vuistbijlen en bifaciale werktuigen die hier te vinden zijn, maar mogelijk is ook sprake van een afzonderlijke groep gedefinieerd als het MBT ofwel *Mousterian with bifacial tools*[^383]*.*

Binnen een internationaal kader, spelen de belangrijkste Vlaamse vindplaatsen ook een rol in discussies rond het verschijnen van technologische innovaties, evenals bijvoorbeeld eventuele

correlatie tussen (de evolutie van) hominide types en complexe reductietechnologieën[^384]. Een belangrijk internationaal onderzoeksthema is hoe het neanderthalernederzettingsysteem georganiseerd werd en op welke wijze gebruik gemaakt werd van het landschap, dit vaak vanuit een diachronisch perspectief.[^385]

## HET LAAT- EN FINAALPALEOLITHICM 

Ook voor het **laat- en finaalpaleolithicum** kenmerken zich heel wat werken door een focus op een beschrijvende materiaalstudie. Thema's als regionale variatie en etniciteit kregen doorheen de tijd wisselende aandacht[^386]. Vragen rond populatieprocessen en culturele adaptatie in de overgang van pleistoceen naar holoceen waren altijd al aan de orde[^387]. Recent onderzoek in de Moervaartdepressie maar ook ruimer in het Scheldegebied focust zich sterk op het paleo-ecologisch kader en de impact van het veranderend klimaat op het landschap[^388]. Dit heeft geleid tot nieuwe inzichten op vlak van (re)kolonisatie en adaptatie door de finaalpaleolithische groepen[^389]. De laatste decennia komen voor de federmessergroepen ook nogal wat vragen rond mobiliteit en gebruik van het landschap aan bod[^390], waar de focus tot dan vooral *intrasite* gericht was[^391]. Hoewel bij dit onderzoek naar nederzettingsorganisatie en --dynamiek vooral functionele activiteiten als verklaring naar voren gebracht worden, kan grondige analyse soms ook leiden tot een glimp van ritueel gedrag[^392]. Het sterkst bestudeerd zijn wellicht thema's als technologie en functionaliteit[^393]. Opmerkelijk is wel dat een systematische technologische en economische vergelijking tussen de grote ensembles (Kanne, Meer, Rekem, Lommel, Zonhoven, ...), op een kleine aanzet na[^394], tot hiertoe niet heeft plaatsgevonden, terwijl er bijvoorbeeld toch heel wat materiaal gerefit is. Wel hebben verschillende individuele sites een technologische analyse ondergaan waardoor vergelijkingen in de toekomst mogelijk zijn. Periodeoverschrijdend onderzoek werd bijvoorbeeld voor het finaalpaleolithicum en vroegmesolithisch materiaal tot op heden in beperkte mate uitgevoerd[^395]. Deze analyses, die zich o.m. baseren op refitting van finaalpaleolithische (ahrensburg) en vroegmesolithische clusters, suggereren tot op zeker niveau een continuïteit in lithische technologie[^396]. De periodespecifieke methodologie die vaak gehanteerd wordt, maakt vergelijking moeilijk.

Binnen de thema's van mobiliteit en gebruik van het landschap is er ook al enkele decennia aandacht voor de locatiekeuze van sites. Voor de Kempen wordt een relatie gelegd tussen het voorkomen van finaalpaleolithische bewoningssites op eolische (dek)zandruggen nabij open water, zoals in Landschap de Liereman^425^, Meer-Meirberg en Lommel-Maatheide. Het is een aspect dat uiteraad ook aan bod komt in de hoger vermelde studies in de Scheldevallei. Op basis van de huidige stand van het onderzoek is mogelijk sprake van een verschuiving van bewoning, waarbij federmessergroepen een voorkeur hadden voor de droge oevers van meren en vennen. Terwijl tijdens de Jonge Dryas eerder de

riviervalleien werden gefrequenteerd, dit onder invloed van het drogere en koudere klimaat en het droogvallen van de meeste meren en vennen[^397].

Tot slot moet als lacune nog worden meegegeven dat onderzoek naar voedselvoorziening en consumptie door gebrek aan bronnenmateriaal voor alle periodes van het paleolithicum uitermate beperkt is gebleven.

8 BALANS VAN METHODOLOGISCH WERK:

## INLEIDING 

In de eerste versie van de onderzoeksbalans werd in dit hoofdstuk een historische schets opgemaakt van de belangrijkste methodologische ontwikkelingen. Deze inzichten werden voor de huidige versie verplaatst naar de historiek van het onderzoek. Onderhavige tekst biedt een kort overzicht van de meest courante onderzoeksmethodes en hun toepassing. Een groot aantal toont sterke gelijkenissen met de methodes die worden beschreven in het hoofdstuk mesolithicum en die daar exhaustief worden toegelicht. We verwijzen dan ook expliciet naar het hoofdstuk mesolithicum voor een uitgebreide bespreking.

## PROSPECTIEMETHODES 

Voorafgaand aan, of als startpunt van, een steentijdtraject wordt vaak een (paleo)landschappelijk onderzoek opgestart. Om de bewarings- en trefkans van steentijdvindplaatsen in te schatten, is een goed begrip van de evolutie van het (paleo)landschap immers noodzakelijk. Meestal bestaat een dergelijk onderzoek uit het uitvoeren van landschappelijk boringen (manueel of mechanisch) in een regelmatig grid of d.m.v. gerichte boorraaien. In functie van grootschalig onderzoek, werd de laatste decennia ook gebruik gemaakt van geofysische methodes, met name door gebruik te maken van elektromagnetische inductie of EMI, zoals bijvoorbeeld ter hoogte van de Moervaartdepressie[^398]. Ugent ontwikkelde de afgelopen jaren de *Cone Penetration Testing* methode gericht op het in kaart brengen van de laatglaciale paleotopografie, dat in combinatie met landschappelijke boringen en geofysisch onderzoek werd ingezet in de Scheldepolders[^399].

Vooronderzoeken gericht op steentijdvindplaatsen omvatten veldkartering, booronderzoek en proefputtenonderzoek. Deze methodes worden o.m. behandeld in de in 2006 opgestelde handleiding opgesteld voor het prospecteren naar steentijd artefactensites door het agentschap Onroerend Erfgoed[^400].

Veldkarteringen zijn geschikt voor het in kaart brengen van sites nabij of aan het oppervlak. Het succes van de methode hangt vaak vast aan het herhaaldelijk prospecteren van een vindplaats en dit onder de juiste omstandigheden. Wellicht is dat ook de reden dat ze binnen het kader van malta-archeologie niet zo vaak worden toegepast. De tijdsdruk die vaak op dergelijk onderzoek zit, laat vaak niet toe om met deze factoren rekening te houden. Nochtans mag het belang van deze prospectiemethode niet onderschat worden aangezien ze informatie kan verschaffen over de ruimtelijke omvang en samenstelling van oppervlaktevindplaatsen.

Terwijl veldkartering in de 20^ste^ eeuw een belangrijk aandeel innam, gebeurt de laatste jaren opvallend veel surveywerk plaats via booronderzoek, ook in gebieden die voorheen niet prospecteerbaar waren (bijv. bos- en heidegebied^430^). Het archeologisch booronderzoek richt zich op het steekproefsgewijs inzamelen van bodemmonsters uit sediment waarin steentijdvindplaatsen kunnen voorkomen. Deze methode wordt zowel toegepast voor vindplaatsen die afgedekt zijn door antropogene, alluviale en/of eolische sedimenten en daardoor niet zichtbaar of opspoorbaar zijn aan het oppervlak. Maar evenzeer voor zogenaamde niet-afgedekte vindplaatsen, waarvan het materiaal onder invloed van bio- en faunaturbatie dieper in de bodem is gemigreerd en daardoor (deels) bewaard. Sinds het invoege treden van de gewijzigde wetgeving inzake archeologie in 2016 en de daaraan gekoppelde Code van

Goede Praktijk zien we een sterke toename van prospecties d.m.v. booronderzoek. Vaak wordt in eerste instantie een landschappelijk booronderzoek uitgevoerd gericht op het in kaart brengen van de aardkundige situatie. Waarna een archeologisch booronderzoek (volgens de wettelijke bepalingen maximaal in een grid van 10 x 12 m) volgt waarbij het sediment wordt ingezameld en nat uitgezeefd. Bij het aantreffen van indicatoren (vuursteen, verbrand bot, hazelnoot,...) dient vervolgens overgegaan te worden tot een verdicht grid (5 x 6 m) zodat de vindplaats verder kan gewaardeerd worden. Deze opeenvolging van beide methodes biedt het voordeel dat vrij snel grote gebieden gekarteerd kunnen worden. Er zijn echter ook wat nadelen aan verbonden[^401]. Zo is de bodemopbouw in het beperkte (en soms geroerde) staal niet altijd duidelijk te interpreteren en worden paleobodems soms niet opgemerkt of de bodemgaafheid niet altijd correct ingeschat. Ook blijkt de methode van archeologisch boren weinig geschikt voor vindplaatsen met een lage densiteit aan vondsten en/of beperkte omvang. Onderzoek naar de omvang van finaalpaleolithische en mesolithische vuursteenclusters heeft aangetoond dat ze vaak beperkt zijn in omvang, in de orde van 20-30 m². Een recente evaluatie van steentijdprospectietechnieken in Vlaanderen en Nederland wijst uit dat de klassieke boorstrategie weinig geschikt is voor het treffen van lage densiteit vindplaatsen[^402]. Concreet gaat het om vindplaatsen die een lagere vondstdichtheid hebben dan 80 vondsten per m² (bij zeven over 3 mm), en die kleiner zijn dan 200 m². Dit betekent dat de kans groot is dat dergelijke kleine en/of lage densiteit vindplaatsen gemist worden met deze prospectiemethode. Tot slot verwijzen we naar de eerder aangehaalde problematiek rond selectiecriteria om over te gaan tot verkennend en vervolgens waarderend onderzoek[^403].

Bovendien zien we dat deze strategie in de praktijk vaak te ondiep wordt uitgevoerd en slechts een partieel beeld van de bodemopbouw- en evolutie wordt verkregen. Op die manier wordt voornamelijk ingezet op de detectie van niet-afgedekte finaalpaleolithische en mesolithische vindplaatsen. Terwijl de systematische opsporing van zowel ondiep als diep afgedekte paleolandschappen en eventuele vindplaatsen in mindere mate gebeurt. En ook in die gevallen focust het onderzoek zich over het algemeen op de top van het pleistoceen. Het is een problematiek die reeds eerder werd aangekaart[^404]. Voor het finaalpaleolithicum merken we een traag groeiende bewustwording voor de mogelijke aanwezigheid van een ondiep afgedekte Usselobodem en eventueel daarmee geassocieerde vindplaatsen. Echter, finaalpaleolithische vindplaatsen zijn niet enkel met deze bodem geassocieerd. Dus de afwezigheid (of onzichtbaarheid) van een Usselobodem impliceert niet dat er geen finaalpaleolithische vindplaats kan voorkomen. In de rivierduinen langsheen de Schelde bijvoorbeeld bevinden sites zich in het eolisch zand los van enige paleosol. Om dergelijke contexten te vinden is een continue bemonstering van de top tot het contact met de pleniglaciale sedimenten noodzakelijk.

Terwijl met name voor de evaluatie van de steentijdvindplaatsen in de Kempen tot enkele decennia terug nog regelmatig gebruik werd gemaakt van proefputtenonderzoek, lijkt het belang van deze methode af te nemen in de huidge praktijk. Nochtans bieden proefputten het voordeel dat er een groter staal kan ingezameld worden en beter zicht verkregen op de aardkundige situatie.

Aandacht voor het opsporen van afgedekte laat- en middenpaleolithische vindplaatsen ontbreekt nagenoeg volledig in de huidige (en vroegere), preventieve archeologische praktijk. Een basismethodiek of concrete richtlijnen om dergelijk onderzoek te integreren in een preventief traject is momenteel niet voor handen. Vanuit academische hoek worden in Vlaanderen wel initiatieven genomen om bijv. door middel van diepe mechanische sonderingen (bijv. het Flemish Valley Survey project) of nieuwe technieken (bijv. de hierboven vermelde *cone penetration testing*[^405]) hieraan tegemoet te komen. Ook in Wallonië zet men ondertussen in op deze methodiek voor het opsporen

van middenpaleolithische vindplaatsen zoals o.m. te Rocourt[^406] en Remicourt[^407]. In Frankrijk zet men daan weer volop in op systematisch mechanisch proefputten en/of -sleuvenonderzoek voor de detectie van paleolithische niveaus bij grootschalige ontwikkelingen[^408]. Wat deze onderzoeken bindt, is de integratie van de geomorfologische expertise en de inzet op pale-ecologisch en dateringsonderzoek reeds tijdens het vooronderzoek gericht op het opstellen van een voldoende betrouwbaar chronostratigrafisch kader.

### Opgravingsmethodes 

Terwijl in het pre-Maltatijdperk het opgraven in 3D de norm was, wordt dit de afgelopen decennia nauwelijks nog toegepast. Voor finaalpaleolithische (en mesolithische) opgravingen wordt standaard opgegraven in artificiële vakken van ¼ m² en niveaus van 5 cm, waarbij het sediment nat wordt uitgezeefd. De methodiek werd in Vlaanderen voor het eerst toegepast in het kader van het grootschalig onderzoek in de Antwerpse haven (Verrebroek -- Dok[^409]). Deze methodiek is gericht op een efficiënte en snelle berging van de prehistorische resten, terwijl door het toepassen van relatief kleine zeefeenheden (namelijk 50 cm x 50 cm x 5cm) nog 'voldoende' zicht wordt behouden op de horizontale en verticale spreiding van het archeologisch materiaal. Maar uiteraard is de resolutie minder fijn in vergelijking met een 3D registratie. Bovendien houdt deze mechanische werkwijze in dat er mogelijke beschadigingen optreden op het lithisch materiaal die verdere analyses bemoeilijken. Beschadigingen kunnen zowel optreden tijdens het inzamelen van de vondsten (bij gebruik van metalen opgraafmateriaal) als tijdens het zeven (met name wanneer metalen zeefdraad wordt gebruikt)[^410]. Ook de detectie van grondsporen (natuurlijk een antropogene) wordt door deze werkwijze bemoeilijkt. Het aanleggen van een sporenvlak blijft dan ook essentieel.

In de praktijk zien we dat er over het algemeen een waarderend testputtenonderzoek direct voorafgaand aan de opgraving wordt gerealiseerd. Deze testputtenfase heeft tot doel om de clusters verder te waarderen en af te bakenen en zo de zone van de opgraving te bepalen. Vaak is er immers op basis van het voorafgaand archeologisch booronderzoek onvoldoende zicht op de ruimtelijke spreiding van het materiaal. Een testputtenonderzoek wordt vaak vanuit praktische overwegingen net voorafgaand aan de opgraving geprogrammeerd.

Een bijzonder gegeven voor de steentijdopgravingen die binnen een maltacontext verliepen, is dat ze over het algemeen niet in hun totaliteit worden onderzocht. Voor de vindplaats Beveren -- LPWW werd aan de hand van archeologisch booronderzoek een zone van 6ha afgebakend, maar werd slechts 1ha geselecteerd voor de opgraving[^411]. De overige steentijdvindplaatsen gingen verloren bij de daaropvolgende ontwikkeling van het gebied. Deze selectie wordt vooral ingegeven vanuit de bezorgheid dat de kostprijs voor het steentijdonderzoek te hoog zou oplopen.

De hierboven geschetste opgravingsmethodiek heeft betrekking op opgravingen waarbij systematisch onderzoek zowel gericht op mesolithische als finaalpaleolithische vindplaatsen. Het merendeel van de recent opgegraven finaalpaleolithische vindplaatsen werd echter eerder 'per toeval' ontdekt. Ze kenmerken zich over het algemeen door hun eerder beperktere omvang, alhoewel we hierbij direct opmerken dat in de meeste gevallen geen gericht vooronderzoek werd uitgevoerd naar de steentijdaanwezigheid en dus ook niet met zekerheid kan gesteld worden dat ze geïsoleerd voorkomen. De manier waarop ze opgegraven zijn, varieert, maar over het algemeen werd eveneens overgegaan tot onderzoek in vakken. Te Tongeren-Plinius werden zeefvakken van 50cm x 50cm

toegepast en kon het materiaal niet volledig worden opgegraven omwille van tijdsdruk[^412]. Ook te Ruien-Rosalinde werd overgeschakeld naar een methode van zeefvakken van 50cm x 50cm x 5cm, maar de haardstructuur wel in 3D opgegraven. Aanvullend werden bovendien in een ruimere zone archeologische boringen geplaatst, die evenwel geen extra clusters opleverden[^413].

Recente opgravingen naar de oudere periodes werden tot op heden in Vlaanderen enkel vanuit een academische vraagstelling uitgevoerd. De opgravingsmethodes variëren er, afhankelijk van de vraagstelling en middelen, van het inzamelen van materiaal uit het geologisch profiel tot een gedetailleerde vlakopgraving in 3D. Een standaard aanpak voor Vlaanderen is er dus niet. Maar wanneer de naburige regio's bekijken waar wel onderzoek gebeurt naar middenpaleolithische vindplaatsen binnen het preventieve traject dan zien we vaak een keuze voor een gedetailleerde 3D registratie per stratigrafische eenheid voor artefacten, terwijl kleiner materiaal wordt ingezameld in zeefeenheden van ¼ m² [^414].

### Absolute dateringen 

Bij de bespreking van de dateringsproblematiek gaven we reeds aan dat absolute dateringen die rechtstreeks gelinkt kunnen worden aan steentijdclusters uitzonderlijk zijn. Dit heeft onder meer te maken met de afwezigheid van evidente haardstructuren op de meeste vindplaatsen. Uitzonderingen hierop zijn bijv. Ruien-Rosalinde[^415] en Tongeren -- Plinius[^416]. In het geval van haardstructuren bieden hiermee geassocieerde houtskoolresten en verbrand bot mogelijkheden tot 14C-dateringen. Latente structuren of een losse spreiding van verkoold materiaal tussen de lithische vondsten komen iets vaker voor, maar in dergelijke gevallen is de associatie met de artefacten moeilijker vast te stellen. Het uitvoeren van voldoende dateringen is in dat geval van belang, evenals een kritische selectie van de stalen. Houtskoolresten komen bijvoorbeeld van nature (bijv. door bosbranden) voor in de grond, ook in concentraties, en zijn dus minder geschikt voor dateringsonderzoek. Dateringen op wit verbrand bot stellen eveneens problemen, met name wanneer het om contexten gaat die niet of heel laat afgedekt werden[^417].

Dateringen rechtstreeks op het archeologisch materiaal zijn enkel mogelijk indien beschikbaar residue aanwezig is, maar dat lijkt uitzonderlijk het geval. In Vlaanderen werd enkel te Rekem het hars op een spits gedateerd[^418]. Wanneer bewerkt bot wordt aangetroffen, biedt dit uiteraard ook dateringsmogelijkheden. Maar ook die situatie is eerder uitzonderlijk voor Vlaanderen. Een voorbeeld hiervan is het gegraveerd laatpaleolithisch bot dat te Schulensbroek werd gevonden en door middel van radiokoolstofdateringen werd onderzocht[^419].

Thermoluminiscentiedateringen zijn mogelijk op anorganische materialen die verhit werden, maar biedt over het algemeen een minder grote resolutie in vergelijking met 14C-dateringen. Dergelijke dateringen werden uitgevoerd op verbrande stenen in Rekem[^420] en in Meer IV^451^, maar konden er enkel de laatglaciale ouderdom bevestigen.

Indien een vindplaats in stratigrafische verband voorkomt, biedt de datering van de geassocieerde bodemhorizonten of -afzettingen mogelijkheden. Finaalpaleolithische vindplaatsen die in een

Usselobodem voorkomen, zoals Arendonk -- Liereman[^421] en Lommel -- Maatheide[^422], werden o.m. gedateerd op basis van het houtskoolmateriaal in de Usselobodem. De houtskoolresten die over het algemeen in de Usselobodem zijn aangetroffen, zijn het resultaat van natuurlijke bosbranden. Ook hier dient de belangrijke kanttekening geplaatst te worden dat ze niet direct de vindplaats zelf dateren. Organische paleosols worden beter gedateerd d.m.v. AMS-dateringen, maar hierbij is het belangrijk dat enkel terrestrische plantenresten (en geen waterplanten) geselecteerd worden[^423].

Ook OSL-dateringen (Optical Stimulated Luminescence) kunnen aangewend worden voor de datering van sedimenten, zoals bijvoorbeeld te Ruien-Rosalinde[^424], Oudenaarde-Markt[^425], Arendonk-Korhaan en Lommel-Maatheide[^426]. Op basis van het onderzoek van deze laatste site, onderstrepen de auteurs het belang van voldoende en een continue sequentie van staalname, met name wanneer de stratigrafische opeenvolging van de sedimenten niet zichtbaar is.

### Paleo-ecologie 

Paleo-ecologie tracht aan de hand van organische resten zoals macroresten, pollen, fauna en diatomieeën het landschap te reconstrueren. Voor dergelijk onderzoek zijn niet enkel de resten van belang die direct met de antropogene resten geassocieerd zijn, maar zijn ook van belang om het omringende landschap in beeld te brengen. De situatie waarbij plantaardige of dierlijke resten direct geassocieerd zijn met antropogene sporen komt overigens niet zo vaak voor in Vlaanderen en kan terug gevonden worden in stratigrafisch bewaarde vindplaatsen binnen een alluviale context. Maar zoals meermaals aangegeven, krijgen deze vindplaatsen net minder aandacht binnen de preventieve archeologie.

Paleo-ecologisch onderzoek wordt in Vlaanderen vooral vanuit een bredere, regionale vraagstelling uitgevoerd en is gericht op de diachrone reconstructie van het landschap tijdens het laatglaciaal en (vroeg)holoceen, vaak in combinatie met sedimentologische studies. Vanuit de UGent werd intensief onderzoek uitgevoerd in de Scheldevallei, met onder meer focus op de Moervaartdepressie[^427] en de Wase Scheldepolders[^428]. Voor de Kempen vermelden we o.m. het paleo-ecologisch onderzoek ter hoogte van de verveende depressies in het landschap De Liereman[^429] en langs de Grote Nete[^430].

Voor het middenpaleolithicum vormden de rijke fauna-assemblages die o.m. werden aangetroffen te Zemst-Bos van Aa[^431], te Uitbergen -- Groeve Maes[^432] en meer recentelijk te Oekene-Groeve Maes[^433] aanleiding tot gedetailleerde studies. Ze gaven bovendien indicaties omtrent de relatieve ouderdom van de artefacten die er werden gevonden. Te Veldwezelt-Hezerwater werden een aantal niveaus aangetroffen waar het lithisch materiaal direct geassocieerd is met glaciale fauna[^434]. Voor deze types van vindplaatsen blijkt een gedetailleerde studie waarbij geomorfologische, bodemkundige en ecologische data worden geïntegreerd binnen hun stratigrafisch kader essentieel voor de interpretatie van de menselijke resten[^435].

### Vormtypologische analyses 

In de 19^de^ eeuw en een groot deel van de 20^ste^ eeuw werd het onderzoekskader in Vlaanderen sterk beïnvloed door het schema dat in Frankrijk werd opgesteld vanuit de evolutionistische theorieën. Lange tijd blijkt deze theorie van een unilineaire, voor de hele wereld gelijk lopende evolutie, tot de grondbeginselen van het Belgisch prehistorisch denken behoren en werden vindplaatsen in het bestaande kader ingepast op basis van specifieke 'gidsfossielen' of types.

In de decennia na WOII valt vooreerst de opkomst van de statistiek in het archeologisch onderzoek op. Nieuwe typologieën en bijhorende statistische methodes ontwikkeld werden door Bordes[^436] ontwikkeld voor het middenpaleolithicum. Hij creëerde een lijst van acheuleaan en middenpaleolithische types naast een basisomschrijving voor kernreductiestrategieën. De focus op de zogenaamde gidsfossiel verschoof hiermee naar een kwantitatieve en kwalitatieve analyse van een reeks types. Bovendien resulteerde deze analyse tot de beschrijving van enkele culturele groepen. Zijn werk imponeerde een groot aantal prehistorici, ook in België. De Sonneville-Bordes en Perrot[^437], stelden een typologische lijst op voor het jongpaleolithicum en verschaften daarmee een werkinstrument om ook sites waar enkel lithisch materiaal bewaard was op een degelijke wijze te bestuderen. Ten slotte werd voor \"l\'Epipaléolithique\" (finaalpaleolithicum en mesolithicum) in de tweede helft van de jaren zestig een gelijkaardige typologie uitgewerkt door G. Rozoy en de \"*Groupe d\'Etude de l\'Epipaléolithique*\"[^438].

In België werden deze Franse kwantitatieve analysetechnieken vrij snel door enkele Belgische vorsers geaccepteerd[^439]. In 1960 publiceerde J. De Heinzelin zijn eigen \"*Principes de diagnose numérique en typologie*\". Daarin evalueerde hij de mogelijkheden van de statistiek voor het typologisch onderzoek. Iets later publiceerde dezelfde auteur ook een typologisch handboek[^440], waarin hij poogde de tot op dat moment geconcipieerde types te inventariseren (uitsluitend lithische artefacten). Het was de bedoeling daarmee een einde te maken aan de heersende verwarring ten gevolge van de verschillende typologieën. Concreet leverde dat voor het finaalpaleolithicum echter geen ernstige statistische analyses op. Door K. Narr[^441] werd de methode zelfs vrij expliciet in vraag gesteld. Ook cumulatieve grafieken werden voor paleolithische ensembles in Vlaanderen uiteindelijk zelden opgesteld (bijv. in Kanne). Van Noten, die voor Meer II wel een cumulatieve grafiek uittekende, vond dat die een verkeerd beeld gaf van de nederzetting[^442].

In Nederland werd in de jaren 1950 en 1960 overigens wel een groot wetenschappelijk project uitgewerkt (o.l.v. A. Bohmers), waarbij ook het finaalpaleolithicum statistisch ontleed werd. Het project is echter om praktische redenen grotendeels in zijn opbouwfase blijven steken en de daaropvolgende publicaties vielen grotendeels op de 'gidsfossielen' terug. Vooral discussie over de juiste toewijzing van de sites aan één of andere groep en de plaats van die groep in een groter geheel bleven centraal staan.

Intussen waren in de theoretische geschriften uit de Verenigde Staten de eerste oproepen tot nieuwe benaderingswijzen te vinden, de zogenaamde *New Archaeology*. Voor de kleine finaalpaleolithische opgravingen in de jaren 1960 en 1970 bleef de verwerking echter vaak beperkt tot typochronologische studie van het materiaal en beschrijving van de terreincontext.

Voor het middenpaleolithicum vormen (vorm)typologische classificaties, die teruggaan op het werk van Bordes[^443], nog steeds een basis van lithische analyses, maar deze worden over het algemeen op minder rigide wijze en in combinatie met technologische aspecten gehanteerd.

Voor het laat- en finaalpleolithicum wordt eveneens teruggegrepen naar oude classificaties[^444]. Bij onze noorderburen verschijnen regelmatig synthesestudies met aanvulling en nieuwe inzichten in de chronologie[^445].

### Technologische analyses 

Technologische analyses focussen zich op de analyse van het productieproces en gebruik van artefacten. Dergelijk onderzoek werd vanaf de tweede helft van vorige eeuw vanuit verschillende hoeken ontwikkeld en resulteerde ondertussen in een heel breed scala aan methodes, waartoe ook refitting, gebruikssporenanalyse en grondstofanalyse horen (zie verder). Een belangrijk concept binnen technologische studies is de zogenaamde *chaîne opératoire*, oorspronkelijk gedefinieerd door Leroi-Gourhan en kan omschreven worden als de reconstructie van de organisatie van een lithisch reductieproces waarbij zowel de opeenvolgende mentale als technische handelingen in kaart worden gebracht. Vooral vanaf de jaren '80 en '90 van de 20^ste^ eeuw heeft de aandacht voor lithische technologie een nieuwe dimensie gegeven binnen het onderzoek naar paleolithische ensembles.

Lithische technologie kan o.m. aan de hand van een attributenalyse onderzocht worden. Een dergelijke attributenanalyse richt zich op morfologische kenmerken (afmetingen, breuken, vorm,...), impactkenmerken (bijv. aanwezigheid van een slagbult, lip,...) en dorsale patronen (ribben, afslagrichting van de negatieven,...) van de individuele artefacten in beeld en tracht op die manier de verschillende reductiestrategieën te reconstueren. Een attributenanalyse biedt het voordeel dat er op een relatief snelle en eenvoudige wijze inzicht kan verkregen worden omtrent een aantal technologische aspecten, maar deze methode bereikt niet het detailniveau zoals deze met refitting kan bekomen worden.

Dergelijke attributenanalyse werd in Vlaanderen voor het finaalpaleolithicum eerst te Rekem[^446] en later te Verrebroek -- Dok 2[^447], Doel, Gent-Tweekerkenstraat[^448], Weelde-Eindegoorheide[^449] en Ruien[^450]. toegepast. Ze wordt ondertussen ook in heel wat malta-onderzoeken geïntegreerd. Ook voor de vindplaatsen de Kesselt-Op de Schans[^451] en Veldwezelt- Hezerwater^483^ werd een attributenanalyse uitgevoerd.

### Refitting 

Bij refitting worden de individuele, stenen artefacten terug op elkaar gepast. Refitting levert gedetailleerde informatie op over de lithische technologie, maar ook over de ruimtelijke organisatie binnen en tussen clusters en transport van grondstof of artefacten. Tot slot levert refitting inzicht over de mogelijke gelijktijdigheid van clusters en tafonomische processen.

Een reflectie over het nut en de opportuniteit van deze methode is regelmatig expliciet naar buiten gebracht[^452].

In Vlaanderen werd refitting toegepast op een aantal middenpaleolithische ensembles te Kesselt-Op de Schans[^453] en Veldwezelt - Hezerwater[^454]. Ook het laatpaleolithisch materiaal te Kanne werd gerefit. Voor het finaalpaleolithicum werd dit toegepast te Meer en Rekem[^455], Verrebroek-Dok 2[^456], ZonhovenMolenheide[^457] en recentelijk op Ruien-Rosalinde[^458].

### Gebruikssporen, projectielanalyse en residuanalyse 

Gebruikssporen- of microwearanalyse tracht door middel van microscopisch onderzoek van slijtage- en impactsporen en vergelijking met experimenteel materiaal te achterhalen op welke wijze lithische artefacten gebruikt werden. Het succes van de methode is sterk afhankelijk van de postdepositionele processen die een impact gehad hebben op het lithisch materiaal[^459], maar tevens van de wijze waarop ze ingezameld en behandeld werden nadien.

In Vlaanderen werd voor het eerst op de site van Meer-Meirberg 2 een combinatie van refitting, microwearanalyse en ruimtelijke analyse toegepast, wat internationaal heel wat weerklank kreeg[^460]. Aangevuld met een uitgebreide attributenanalyse kreeg deze benadering later ook in Rekem een doorgedreven toepassing[^461].

Tot 2012 beschikt de Eenheid Prehistorische Archeologie van de KULeuven over expertise in functioneel onderzoek (microwearanalyse) (Caspar, V. Rots) en in experimenteel werk met oog op de opbouw van *middle range theory*. Ondertussen is V. Rots verbonden aan het Luikse Tracéolab (Universiteit Luik). Sinds kort wordt ook aan de UGent expertise op vlak van microwearanalyse uitgebouwd (E. Hallbrucker).

Microwear analyses op paleolithische ensembles in Vlaanderen bleef voorlopig beperkt. Ook binnen het kader van malta-onderzoek wordt de methode nauwelijks toegepast. Een uitzondering hierop vormt het recent afgeronde sythese-onderzoek uitgevoerd door Tracéolab op een selectie van het materiaal van Beveren-LPW, Lommel-Maatheide, Meeuwen-Monnikswijer en Tongeren-Plinius.^494^ De studie bracht o.m. informatie aan het licht omtrent bewerking van planten (op schrabbers, maar ook op microklingen) en aanwezigheid van montagesporen. Daarnaast formuleert de studie een aantal praktische richtlijnen naar inzamelings- en opgravingsstrategie toe (o.m. impact van gebruik van metalen opgravingsmateriaal). Uit de studie bleek ook dat op een aantal artefacten nog residusporen bewaard waren (met name van plantaardig materiaal) en dat ook deze methode tot interessante resultaten kan leiden.

In tegenstelling tot microwearanalyse, stelt projectielanalyse minder eisen op vlak van bewaring van het materiaal. Deze analyse focust zich vooral op breuken en afsplinteringen die het resultaat zijn van de impact van het projectiel op het geschoten wild. Uit de hierboven vermelde synthesestudie blijkt dat de methode enkel zinvol is indien voldoende elementen kunnen geanalyseerd worden.

### Ruimtelijke analyse 

Ingeburgerd is ook het gebruik van ruimtelijke analyse en GIS-toepassingen, zowel op de site-niveau[^462], als voor verspreidingsanalyse van sites in studies van paleolithisch landgebruik en mobiliteit[^463]. Het gebruik van ruimtelijke statistiek is daarbij voorlopig wel beperkt gebleven[^464].

### Grondstofanalyse 

Grondstofanalyse focust zich op de herkomst van het materiaal waaruit artefacten zijn gemaakt. Dergelijke analyses geven o.m. inzichten op de adaptie van technologie naargelang de grondstofvereisten, mobiliteit, territorialiteit en culturele aspecten.

De bulk van het archeologisch materiaal uit het paleolithicum in Vlaanderen bestaat uit lithisch materiaal. Daarbij neemt vuursteen het belangrijkste aandeel in, maar ook andere grondstoffen zoals Wommersom, kwartsieten en ftaniet werden gebruikt. In mindere mate wordt het gebruik van zandsteen en uitzonderlijk fossiel hout of bitumen vermeld[^465]. Over het algemeen worden de analyses op macroscopisch niveau uitgevoerd, waarbij zaken als kleur, korrelgrootte, inclusies, ... vergeleken worden met gekende ontsluitingen. Voorbeelden hiervan zijn het zogenaamde spiennevuursteen of wommersomkwartsiet. Teneinde enige uniformiteit in de determinatie van de talloze types gesteenten, in het bijzonder vuursteen, na te streven is het wenselijk om regionale referentiecollecties of lithotheken aan te leggen. Een eerste aanzet daartoe is gezet aan de Gentse universiteit met de uitbouw van een (vooralsnog niet openbaar toegankelijke) referentiecollectie van gesteenten en kleien, onder de naam Flepostore (Flemish pottery and stone reference collection)[^466], waarin voorlopig voornamelijk referentiestukken uit de Scheldevallei zijn opgenomen. Naast macroscopische kenmerken, worden ook in de mate van het mogelijke mineralogische en geochemische kenmerken opgenomen. Tevens werd onlangs aan de UGent ook een protocol uitgewerkt om geochemische herkomstanalyses (aan de hand van µXRF) mogelijk te maken van de in Vlaanderen gebruikte vuursteensoorten. Daarbij konden, in een eerste fase van het onderzoek, reeds artefacten van verschillende sites uit de Scheldevallei (e.g. Kerkhove, Bazel, Ruien, Verrebroek Aven Ackers) onder andere succesvol gekoppeld worden aan ontsluitingen van Turoniaan vuursteen uit de regio Doornik-

Rijssel^500^.

[^379]: Bordes 1950.
[^380]: Bringmans 2006; Van Baelen 2014.
[^381]: Di Modica 2010.
[^382]: Ruebens *et al.* 2014.
[^383]: Ruebens & Di Modica 2011; Ruebens *et al.* 2014.
[^384]: Moncel *et al.* 2020.
[^385]: Zie o.m. Goval 2012.
[^386]: Schwabedissen 1954; Narr 1968; Perdaen 2004.
[^387]: De Bie & Vermeersch 1998, 29-43.
[^388]: Bogemans *et al.* 2012; Van Gils *et al.* 2012; Crombé *et al.* 2013, 2014; Crombé 2018; Bos *et al.* 2017; Storme *et al.* 2017.
[^389]: Crombé 2018 ; Crombé 2020.
[^390]: De Bie & Van Gils 2006, 781-790; Crombé *et al.* 2008, 195-205.
[^391]: Van Noten 1978; Lauwers 1988, 217-234; De Bie *et al.* 2002, 139-164.
[^392]: De Bie & Caspar 2000.
[^393]: Van Noten 1978; Vermeersch *et* *al*. 1987, 7-56; Caspar & De Bie 1996, 437-460; Vanderbeken 1998; Caspar & De Bie 2000, 341-355; De Bie & Casper 2000; Perdaen & Ryssaert 2002, 75-81; Perdaen 2004; De Bie 2006, 277-295; Vandendriessche & Crombé 2019a.
[^394]: De Bie 1999, 179-188.
[^395]: Perdaen 2004; Vandendriessche & Crombé 2020.
[^396]: Vandendriessche & Crombé 2020; Vandendriessche 2021. ^425^ Vanmontfort *et al.* 2010.
[^397]: Crombé *et al.* 2018.
[^398]: Meyelemans *et al.* 2011; De Smedt *et al.* 2011a & b.
[^399]: Verhegge 2015; Verhegge *et al.* 2018; Verhegge *et al.* 2021.
[^400]: Van Gils & Meylemans 2019. ^430^ De Bie 2005b, 6.1-6.10.
[^401]: Zie o.m. Noens 2019 voor een uitgebreide discussie.
[^402]: Verhagen *et al.* 2011, 32-33.
[^403]: Zie Van Baelen & Noens in voorbereiding voor een uitgebreide discussie.
[^404]: De Clercq *et al.* 2012; Crombé *et al.* 2018.
[^405]: Verhegge *et* *al*. 2018; Verhegge *et* *al*. 2021.
[^406]: Pirson *et* *al*. 2019.
[^407]: Delvoie *et* *al*. 2016a, maar zie ook Delvoie 2017 en Delvoie *et* *al*. 2016b voor andere voorbeelden.
[^408]: Prilaux & Talon 2012.
[^409]: Crombé (red.) 2005.
[^410]: Cnuts *et* *al*. 2021.
[^411]: Perdaen *et* *al*. 2015.
[^412]: Bink 2007.
[^413]: Verbrugge *et* *al*. 2021.
[^414]: Jarry *et* *al*. 2007; Prilaux & Talon 2012; Van der Sloot *et* *al*. 2009.
[^415]: Verbrugge *et* *al*. 2021.
[^416]: Bink 2007.
[^417]: Crombé *et* *al*. 2021.
[^418]: De Bie 1988.
[^419]: Van Peer 2020.
[^420]: De Bie & Caspar 2000, 42-43. ^451^ Charles 1994.
[^421]: Van Gils *et* *al*. 2009; Vanmontfort *et* *al*. 2010.
[^422]: De Bie & Van Gils, 2006.
[^423]: Bos *et* *al*. 2017; 2018a & b; Crombé *et* *al*. 2011; Verhegge *et* *al*. 2021.
[^424]: Verbrugge *et* *al*. 2021.
[^425]: Crombé *et* *al*. 2018.
[^426]: Derese *et* *al*. 2012.
[^427]: Zie o.m. Bos *et* *al*. 2018a&b; Crombé *et* *al*. 2013 & 2014; Crombé *et* *al*. 2020.
[^428]: Verhegge *et* *al*. 2021; Crombé (red.) 2005.
[^429]: Meirsman *et* *al*. 2008; Verbruggen 2013; Verbruggen *et* *al*. 2019.
[^430]: Gelorini *et* *al*. 2007.
[^431]: Germonpré 1999.
[^432]: Germonpré & Ervynck 1988.
[^433]: De Wilde 2011.
[^434]: Bringmans 2006.
[^435]: Bringmans 2006; Van Baelen 2014; Meijs 2011.
[^436]: Bordes 1950, 17-34.
[^437]: de Sonneville-Bordes 1961, 421-443; de Sonneville-Bordes 1956.
[^438]: Rozoy 1968; Rozoy 1978; GEE 1969, 355-366; 1972, 364-375; 1975, 319-332.
[^439]: Verheyleweghen 1956, 179-258.
[^440]: De Heinzelin 1962.
[^441]: Narr 1968.
[^442]: Van Noten 1968, 149-153.
[^443]: Zie o.m. Débenath & Dibble 1993.
[^444]: Zie o.m. Arts & Deeben 1981; Bohmers 1956; Campbell 1977; Demars & Laurent 2000; Van Noten 1978.
[^445]: Zie o.m. Amktreutz *et* *al*. 2016; Beuker 2010; Deeben *et* *al*. 2005.
[^446]: De Bie & Caspar 2000.
[^447]: Perdaen & Ryssaert 2002 ; Perdaen 2004.
[^448]: Ryssaert *et* *al*. 2004.
[^449]: Verbeek 1999.
[^450]: Vandendriessche 2021.
[^451]: Van Baelen 2014. ^483^ Bringmans 2006.
[^452]: Cahen 1976, 81-93; Cahen *et* *al*. 1980, 209-259; De Bie 2007, 31-44; Vandendriessche 2021.
[^453]: Van Baelen 2014.
[^454]: Bringmans 2006.
[^455]: De Bie & Caspar 2000.
[^456]: Perdaen & Ryssaert 2002.
[^457]: Vermeersch 2015.
[^458]: Vandendriessche 2021.
[^459]: Vermeersch 1999.
[^460]: Van Noten 1978.
[^461]: De Bie & Caspar 2000; De Bie 2006, 277-295. ^494^ Cnuts *et* *al*. 2021.
[^462]: De Bie & Caspar 2000; Dijkstra *et* *al*. 2007, 16-47.
[^463]: Crombé & Verbruggen 2002, 165-180; De Bie & Van Gils 2006, 781-790; Van Gils & De Bie 2007; Perdaen *et* *al*. 2008, 317327.
[^464]: De Bie & Caspar 2002, 139-164.
[^465]: Van der Haegen & Crombé 1994; Ryssaert 2004.
[^466]: [[https://flepostore.ugent.be/]{.underline},](https://flepostore.ugent.be/) geraadpleegd op 12 mei 2021. ^500^ Fiers *et* *al*. 2017; Laforce *et* *al*. 2021.
