# BALANS VAN THEORETISCH WERK 

*Overzicht van theoretische ontwikkelingen (reflecties over de discipline)*

Zoals uit het historische overzicht is gebleken, is het paleolithisch onderzoek in Vlaanderen traag op gang gekomen. Tot halfweg de twintigste eeuw heeft het zeker geen bijdrage gehad in ontwikkelingen op theoretisch vlak.

Voor de jaren 1950 kunnen we stellen dat minstens S.J. De Laet in Gent zeker op de hoogte was van de internationale methodologische en theoretische ontwikkelingen in de archeologie. Hij publiceerde als enige Vlaamse auteur een standaardwerk over de aard en de problemen van de archeologie, waarbij hij -- aan de ene kant - de kritiek niet spaarde op de traditionele benaderingen, ongefundeerde etnische interpretaties en het gevaar voor politiek misbruik. Aan de andere kant formuleerde hij ook bedenkingen bij de positivistische benadering van de Amerikaanse archeologie[^467] (later in vele talen vertaald).

Helaas heeft deze actie niet kunnen leiden tot bestendige theoretisch reflectie in de Vlaamse archeologie, die, in tegenstelling tot Nederland bijvoorbeeld, nooit actief heeft meegespeeld in de snelle epistemologische ontwikkelingen die zich vanaf de jaren 1960 internationaal hebben afgespeeld, in het bijzonder in de Angelsaksische wereld. Deze inzichten drongen maar sporadisch en in verdunde vorm door in projecten van paleolithisch onderzoek, in Meer of in Rekem bijvoorbeeld.

Recentere publicaties in Vlaanderen die expliciet handelen over theoretische ontwikkelingen in de archeologie van jagers-verzamelaars of over theorievorming in de archeologie, kennen we enkel in de vorm van licentiaatsverhandelingen[^468].

[^467]: De Laet 1957.
[^468]: De Bie 1988; Van Reybrouck 1993; Leysen 2003.
